### ISSUE TITLE
ConfirmEdit blocks SMW

### ISSUE THREAD

**Issue by stefahn** [SemanticMediaWiki/SemanticMediaWiki#1406] opened 2016-02-16 15:00 UTC
I have a fresh install of both MediaWiki and SMW. SMW was installed by composer without any issues. 

After adding the first property I wanted to check Special:Browse, but the Special page wouldn't load. I also saw that SMW namespaces didn't exist.
I disabled the other extensions and found that ConfirmEdit is causing the trouble. If I disable ConfirmEdit, SMW runs fine (namespaces exist and Special pages too).

I tested this both with ConfirmEdit 1.4.0 (bundled with MW 1.26.2) and the master version of ConfirmEdit. Both seem to block SMW.

Versions:
Semantic MediaWiki	2.3.1
MediaWiki 	1.26.2
PHP 	5.4.45-0+deb7u2 (cgi-fcgi)
MySQL 	5.5.47-0+deb7u1
ICU 	4.8.1.1
More version info see http://awesomescreenshot.com/0515mx7i91

**Comment by JeroenDeDauw** [comment] 2016-02-16 15:12
Thanks for reporting the issue!

**Comment by mwjames** [comment] 2016-02-16 18:31
I do think this issue has been discussed before on the mailing list back in 2014 [0].

[0] http://wikimedia.7.x6.nabble.com/SMW-Namespaces-seem-to-be-blocked-td5032732.html

**Comment by stefahn** [comment] 2016-02-16 18:47
@mwjames : Good find. Funny that back then it was me too, who encountered that problem. But this time it's a brand new install. 
Hope someone can reproduce the issue.

**Comment by mwjames** [comment] 2016-03-12 16:17
Unless someone finds the reasons as to what `ConfirmEdit` does so that both cannot be used together, it is unlikely that SMW core can provide any assistance in solving this issue.

Feel free to re-open this issue in case some actionable tasks can be assigned to it.

**Closed by mwjames** 2016-03-12 16:17 UTC

**Comment by kghbln** [comment] 2016-06-23 09:41
@stefahn FYI https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1686
