### ISSUE TITLE
PHP Fatal error:  Can't inherit abstract function Copyable::getCopy()

### ISSUE THREAD

**Issue by plegault3397** [SemanticMediaWiki/SemanticMediaWiki#785] opened 2015-02-05 00:16 UTC
MediaWiki          1.23.8
PHP        5.3.3 (apache2handler)
MySQL  5.6.19-log
Semantic MediaWiki       2.2 alpha (d456c95) 13:11, 4 February 2015

 I ran into an error

 PHP Fatal error:  Can't inherit abstract function Copyable::getCopy() (previously declared abstract in DataValues\DataValue) in /var/www/html/mw/vendor/data-values/data-values/src/DataValues/DataValue.php on line 13

 php rebuildData.php -v
reached ID 62 and recieved the error

Tried to run it again starting at id 63
Processing all IDs from 63 to last ID ...
(1) Processing ID 63 ...
(2) Processing ID 64 ...
(3) Processing ID 65 ...
(4) Processing ID 66 ...
(5) Processing ID 67 ...
(6) Processing ID 68 ...
(7) Processing ID 69 ...
(8) Processing ID 70 ...
(9) Processing ID 71 ...
(10) Processing ID 72 ...
(11) Processing ID 73 ...
(12) Processing ID 74 ...
(13) Processing ID 75 ...
(14) Processing ID 76 ...
(15) Processing ID 77 ...
PHP Fatal error:  Can't inherit abstract function Copyable::getCopy() (previously declared abstract in DataValues\DataValue) in /var/www/html/mw/vendor/data-values/data-values/src/DataValues/DataValue.php on line 13

Fatal error: Can't inherit abstract function Copyable::getCopy() (previously declared abstract in DataValues\DataValue) in /var/www/html/mw/vendor/data-values/data-values/src/DataValues/DataValue.php on line 13

**Comment by plegault3397** [comment] 2015-02-05 00:19
This just started after the update I pulled today

**Comment by mwjames** [comment] 2015-02-05 00:20
@JeroenDeDauw `Copyable::getCopy` / `DataValues/DataValue.php` ?

**Comment by mwjames** [comment] 2015-02-05 00:26
> PHP Fatal error: Can't inherit abstract function Copyable::getCopy() (previously declared abstract in DataValues\DataValue) in /var/www/html/mw/vendor/data-values/data-values/src/DataValues/DataValue.php on line 13

I can't see who is emitting this error, maybe you can try running `php rebuildData.php -v --debug` (hopefully we can see a bit more from the stack trace).

**Comment by JeroenDeDauw** [comment] 2015-02-05 01:19
I doubt its something wrong with `Copyable`. Probably some incorrect class loading or so that just breaks there because its one of the first things loaded

**Comment by plegault3397** [comment] 2015-02-05 11:07
I run it with debug and get the same error

(54) Processing ID 62 ...
PHP Fatal error:  Can't inherit abstract function Copyable::getCopy() (previously declared abstract in DataValues\DataValue) in /var/www/html/mw/vendor/data-values/data-values/src/DataValues/DataValue.php on line 13

Nothing else

**Comment by mwjames** [comment] 2015-02-05 11:17
> Nothing else

Well, not much to go one since Travis doesn't show such error. (Hopefully, you don't use SemanticBundle and have re-installed SMW over it haven't you? I also hope you don't have two vendor directories one in the MW-root and one in the SMW-root directory)

**Comment by plegault3397** [comment] 2015-02-05 11:33
I don’t use semantic bundle and have not reinstalled SMW

I enabled debugging and when connecting to the home page I see this
In the update yesterday I received a chameleon update as well.
Could this be it?

Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /var/www/html/mw/skins/chameleon/src/Components/Html.php on line 54 Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /var/www/html/mw/skins/chameleon/src/Components/Html.php on line 54


I’m going to pull back a previous version and remove chameleon from composer and try the update again.

I will let you know

**Comment by mwjames** [comment] 2015-02-05 11:40
@s7eph4n FYI, DOMDocument::saveHTML() /var/www/html/mw/skins/chameleon/src/Components/Html.php on line 54

**Comment by s7eph4n** [comment] 2015-02-05 12:04
I think it is unrelated.

The parameter for saveHTML was introduced in PHP 5.3.6

**Comment by s7eph4n** [comment] 2015-02-05 12:17
Could this be caused by some left-over extension from some pre-composer install? Or a forgotten require_once in LocalSettings?

**Comment by plegault3397** [comment] 2015-02-05 12:25
Not sure I’m rolling back to a previous version to see if the issue is still there.
I have some old extensions and they have been working.

Once I’m back up again I will test on another sandbox and get back to you.

**Comment by plegault3397** [comment] 2015-02-05 12:41
What is the latest version of PHP supported?

I’m on 5.3.3

**Comment by s7eph4n** [comment] 2015-02-05 12:44
5.5.19

**Comment by plegault3397** [comment] 2015-02-05 13:03
Does anyone know how to upgrade php on redhat?

**Comment by mwjames** [comment] 2015-02-09 21:16
I'm closing this under the assumption that it is not directly related to SMW (or the chosen install method) but feel free to re-open the issue in case of new or additional information that would allow for a more in-depth analysis.

**Closed by mwjames** 2015-02-09 21:16 UTC
Labels: bug
