### ISSUE TITLE
mw-collapsible does not show up

### ISSUE THREAD

**Issue by RinekeOostenrijk** [SemanticMediaWiki/SemanticMediaWiki#1765] opened 2016-08-10 11:08 UTC
### Setup and configuration

Product Version
- SMW version: 2.4.1
- MW version: 1.26.3 
- DB version:MySQL 5.5.50-0ubuntu0.14.04.1 

### Issue
the 'div class="mw-collapsible"' whatever text ' /div'  does not show the [collapse] button in internet explorer. There is no problem with firefox or chrome.

see: http://sandbox.semantic-mediawiki.org/wiki/Issue/collapse

If I disable enableSemantics in Localsettings it works as it should. Also if I add
`$wgResourceLoaderDebug  = true;`
at the end of my "LocalSettings.php" produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:
```
no outputs
```

**Comment by kghbln** [comment] 2016-08-10 13:29
Thanks for reporting.

**Comment by mwjames** [comment] 2016-08-10 13:50
> There is no problem with firefox or chrome.

SMW does not distinguish between browsers nor does it discriminate against ceratin browser types. If it doesn't work with the "internet explorer" then I'm guessing some JS maybe at fault but since " firefox or chrome" works just fine and I personally don't use (nor have I installed) the internet explorer I'd therefore categorize this as a non-SMW issue (unless someone finds the cause).

**Comment by kghbln** [comment] 2016-08-10 14:24
> I'm guessing some JS maybe at fault

Probably right. For the record: I just tested this on Edge and Opera and these two do not work either.

**Comment by mwjames** [comment] 2016-08-11 15:43
>  I just tested this on Edge and Opera and these two do not work either.

As mentioned above, personally I'm incapacitated to use "internet explorer" therefore I would expect users reporting the issue to provide more information such as console output, logs etc. to avoid a situation where this issue is rotting away due to insufficient information. I'm aiming at closing this issue within a week unless evidentiary data is presented that shows it to be an SMW related issue.

**Comment by kghbln** [comment] 2016-08-11 15:49
I was just by accident that I had my Windows VM running. It was just a note on what is working or not. Did not look deep as you realised.

**Comment by mwjames** [comment] 2016-08-11 15:52
>  It was just a note on what is working or not. Did not look deep as you realised.

I'm not blaming anyone, I just want to see things move forward and not having to squash issues in half a year or so due to insufficient information.

**Comment by mwjames** [comment] 2016-08-24 04:46
> I'm aiming at closing this issue within a week unless evidentiary data is presented that shows it to be an SMW related issue.

Closing this now.

> I would expect users reporting the issue to provide more information such as console output, logs etc. to avoid a situation where this issue is rotting away due to insufficient information.

Feel free to reopen this issue in case new information are available to make this a reproducible use case where actionable items can be deducted based on the information provided.

**Closed by mwjames** 2016-08-24 04:46 UTC
Labels: bug
