### ISSUE TITLE
Failed to open dir: No such file or directory (textcat lib)

### ISSUE THREAD

**Issue by jaideraf** [SemanticMediaWiki/SemanticMediaWiki#4599] opened 2020-02-26 14:25 UTC
### Setup and configuration

- SMW version: 3.2.0-alpha
- MW version: 1.33.2
- PHP version: 7.3.14
- MySQL version: 5.6.46-86.2

### Issue
When running `rebuildFulltextSearchTable.php` with `$smwgFulltextLanguageDetection` setting
```php
$smwgFulltextLanguageDetection = [
	'TextCatLanguageDetector' => [ 'pt', 'en', 'es' ]
];
```
the following error appears. It seems caused by something looking for `/textcat/src/LM` but, `LM` directory is not in the `src` directory, it is in `textcat` directory.

### Stack trace
```
UnexpectedValueException from line 173 of /w/vendor/wikimedia/textcat/src/TextCat.php: 
DirectoryIterator::__construct(/w/vendor/wikimedia/textcat/src/LM): 
failed to open dir: No such file or directory
Backtrace:
#0 /w/vendor/wikimedia/textcat/src/TextCat.php(173): DirectoryIterator->__construct(string)
#1 /w/vendor/onoi/tesa/src/LanguageDetector/TextCatLanguageDetector.php(36): TextCat->__construct()
#2 /w/vendor/onoi/tesa/src/SanitizerFactory.php(134): Onoi\Tesa\LanguageDetector\TextCatLanguageDetector->__construct()
#3 /w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/TextSanitizer.php(160): Onoi\Tesa\SanitizerFactory->newTextCatLanguageDetector()
#4 /w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/TextSanitizer.php(112): SMW\SQLStore\QueryEngine\Fulltext\TextSanitizer->predictLanguage(string)
#5 /w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableUpdater.php(154): SMW\SQLStore\QueryEngine\Fulltext\TextSanitizer->sanitize(string)
#6 /w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php(362): SMW\SQLStore\QueryEngine\Fulltext\SearchTableUpdater->update(string, string, string)
#7 /w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php(319): SMW\SQLStore\QueryEngine\Fulltext\SearchTableRebuilder->doRebuildFromRows(SMW\SQLStore\QueryEngine\Fulltext\SearchTable, string, string, Wikimedia\Rdbms\ResultWrapper)
#8 /w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php(240): SMW\SQLStore\QueryEngine\Fulltext\SearchTableRebuilder->doRebuildByPropertyTable(SMW\SQLStore\PropertyTableDefinition)
#9 /w/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/Fulltext/SearchTableRebuilder.php(124): SMW\SQLStore\QueryEngine\Fulltext\SearchTableRebuilder->doRebuild()
#10 /w/extensions/SemanticMediaWiki/maintenance/rebuildFulltextSearchTable.php(161): SMW\SQLStore\QueryEngine\Fulltext\SearchTableRebuilder->rebuild()
#11 /w/maintenance/doMaintenance.php(96): SMW\Maintenance\RebuildFulltextSearchTable->execute()
#12 /w/extensions/SemanticMediaWiki/maintenance/rebuildFulltextSearchTable.php(252): require_once(string)
#13 {main}
```

### Steps to reproduce
Run `rebuildFulltextSearchTable.php` with `$smwgFulltextLanguageDetection` setting.

**Comment by kghbln** [comment] 2020-02-26 16:16
`$smwgFulltextLanguageDetection` is probably the reason why I never detected this on smw.o

**Comment by mwjames** [comment] 2020-02-29 02:43
> UnexpectedValueException from line 173 of /w/vendor/wikimedia/textcat/src/TextCat.php: 
DirectoryIterator::__construct(/w/vendor/wikimedia/textcat/src/LM): 
failed to open dir: No such file or directory
Backtrace:

As seen in the stack trace (which is why it is important to attach one in a ticket!) that this is caused by `TextCat.php` which isn't part of SMW.  It is maintained by WMF and the issue has been apparently fixed with https://github.com/wikimedia/textcat/commit/723ba510527a50b946e1f06a45ffe3203ae9a24c (Oct 21, 2019) but the last release was (on Feb 12, 2019 1.3.0) so those changes are not available hence the library remains broken.

You should request a release from the maintainer.

> $smwgFulltextLanguageDetection = [
	'TextCatLanguageDetector' => [ 'pt', 'en', 'es' ]
];

To be honest, I have no idea how good the `TextCatLanguageDetector` (using above metioned textcat library) is and whether this makes a difference or not in terms of the generated full-text.

**Closed by mwjames** 2020-02-29 02:43 UTC
Labels: bug

**Comment by jaideraf** [comment] 2020-03-03 13:55
Thanks a lot @mwjames!

> To be honest, I have no idea how good the TextCatLanguageDetector (using above metioned textcat library) is and whether this makes a difference or not in terms of the generated full-text.

Me neither, I was just about to test this feature when I encountered this bug. I will test it in an other occasion.
