### ISSUE TITLE
Use SMW with PHP 7

### ISSUE THREAD

**Issue by jongfeli** [SemanticMediaWiki/SemanticMediaWiki#1142] opened 2015-09-07 13:34 UTC
This is a question. Since the beta versions of **PHP 7** I have a copy of our wiki running on a web server that runs on PHP 7, this is for testing and speed comparison. The beta versions where "buggy" but with **RC1** & recently **RC2** things seem to run "smoothly", besides some **deprecated** messages from some extensions, not SMW. The performance increase under windows is almost irresistible, with the lack of **HHVM** support :). 

Nothing is what it seems so my question is does **SMW** need any changes to its code before it can reliably run "on" **PHP 7**? Is there anything automatically tested yet against PHP 7? Thanks.

**Comment by mwjames** [comment] 2015-09-07 13:41
> Nothing is what it seems so my question is does SMW need any changes to its code before it can reliably run "on" PHP 7? Is there anything automatically tested yet against PHP 7? Thanks.

Currently we cannot run tests against PHP 7 because MW has an open issue  [0] / (the trial run was made on SMT but it would be the same for SMW) not yet resolved and until then we can't give any sufficient answer about the coverage or it's reliability.

[0] https://phabricator.wikimedia.org/T107933

**Comment by JeroenDeDauw** [comment] 2015-09-07 16:22
Yeah - you're more likely to get issues from MW than from SMW. I had a look at php7 issues in SMW a few months ago and think I was able to fix them all.

**Comment by mwjames** [comment] 2015-09-23 22:51
@jongfeli Can you run `composer phpunit` [0] against the latest SMW / MW master on your PHP 7 as [1] got resolved. I'm currently a bit reluctant to add another Travis job just for the sake of PHP 7.

Some feedback would be nice to see whether tests run through or not.

PS: We know that two tests on master will fail because some eloquent developers on the WMF side thought its funny to create work for volunteer extension developers (its the second time after 1.25 that the API tests are broken, I'm really sick and tired of this). 

```
MediaWiki: 1.26alpha (Extension vendor autoloader)
Semantic MediaWiki: 2.3 alpha (SMWSQLStore3, sqlite)

1) SMW\Tests\MediaWiki\Api\AskArgsTest::testExecuteOnStore with data set #0 (array('[[Modification date::+]]', null, null), array(true))
Use of ApiResult::getIsRawMode was deprecated in MediaWiki 1.25. [Called from SMW\MediaWiki\Api\Query::addQueryResult in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Api/Query.php at line 73]
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests#running-tests
[1] https://phabricator.wikimedia.org/T107933

**Comment by jongfeli** [comment] 2015-09-24 19:25
Ok. I will have a go at it tomorrow morning when time permits. Thanks for the info @mwjames.

P.S. what do you mean with WMF? I know WMF makes very nice, and sharp [forged](http://www.wmf.com/de/messer-helfer/messer/kollektionen.html) kitchen knives, German quality. But my guess is that WMF has nothing to do with MediaWiki ;)

**Comment by mwjames** [comment] 2015-09-24 19:35
>  what do you mean with WMF? I know WMF makes very nice, and sharp forged kitchen knives, German quality. But my guess is that WMF has nothing to do with MediaWiki ;)

It refers to https://en.wikipedia.org/wiki/Wikimedia_Foundation also known as WMF.

**Comment by JeroenDeDauw** [comment] 2015-09-24 19:39
Those damned kitchen knives makers. Always breaking PHP7 compat!

**Comment by JeroenDeDauw** [comment] 2015-09-24 19:43
> Use of ApiResult::getIsRawMode was deprecated in MediaWiki 1.25.

@mwjames do we have a tracking issue for this? I'm thinking that it might be nice to have a `help wanted from MW devs` tag, which we can point people to. The ones that made the breaking change (or rather deprecation) we are running into here did go through many extensions to match the changes. Since SMW is not on Gerrit, we are falling through the cracks there. Of course we'd want to be careful with how we word things on such tickets then, as otherwise they might get the impression their help is not welcome.

**Comment by mwjames** [comment] 2015-09-24 19:55
>  do we have a tracking issue for this? I'm thinking that it might be nice to have a help wanted from MW devs tag,

and then what? Nothing will happen, if non of us fixes it just remains which means tests are broken. No one will come to rescue which means that with or without a tag, with or without running on Gerrit it is just a pile of energy that ought to vanish in the realm of the WMF universe.

**Comment by mwjames** [comment] 2015-09-24 19:57
Let's focus on the issue at hand which is PHP 7.

**Comment by jongfeli** [comment] 2015-09-25 05:44
Ok, that went smooth but the tests fail before they can finish, there seems to be a [bug](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/ByJsonScript/ParserTestCaseProcessor.php#L62) in the code that handles the tests. If any more info is needed please ask.

```
PS C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki> composer phpunit --no-dev
> php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist
PHPUnit already present

MediaWiki: 1.26alpha (Extension vendor autoloader)
Semantic MediaWiki: 2.3 alpha (SMWSQLStore3, mysql)

PHPUnit 4.8.9 by Sebastian Bergmann and contributors.

Runtime:        PHP 7.0.0RC3
Configuration:  C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\phpunit.xml.dist

............................................................   60 / 3074 (  1%)
............................................................  120 / 3074 (  3%)
............................................................  180 / 3074 (  5%)
............................................................  240 / 3074 (  7%)
............................................................  300 / 3074 (  9%)
............................................................  360 / 3074 ( 11%)
............................................................  420 / 3074 ( 13%)
............................................................  480 / 3074 ( 15%)
............................................................  540 / 3074 ( 17%)
............................................................  600 / 3074 ( 19%)
............................................................  660 / 3074 ( 21%)
............................................................  720 / 3074 ( 23%)
............................................................  780 / 3074 ( 25%)
............................................................  840 / 3074 ( 27%)
............................................................  900 / 3074 ( 29%)
............................................................  960 / 3074 ( 31%)
............................................................ 1020 / 3074 ( 33%)
............................................................ 1080 / 3074 ( 35%)
............................................................ 1140 / 3074 ( 37%)
............................................................ 1200 / 3074 ( 39%)
............................................................ 1260 / 3074 ( 40%)
............................................................ 1320 / 3074 ( 42%)
..................F...................................F..... 1380 / 3074 ( 44%)
............................................................ 1440 / 3074 ( 46%)
............................................................ 1500 / 3074 ( 48%)
............................................................ 1560 / 3074 ( 50%)
............................................................ 1620 / 3074 ( 52%)
............................................................ 1680 / 3074 ( 54%)
............................................................ 1740 / 3074 ( 56%)
............................................................ 1800 / 3074 ( 58%)
............................................................ 1860 / 3074 ( 60%)
............................................................ 1920 / 3074 ( 62%)
............................................................ 1980 / 3074 ( 64%)
............................................................ 2040 / 3074 ( 66%)
............................................................ 2100 / 3074 ( 68%)
............................................................ 2160 / 3074 ( 70%)
............................................................ 2220 / 3074 ( 72%)
............................................................ 2280 / 3074 ( 74%)
............................................................ 2340 / 3074 ( 76%)
............................................................ 2400 / 3074 ( 78%)
............................................................ 2460 / 3074 ( 80%)
............................................................ 2520 / 3074 ( 81%)
.........PHP Fatal error:  'break' not in the 'loop' or 'switch' context in 
C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\ByJsonScript\ParserTestCaseProcessor.php on line 62
Script php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist handling the phpunit event returned with an error



  [RuntimeException]
  Error Output: PHP Fatal error:  'break' not in the 'loop' or 'switch' context in C:\Apache\htdocs\mediawiki\extensi
  ons\SemanticMediaWiki\tests\phpunit\Integration\ByJsonScript\ParserTestCaseProcessor.php on line 62



phpunit [--dev] [--no-dev] [args1] ... [argsN]
```

**Comment by mwjames** [comment] 2015-09-25 05:54
>PHP Fatal error:  'break' not in the 'loop' or 'switch' context in 
C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\ByJsonScript\ParserTestCaseProcessor.php on line 62
Script php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist handling the phpunit event returned with an error

Fixed with 6d1ad9ae0a. Lets hope for the next one.

**Comment by mwjames** [comment] 2015-09-25 05:58
PHP is more strict about such constructs which why it wasn't noticed before.

**Comment by jongfeli** [comment] 2015-09-25 06:22
Ok, that worked, it finished with 2 failures and 11 skipped tests. It skipped those also when testing against PHP 5.6.11
```
PS C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki> composer phpunit
> php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist
PHPUnit already present

MediaWiki: 1.26alpha (Extension vendor autoloader)
Semantic MediaWiki: 2.3 alpha (SMWSQLStore3, mysql)

PHPUnit 4.8.9 by Sebastian Bergmann and contributors.

Runtime:        PHP 7.0.0RC3
Configuration:  C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\phpunit.xml.dist

............................................................   60 / 3074 (  1%)
............................................................  120 / 3074 (  3%)
............................................................  180 / 3074 (  5%)
............................................................  240 / 3074 (  7%)
............................................................  300 / 3074 (  9%)
............................................................  360 / 3074 ( 11%)
............................................................  420 / 3074 ( 13%)
............................................................  480 / 3074 ( 15%)
............................................................  540 / 3074 ( 17%)
............................................................  600 / 3074 ( 19%)
............................................................  660 / 3074 ( 21%)
............................................................  720 / 3074 ( 23%)
............................................................  780 / 3074 ( 25%)
............................................................  840 / 3074 ( 27%)
............................................................  900 / 3074 ( 29%)
............................................................  960 / 3074 ( 31%)
............................................................ 1020 / 3074 ( 33%)
............................................................ 1080 / 3074 ( 35%)
............................................................ 1140 / 3074 ( 37%)
............................................................ 1200 / 3074 ( 39%)
............................................................ 1260 / 3074 ( 40%)
............................................................ 1320 / 3074 ( 42%)
..................F...................................F..... 1380 / 3074 ( 44%)
............................................................ 1440 / 3074 ( 46%)
............................................................ 1500 / 3074 ( 48%)
............................................................ 1560 / 3074 ( 50%)
............................................................ 1620 / 3074 ( 52%)
............................................................ 1680 / 3074 ( 54%)
............................................................ 1740 / 3074 ( 56%)
............................................................ 1800 / 3074 ( 58%)
............................................................ 1860 / 3074 ( 60%)
............................................................ 1920 / 3074 ( 62%)
............................................................ 1980 / 3074 ( 64%)
............................................................ 2040 / 3074 ( 66%)
............................................................ 2100 / 3074 ( 68%)
............................................................ 2160 / 3074 ( 70%)
............................................................ 2220 / 3074 ( 72%)
............................................................ 2280 / 3074 ( 74%)
............................................................ 2340 / 3074 ( 76%)
............................................................ 2400 / 3074 ( 78%)
............................................................ 2460 / 3074 ( 80%)
............................................................ 2520 / 3074 ( 81%)
............................................................ 2580 / 3074 ( 83%)
............................................................ 2640 / 3074 ( 85%)
...........S................................................ 2700 / 3074 ( 87%)
..SSSSSSS..............................................
SMW\Tests\Integration\MediaWiki\Import\Maintenance\RebuildDataMaintenanceTest testRebuildData ran for 15.009 seconds
..... 2760 / 3074 ( 89%)
............................................................ 2820 / 3074 ( 91%)
............................................................ 2880 / 3074 ( 93%)
............................................................ 2940 / 3074 ( 95%)
.....................................................SSS.... 3000 / 3074 ( 97%)
............................................................ 3060 / 3074 ( 99%)
..............

Time: 3.09 minutes, Memory: 138.00Mb

There were 2 failures:

1) SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest::testSetIndexedTagNameException
Failed asserting that exception of type "ReflectionException" matches expected exception "InvalidArgumentException". Message was: 
"Invocation of method SMW\MediaWiki\Api\ApiQueryResultFormatter::setIndexedTagName() failed" at

#0 C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Unit\MediaWiki\Api\ApiQueryResultFormatterTest.php(49): ReflectionMethod->invoke(Object(SMW\MediaWiki\Api\ApiQueryResultFormatter), Array, NULL)
#1 [internal function]: SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest->testSetIndexedTagNameException()
#2 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestCase.php(880): ReflectionMethod->invokeArgs(Object(SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest), Array)
#3 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestCase.php(746): PHPUnit_Framework_TestCase->runTest()
#4 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestResult.php(601): PHPUnit_Framework_TestCase->runBare()
#5 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestCase.php(702): PHPUnit_Framework_TestResult->run(Object(SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest))
#6 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestSuite.php(735): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#7 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestSuite.php(735): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#8 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestSuite.php(735): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#9 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(432): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#10 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\TextUI\Command.php(148): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#11 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\TextUI\Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#12 C:\Apache\htdocs\mediawiki\tests\phpunit\phpunit.php(250): PHPUnit_TextUI_Command::main()
#13 {main}.

2) SMW\Tests\MediaWiki\Api\BrowseBySubjectTest::testExecuteForInvalidSubjectThrowsException
Failed asserting that exception of type "TypeError" matches expected exception "Exception".

--

There were 11 skipped tests:

1) SMW\Tests\Integration\MediaWiki\SearchInPageDBIntegrationTest::testSearchForGeographicCoordinateValueAsTerm
Requires 'Geographic coordinate' to be a supported data type (see Semantic Maps)

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\MediaWiki\SearchInPageDBIntegrationTest.php:62
C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\MwDBaseUnitTestCase.php:111

2) SMW\Tests\Integration\SPARQLStore\QueryResultLookupWithoutBaseStoreIntegrationTest::testQuerySubjects_afterUpdatingSemanticData
Requires a SPARQLStore instance

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\SPARQLStore\QueryResultLookupWithoutBaseStoreIntegrationTest.php:51

3) SMW\Tests\Integration\SPARQLStore\QueryResultLookupWithoutBaseStoreIntegrationTest::testQueryZeroResults_afterSubjectRemoval
Requires a SPARQLStore instance

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\SPARQLStore\QueryResultLookupWithoutBaseStoreIntegrationTest.php:51

4) SMW\Tests\Integration\SPARQLStore\QueryResultLookupWithoutBaseStoreIntegrationTest::testQuerySubjects_onNamspaceRestrictedCondition
Requires a SPARQLStore instance

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\SPARQLStore\QueryResultLookupWithoutBaseStoreIntegrationTest.php:51

5) SMW\Tests\Integration\SPARQLStore\QueryResultLookupWithoutBaseStoreIntegrationTest::testQuerySubobjects_afterUpdatingWithEmptyContainerAllAssociatedEntitiesGetRemovedFromGraph
Requires a SPARQLStore instance

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\SPARQLStore\QueryResultLookupWithoutBaseStoreIntegrationTest.php:51

6) SMW\Tests\Integration\SPARQLStore\RedirectLookupIntegrationTest::testRedirectTragetLookupForNonExistingEntry with data set #0 (SMW\Exporter\Element\ExpNsResource Object (...))
Requires a SPARQLStore instance

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\SPARQLStore\RedirectLookupIntegrationTest.php:38

7) SMW\Tests\Integration\SPARQLStore\RedirectLookupIntegrationTest::testRedirectTragetLookupForNonExistingEntry with data set #1 (SMW\Exporter\Element\ExpNsResource Object (...))
Requires a SPARQLStore instance

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\SPARQLStore\RedirectLookupIntegrationTest.php:38

8) SMW\Tests\Integration\SPARQLStore\RedirectLookupIntegrationTest::testRedirectTragetLookupForExistingEntryRequires a SPARQLStore instance

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\SPARQLStore\RedirectLookupIntegrationTest.php:38

9) SMW\Tests\System\InstallationGlobalsProviderIntegrityTest::testNamespaceSettingOnExampleIfSetSkip test due to missing http://example.org/id/ setting

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\InstallationConfigurationIntegrityTest.php:60

10) SMW\Tests\System\InstallationGlobalsProviderIntegrityTest::testNamespacesWithSemanticLinksOnTravisCustomNamespace with data set 
#0 ('GLOBALS', array(true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, true, false, true, false))
Test can only be executed with a specified NS_TRAVIS

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\InstallationConfigurationIntegrityTest.php:75

11) SMW\Tests\System\InstallationGlobalsProviderIntegrityTest::testNamespacesWithSemanticLinksOnTravisCustomNamespace with data set 
#1 ('Settings', array(true, false, true, false, true, false, true, false, true, false, true, false, true, false, false, false, false, false, true, false, true, false))
Test can only be executed with a specified NS_TRAVIS

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\InstallationConfigurationIntegrityTest.php:75

FAILURES!
Tests: 3074, Assertions: 9055, Failures: 2, Skipped: 11.
Script php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist handling the phpunit event returned with an error



  [RuntimeException]
  Error Output:



phpunit [--dev] [--no-dev] [args1] ... [argsN]
```

**Comment by mwjames** [comment] 2015-09-25 06:38
> Tests: 3074, Assertions: 9055, Failures: 2, Skipped: 11.

Nicely done.

>  it finished with 2 failures and 11 skipped tests

```
1) SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest::testSetIndexedTagNameException
Failed asserting that exception of type "ReflectionException" matches expected exception "InvalidArgumentException". Message was: 
"Invocation of method SMW\MediaWiki\Api\ApiQueryResultFormatter::setIndexedTagName() failed" at
```
```
2) SMW\Tests\MediaWiki\Api\BrowseBySubjectTest::testExecuteForInvalidSubjectThrowsException
Failed asserting that exception of type "TypeError" matches expected exception "Exception".
```
Above are related to the API (again) but there are actually new with PHP 7 (and don't appear in [0]).

The earlier mentioned (and therefore not yet accounted for) API errors are caused by a more strict test  environment setting [1].

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/82095263

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/travis/update-configuration-settings.sh#L69-L76

**Comment by jongfeli** [comment] 2015-09-25 10:34
Just to make sure I did the test again against "fresh" master code. There are 7 errors, all API related.

```
There were 7 failures:

1) SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest::testSetIndexedTagNameException
Failed asserting that exception of type "ReflectionException" matches expected exception "InvalidArgumentException". Message was: "Invocation of metho
d SMW\MediaWiki\Api\ApiQueryResultFormatter::setIndexedTagName() failed" at
#0 C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Unit\MediaWiki\Api\ApiQueryResultFormatterTest.php(49): ReflectionMethod->inv
oke(Object(SMW\MediaWiki\Api\ApiQueryResultFormatter), Array, NULL)
#1 [internal function]: SMW\Tests\MediaWiki\Api\ApiQueryResultFormatterTest->testSetIndexedTagNameException()
#2 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestCase.php(880): ReflectionMethod->invokeArgs(Object(SMW\Tests\MediaWiki\Api\ApiQ
ueryResultFormatterTest), Array)
#3 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestCase.php(746): PHPUnit_Framework_TestCase->runTest()
#4 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestResult.php(601): PHPUnit_Framework_TestCase->runBare()
#5 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestCase.php(702): PHPUnit_Framework_TestResult->run(Object(SMW\Tests\MediaWiki\Api
\ApiQueryResultFormatterTest))
#6 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestSuite.php(735): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestRe
sult))
#7 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestSuite.php(735): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestR
esult))
#8 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\Framework\TestSuite.php(735): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestR
esult))
#9 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(432): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestRes
ult))
#10 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\TextUI\Command.php(148): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite
), Array)
#11 C:\Apache\htdocs\mediawiki\vendor\phpunit\phpunit\src\TextUI\Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#12 C:\Apache\htdocs\mediawiki\tests\phpunit\phpunit.php(260): PHPUnit_TextUI_Command::main()
#13 {main}.

2) SMW\Tests\MediaWiki\Api\AskArgsTest::testExecuteOnStore with data set #3 (array('Modification date::+', null, null), array(array('', '_wpg', 2, fal
se)))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (...)
+    '_element' => 'printrequest'
 )

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Unit\MediaWiki\Api\AskArgsTest.php:70

3) SMW\Tests\MediaWiki\Api\AskArgsTest::testExecuteOnStore with data set #4 (array('Modification date::+', 'Modification date', null), array(array('',
 '_wpg', 2, false), array('Modification date', '_dat', 1, '')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (...)
     1 => Array (...)
+    '_element' => 'printrequest'
 )

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Unit\MediaWiki\Api\AskArgsTest.php:70

4) SMW\Tests\MediaWiki\Api\AskArgsTest::testExecuteOnStore with data set #5 (array('Modification date::+', 'Modification date', 'limit=1'), array(arra
y('', '_wpg', 2, false), array('Modification date', '_dat', 1, '')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (...)
     1 => Array (...)
+    '_element' => 'printrequest'
 )

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Unit\MediaWiki\Api\AskArgsTest.php:70

5) SMW\Tests\MediaWiki\Api\AskArgsTest::testExecuteOnMockStore
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'query-continue-offset' => 10
     'query' => Array (
         'results' => Array (
-            'Foo' => Array (...)
+            0 => Array (...)
+            '_element' => 'subject'
         )
         'printrequests' => Array (
             0 => 'Bar'
+            '_element' => 'printrequest'
         )
         'meta' => Array (
             'count' => 5
             'offset' => 5
+            '_element' => 'meta'
         )
     )
 )

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Unit\MediaWiki\Api\AskArgsTest.php:119

6) SMW\Tests\MediaWiki\Api\AskTest::testExecute with data set #0 (array('[[Modification date::+]]', '?Modification date', 'limit=10'), array(array('',
 '_wpg', 2, false), array('Modification date', '_dat', 1, '')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (...)
     1 => Array (...)
+    '_element' => 'printrequest'
 )

C:\Apache\htdocs\mediawiki\extensions\SemanticMediaWiki\tests\phpunit\Unit\MediaWiki\Api\AskTest.php:55

7) SMW\Tests\MediaWiki\Api\BrowseBySubjectTest::testExecuteForInvalidSubjectThrowsException
Failed asserting that exception of type "TypeError" matches expected exception "Exception".
```

**Comment by mwjames** [comment] 2015-09-26 13:42
> Just to make sure I did the test again against "fresh" master code. There are 7 errors, all API related.

Thanks, as expected those were the once to fail though but it should not diminish production capability and to be frank as of now I have no intention to fix them (we didn't break them).

**Comment by mwjames** [comment] 2015-11-27 06:13
>  There are 7 errors, all API related.

Once again, the API has been fixed for master and is running smooth (1.27/HHVM) therefore I'm inclined to close this issue for the moment. If there are some actionable tasks in connection with PHP 7 unresolved please feel free to re-open this issue.

**Closed by mwjames** 2015-11-27 06:13 UTC
Labels: question

**Comment by alex-mashin** [comment] 2017-09-19 04:22
News: http://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html.
It seems that HHVM is going to diverge from PHP, and the only actively maintained version of PHP is to be 7.1; so supporting PHP 7.1 remains th only choice.

**Comment by mwjames** [comment] 2017-09-23 01:07
> It seems that HHVM is going to diverge from PHP

As for the continuing support of HHVM, please see comments in #2688.

**Comment by JeroenDeDauw** [comment] 2017-09-23 03:55
Also, SMW already supports PHP 7 :)
