### ISSUE TITLE
No link to Special:Browse in the toolbox with MW 1.35

### ISSUE THREAD

**Issue by jewloszewicz** [SemanticMediaWiki/SemanticMediaWiki#4867] opened 2020-10-22 11:19 UTC
### Setup

- SMW version: 3.2.0
- MW version: 1.35.0
- PHP version: 7.4.11

### Issue
There is no link to the Special:Browse in the sidebar.
It could be related to the hook deprecation as mentioned on the page linked below.

https://www.mediawiki.org/wiki/Manual:Hooks/BaseTemplateToolbox

### Steps to reproduce

1) Open any page that should have the link in the toolbox.
2) The link is not there.
3) Special:Browse works when added manually to the url.

**Comment by octfx** [comment] 2020-10-22 13:38
Is this fixed / related by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4856?

**Comment by kghbln** [comment] 2020-10-22 14:50
Thanks for reporting. Duplicate of #4831 and and #4866

**Closed by kghbln** 2020-10-22 14:50 UTC
Labels: bug
