### ISSUE TITLE
Parameter 3 to SMW\\MediaWiki\\Hooks\\HookRegistry::__invoke() expected to be a reference, value given

### ISSUE THREAD

**Issue by nemobis** [SemanticMediaWiki/SemanticMediaWiki#1376] opened 2016-01-16 11:10 UTC
Bug spanning multiple versions:

```
21.45 -rakkaus:#mediawiki-i18n- (3 lines skipped) [Sun Dec  6 20:46:34 2015] [hphp] [10318:7f360a7ff700:281639:000004] [] \nWarning: Parameter
          3 to SMW\\MediaWiki\\Hooks\\HookRegistry::__invoke() expected to be a reference, value given in
          /srv/mediawiki/tags/2015-12-05_11:27:55/includes/Hooks.php on line 195
14.26 -rakkaus:#mediawiki-i18n- [Sat Dec 19 14:27:46 2015] [hphp] [10318:7f35cc3ff700:363898:000001] [] \nWarning: Parameter 3 to
          SMW\\MediaWiki\\Hooks\\HookRegistry::__invoke() expected to be a reference, value given in
          /srv/mediawiki/tags/2015-12-18_17:18:01/includes/Hooks.php on line 195
10.53 -rakkaus:#mediawiki-i18n- [Sat Jan 16 10:54:33 2016] [hphp] [10318:7f35e8fff700:515749:000001] [] \nWarning: Parameter 3 to
          SMW\\MediaWiki\\Hooks\\HookRegistry::__invoke() expected to be a reference, value given in
          /srv/mediawiki/tags/2016-01-14_14:04:07/includes/Hooks.php on line 195
```

**Comment by mwjames** [comment] 2016-01-16 11:41
Well, I'm guessing this is 1.27 master (above is missing version information for both MW and SMW [0]).

[0] " has invalid call signature; Parameter 3 to SMW\MediaWiki\Hooks\HookRegistry" appeared after a certain patch was merged in 1.27 and was reported two moths ago.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/CONTRIBUTING.md#report-bugs
[1] https://phabricator.wikimedia.org/T118683

**Comment by Nikerabbit** [comment] 2016-02-25 20:40
Why do you require reference when you only need value? This hook is called only from one place in core, and there the third param is passed as reference.

It could also be a bug in HHVM. I don't know what "SMW\\MediaWiki\\Hooks\\HookRegistry::__invoke()" refers to as there is no such function defined anywhere.

**Comment by mwjames** [comment] 2016-02-26 00:30
> Why do you require reference when you only need value? This hook is called only from one place in core, and there the third param is passed as reference.

As I explained in the referenced thread, the code and the hook definition didn't change and seems to appear only after a particular change in 1.27 (`$dbw->onTransactionIdle( function () use ( $params, $dbw ) { ...}`).

A side from that we haven't introduced anything or changed the handler, the hook is defined [0] with a signature of:

```
Hooks::run(
			'TitleMoveComplete',
			array( &$this->oldTitle, &$this->newTitle, &$user, $pageid, $redirid, $reason )
		);
```

The callback handler mirrors the signature (which has been in this form at least since SMW 1.9 [1]).

```
$this->handlers['TitleMoveComplete'] = function ( &$oldTitle, &$newTitle, &$user, $oldId, $newId ) {
}
```

[0] https://github.com/wikimedia/mediawiki/blob/REL1_26/includes/MovePage.php#L374-L377
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/1.9.2/includes/Setup.php#L373-L374

**Comment by Nikerabbit** [comment] 2016-02-26 06:54
I added some comments to the Phabricator task you filed. You are on the right track that the introduction of onTransactionIdle is the trigger. Just need to figure out the cause.

**Comment by mwjames** [comment] 2016-04-08 13:35
This issue is not resolved as I'm still able to reproduce it using Zend not HHVM, yet the WMF has decided to close T118683 without explanation or appropriate response in clarifying the issue for Zend users.

```
MediaWiki 1.27.0-alpha (b8572194), PHP 5.6.8 (apache2handler), MySQL 5.6.24

Parameter 3 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in <b>D:\xampp\htdocs\mw-core-2\includes\Hooks.php</b> on line <b>195</b>
```

Given the limit capacity of volunteer time and the incapacity of WMF employees to appropriately respond to the issue (being reported 5 month ago), I'm unable to assign an actionable task or to further monitor the issue beyond reporting that it is still unresolved.

Feel free to reopen the task, if it is clear how to address the issue.

**Closed by mwjames** 2016-04-08 13:35 UTC

**Comment by Nikerabbit** [comment] 2016-04-08 14:51
If you do not need to alter the value that is passed, just removing the reference would work around the issue – to my knowledge it is always safe to drop the reference on the hook function parameter list if it is not needed.

Given the issue is (again to my knowledge) in the PHP and HHVM, there is no proper fix but only workarounds until fixed versions of those software are released.

**Comment by mwjames** [comment] 2016-04-08 15:12
> If you do not need to alter the value that is passed, just removing the reference would work around the issue

So, we give the WMF some leeway because they introduce `onTransactionIdle...` without testing it appropriately and now we have fix the issue retroactively.

I really don't like this, having to spent my time on issues caused by paid WMF employees.

**Comment by mwjames** [comment] 2016-04-08 15:18
> If you do not need to alter the value that is passed, just removing the reference would work around the issue

I haven't tested this, https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1501.
