### ISSUE TITLE
Fatal error during SMW 2.3.1 or 2.4 (dev-master 77bd7bd) update job in MW 1.26.2

### ISSUE THREAD

**Issue by lloonngg** [SemanticMediaWiki/SemanticMediaWiki#1537] opened 2016-04-29 02:47 UTC
### Setup and configuration

- SMW version:  2.3.1 or 2.4 (dev-master 77bd7bd)
- MW version: 1.26.2
- DB (MySQL etc.): 10.0.20-MariaDB-1~trusty-log
- HHVM 3.7.3 (srv)

### Issue
I was previously running a private wiki based on the development branch of MW1.26 along with SMW 2.2.1 and the above MariaDB and HHVM setup.  Things seem to be fine.  After upgrading to MW1.26.2 and SMW 2.3.1 or 2.4 (dev-master 77bd7bd), I was able to run update.php successfully.  I started repairing and updating the SMW data and then launched runJobs to get the process moving along.  Whenever SMW\UpdateJob hits a Property, it complains of this error:  

Fatal error: Class undefined: SMW\PropertyAnnotator\SortkeyPropertyAnnotator in /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/PropertyAnnotatorFactory.php on line 83

I tried disabling all my extensions other than SMW and also commenting out other permission settings to no avail.

Any idea what may be going on?  Is SMW 2.3.1 fully compatible w/ MW 1.26.2?

Thanks,

Long

**Comment by mwjames** [comment] 2016-04-29 03:00
> Fatal error: Class undefined: SMW\PropertyAnnotator\SortkeyPropertyAnnotator in /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/PropertyAnnotatorFactory.php on line 83

I guessing this is caused by the name reference `Sortkey` instead of being `SortKey` in the filename which makes the autoloader go berserk because the class is name is to be `class SortKeyPropertyAnnotator ` [0].

> Any idea what may be going on? Is SMW 2.3.1 fully compatible w/ MW 1.26.2?

Just for the fun of it, @lloonngg could you try renaming the file `SortkeyPropertyAnnotator.php` to `SortKeyPropertyAnnotator.php`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.3.x/src/PropertyAnnotator/SortkeyPropertyAnnotator.php

**Comment by lloonngg** [comment] 2016-04-29 03:12
@mwjames, just tried your renaming suggestion.  No luck.  I checked my prior setup w/ SMW 2.2.1 and that same file was also named Sort**k**eyPropertyAnnotator.php.  I thought perhaps file owner/group my be at play and changed the permissions for the SMW extensions folder and content.  That did not help either.

**Comment by mwjames** [comment] 2016-04-29 03:21
Not sure how you installed SMW but maybe you need to run `composer dump-autoload` (normally the PSR-4 kicks in).

>  No luck. I checked my prior setup w/ SMW 2.2.1 and that same file was also named SortkeyPropertyAnnotator.php.

The difference is that 2.2 has `SortkeyPropertyAnnotator` (uses lower k in class name) [0] while 2.3 uses `SortKeyPropertyAnnotator` (uses upper K in class name) [1]. In 2.2 the class name matches the filename while this is not the case for 2.3 (and 2.4).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.2.x/src/Annotator/SortkeyPropertyAnnotator.php

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.3.x/src/PropertyAnnotator/SortkeyPropertyAnnotator.php

**Comment by mwjames** [comment] 2016-04-29 03:29
@lloonngg I can see `PropertyAnnotatorFactory` makes reference to `SortkeyPropertyAnnotator` [0, 1] which should instead be `SortKeyPropertyAnnotator`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/PropertyAnnotatorFactory.php#L12

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/PropertyAnnotatorFactory.php#L80

**Comment by lloonngg** [comment] 2016-04-29 03:53
Haha...I came up with that as well.  Editing lines 12 and 80 in /src/PropertyAnnotatorFactory.php as you suggested did the trick.  I was able to get through runJobs now with the latest SMW 2.4 branch.  I imagine this should also fix it in 2.3.1.  Interestingly after make the two edits, renaming /src/PropertyAnnotator/SortkeyPropertyAnnotator.php to Sort**K**eyPropertyAnnotator.php will break things again with the following error:

Warning: File not found: /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/PropertyAnnotator/SortkeyPropertyAnnotator.php in /var/www/html/mediawiki/vendor/composer/ClassLoader.php on line 412

Fatal error: Class undefined: SMW\PropertyAnnotator\SortKeyPropertyAnnotator in /var/www/html/mediawiki/extensions/SemanticMediaWiki/src/PropertyAnnotatorFactory.php on line 83

Looks like the ClassLoader expects the original SortkeyPropertyAnnotator.php filename.  Hopefully this fix can be merged into 2.3.1 and 2.4.

Thanks for you help.

Long

**Comment by mwjames** [comment] 2016-04-29 04:21
>  Interestingly after make the two edits, renaming /src/PropertyAnnotator/SortkeyPropertyAnnotator.php to SortKeyPropertyAnnotator.php will break things again with the following error:

Since I have difficulties to replicate this behavour (WINOS doesn't care for upper/lower case and our Travis Linux didn't scream either), I just merged #1538 which should hopefully untangle the mismatch in naming.

@lloonngg Would you mind trying the 2.4 master (43acf66) to see whether the issue is going away.

@JeroenDeDauw Non of the tools in place caught this which is rather annoying.

**Comment by lloonngg** [comment] 2016-04-29 04:49
Just pulled latest from master with composer and it works!  I'm on Ubuntu 14.04 LTS server if that helps.

**Comment by mwjames** [comment] 2016-05-03 07:52
> Just pulled latest from 2.4 master with composer and it works! I'm on Ubuntu 14.04 LTS server if that helps.

Thanks for testing and sorry for the trouble.

> Hopefully this fix can be merged into 2.3.1 and 2.4.

I won't do a backport (if someone wants to do this go ahead) as it is fixed with master.

**Closed by mwjames** 2016-05-03 07:52 UTC

**Comment by JeroenDeDauw** [comment] 2016-05-03 21:12
#MoreReasonsToMoveAlongWithOurNextRelease ;p
