### ISSUE TITLE
Complain from Aliases.php about SMW\QueryPrinterFactory not found

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#2237] opened 2017-02-05 19:52 UTC
### Setup and configuration

- SMW version: master
- MW version: master
- PHP version: 7
- DB (MySQL etc.): mysql

### Issue

Warnings on every page load about SMW\QPF not being found

**Comment by mwjames** [comment] 2017-02-06 03:21
Hi,

> ### Issue
>
> Warnings on every page load about SMW\QPF not being found

The issue is an outdated alias file that exists on the host system.
Please see the comment in [0].

When installed via Composer there will be no such error but if for
some reason (mixing tarball with Composer, fetching sources via git
only etc.) an outdated alias file contains a file reference as in case
of this very issue then it is necessary to run:

`composer dump-autoload` from the directory that was used to install
the software (which in most cases should be the MW base directory).

How did you install the master?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1841#issuecomment-246910724

Cheers

**Comment by kghbln** [comment] 2017-02-07 15:11
Thumbs up: https://github.com/hexmode/SemanticMediaWiki/commit/059fc242bab1a1d0cbeea4df8261257f37a3fca9#commitcomment-20765179

**Comment by mwjames** [comment] 2017-02-11 11:50
> How did you install the master?

Since no feedback was provided as to whether the suggestion worked or not, I'm closing this issue in anticipation that silence implies consent.

**Closed by mwjames** 2017-02-11 11:50 UTC
Labels: question
