### ISSUE TITLE
Validator::ParserHook is causing StripState/Invalid marker during UpdateJob::run

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [SemanticMediaWiki/SemanticMediaWiki#880] opened 2015-03-10 12:59 UTC
```
Backtrace:
#0 /home/ccccc/htdocs/w/includes/parser/StripState.php(66): StripState->addItem(string, string, string)
#1 /home/ccccc/htdocs/w/includes/parser/Parser.php(999): StripState->addGeneral(string, string)
#2 /home/ccccc/htdocs/w/extensions/Validator/src/legacy/ParserHook.php(302): Parser->insertStripItem(string, StripState)
#3 [internal function]: ParserHook->renderFunction(Parser, string, string, string, string, string)
#4 /home/ccccc/htdocs/w/extensions/Validator/src/legacy/ParserHook.php(336): call_user_func_array(array, array)
#5 /home/ccccc/htdocs/w/extensions/Validator/src/legacy/ParserHook.php(610): ParserHook->renderFunctionObj(Parser, PPFrame_DOM, array)
#6 [internal function]: ParserHookCaller->runFunctionHookObj(Parser, PPFrame_DOM, array)
#7 /home/ccccc/htdocs/w/includes/parser/Parser.php(3753): call_user_func_array(array, array)
#8 /home/ccccc/htdocs/w/includes/parser/Parser.php(3471): Parser->callParserFunction(PPFrame_DOM, string, array)
#9 /home/ccccc/htdocs/w/includes/parser/Preprocessor_DOM.php(1179): Parser->braceSubstitution(array, PPFrame_DOM)
#10 /home/ccccc/htdocs/w/includes/parser/Parser.php(3281): PPFrame_DOM->expand(PPNode_DOM, integer)
#11 /home/ccccc/htdocs/w/includes/parser/Parser.php(1239): Parser->replaceVariables(string)
#12 /home/ccccc/htdocs/w/includes/parser/Parser.php(405): Parser->internalParse(string)
#13 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/ContentParser.php(189): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#14 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/ContentParser.php(129): SMW\ContentParser->fetchFromParser()
#15 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/src/MediaWiki/Jobs/UpdateJob.php(85): SMW\ContentParser->parse()
#16 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/src/MediaWiki/Jobs/UpdateJob.php(73): SMW\MediaWiki\Jobs\UpdateJob->doPageContentParse()
#17 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/src/MediaWiki/Jobs/UpdateJob.php(52): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#18 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_SetupHandlers.php(403): SMW\MediaWiki\Jobs\UpdateJob->run()
#19 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(417): SMWSQLStore3SetupHandlers->refreshData(integer, integer, boolean, boolean)
#20 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/src/Maintenance/DataRebuilder.php(215): SMWSQLStore3->refreshData(integer, integer, boolean, boolean)
#21 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/includes/src/Maintenance/DataRebuilder.php(145): SMW\Maintenance\DataRebuilder->rebuildAll()
#22 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(115): SMW\Maintenance\DataRebuilder->rebuild()
#23 /home/ccccc/htdocs/w/maintenance/doMaintenance.php(101): SMW\Maintenance\RebuildData->execute()
#24 /home/ccccc/htdocs/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(156): require_once(string)
#25 {main}
```
This error was produced by the SMW maintenance script. I tried the following:
```
php rebuildData.php -ftpv
php rebuildData.php -v
```

**Comment by mwjames** [comment] 2015-03-10 13:08
While the stack trace is good, it doesn't really help in analyzing the issue until we know about the page content.

Any parser function within a page (from any any other extension) can cause above issue therfore it would be helpful to know what content this page is hosting to narrow down the issue.

All we know is that it is caused by `Validator/src/legacy/ParserHook.php`:

```
#0 /home/ccccc/htdocs/w/includes/parser/StripState.php(66): StripState->addItem(string, string, string)
#1 /home/ccccc/htdocs/w/includes/parser/Parser.php(999): StripState->addGeneral(string, string)
#2 /home/ccccc/htdocs/w/extensions/Validator/src/legacy/ParserHook.php(302): Parser->insertStripItem(string, StripState)
#3 [internal function]: ParserHook->renderFunction(Parser, string, string, string, string, string)
#4 /home/ccccc/htdocs/w/extensions/Validator/src/legacy/ParserHook.php(336): call_user_func_array(array, array)
#5 /home/ccccc/htdocs/w/extensions/Validator/src/legacy/ParserHook.php(610): ParserHook->renderFunctionObj(Parser, PPFrame_DOM, array)
#6 [internal function]: ParserHookCaller->runFunctionHookObj(Parser, PPFrame_DOM, array)
```

**Comment by DestructionOfPlanetJupiter** [comment] 2015-03-10 13:45
how I am able to find out which site is responsible for this error?

**Comment by mwjames** [comment] 2015-03-10 13:58
> how I am able to find out which site is responsible for this error?

Best I can think of is to use [bisection](http://en.wikipedia.org/wiki/Bisect) of an parameterized (using `-s` `-e`) `rebuildData` to determine in which part (within/outside the range) is causing the break and narrow down the possible id range. (knowing the id will allow to deduce the page from the `page` table).

**Comment by DestructionOfPlanetJupiter** [comment] 2015-03-10 14:19
OK ... this happens after a migration of a productive server to a new environment. I still have a test environment on which I will be able to test things out. I doubt though that I will be able to get it done today. After this the crash has happened:
```
(905) Processing ID 907 ...
```
I have the json output, but it does not contain much information. I used this
```
api.php?action=query&prop=info&pageids=907
```

**Comment by mwjames** [comment] 2015-03-11 19:08
I came across a similar issue that what caused by having a template with no `<includeonly></includeonly>` tags and after some digging I found [0]. If you apply [1] the issue should disappear (it is deployed with 1.25).

[0] https://phabricator.wikimedia.org/T58226
[1] https://gerrit.wikimedia.org/r/#/c/161994/1/includes/parser/Parser.php

**Comment by mwjames** [comment] 2015-10-09 18:07
Closing this for now, if it reappears again we can reopen the issue.

**Closed by mwjames** 2015-10-09 18:07 UTC
