### ISSUE TITLE
SMW_NS_TYPE alias definition causes notices

### ISSUE THREAD

**Issue by nemobis** [SemanticMediaWiki/SemanticMediaWiki#1975] opened 2016-11-01 11:19 UTC
Per https://phabricator.wikimedia.org/T148008#2712864 , namespaces 204 and 205 sometimes have aliases defined despite not being defined themselves.

I see that languages/SemanticMediaWiki.namespaces.php and languages/SMW_LanguageXx.php
 define a series of aliases and then two separate functions in languages/SMW_Language.php take care of unsetting the namespaces and their aliases depending on configuration:

```
		if ( !$smwgHistoricTypeNamespace ) {
			unset( $namespaces[SMW_NS_TYPE] );
			unset( $namespaces[SMW_NS_TYPE_TALK] );
		}
```

```
		if ( !$smwgHistoricTypeNamespace ) {
			foreach ($namespaceAliases as $alias => $namespace) {
				if ( $namespace == SMW_NS_TYPE || $namespace == SMW_NS_TYPE_TALK ) {
					unset( $namespaceAliases[$alias] );
				}
			}
		}
```

**Comment by kghbln** [comment] 2016-11-01 13:37
Any chance to get some info about your setup?

**Comment by JeroenDeDauw** [comment] 2016-11-01 14:25
Just the SMW version probably suffices in this case

**Comment by Nikerabbit** [comment] 2016-11-01 14:49
https://translatewiki.net/wiki/Special:Version

Ask me more if needed, and I'll see what I can provide.

**Comment by kghbln** [comment] 2016-11-01 15:22
For the record since "Special:Version" is kinda dynamic:
- MediaWiki 	1.29.0-alpha
- HHVM 	3.15.0 (srv)
- MariaDB 	5.5.52-MariaDB-1ubuntu0.14.04.1
- Semantic MediaWiki	2.4.1

**Comment by mwjames** [comment] 2016-11-05 01:22
> For the record since "Special:Version" is kinda dynamic:

Thanks and with that information being present, I'm now able to respond to the issue.

> I see that languages/SemanticMediaWiki.namespaces.php and languages/SMW_LanguageXx.php
define a series of aliases and then two separate functions in languages/SMW_Language.php

Since the problem was not present in any previous release, I suspect #1693 to be related therefore my suggestion is to revert the suspected PR on the 2.4.x branch which may (== untested and I won't have time for attending/testing it) solve the issue and could be added to a possible #1751 release.

Furthermore, those mentioned files no longer exist in master (2.5+, #1929) hence should not cause an issue for when `smwgHistoricTypeNamespace` isn't set.

**Comment by nemobis** [comment] 2016-11-17 12:41
This notice is very spammy and has been dominating our logs for this month, so any workaround or emergency solution would be welcome.

**Comment by mwjames** [comment] 2016-11-19 02:15
>  so any workaround or emergency solution would be welcome.

I suspect someone read my comment and tried the suggestion by reverting the mentioned three lines of code (in the linked PR).

> is to revert the suspected PR on the 2.4.x branch which may

As we received no response (on whether the suggestion would indeed resolve the issue or not) the revert didn't make it into the 2.4.2 release.

**Comment by kghbln** [comment] 2016-11-19 12:44
Preliminary setting this to SMW 2.4.3 milestone per https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1751#issuecomment-261711738.

**Comment by kghbln** [comment] 2016-11-22 16:56
@nemobis Any feedback if the revert would solve the issue?

**Comment by Nikerabbit** [comment] 2016-11-22 19:02
Would you have a commit sha I could check out? Or do I need to try to revert manually something myself?

**Comment by kghbln** [comment] 2016-11-23 16:09
I guess this is a matter of indeed manually revert https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1693 or to check out https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/c1d314f95a07a561e1bdf0b8c2c29b5186046981 which should be master just before this got merged.

**Comment by mwjames** [comment] 2016-11-26 02:27
> Would you have a commit sha I could check out?

[0] added to the 2.4.x branch.

I'm unable to confirm the issue on SMW master (I'm currently using Postgres which is broken on MW 1.28 (1923) which means until Postgres works again (== our test suite passes), I cannot provide further assistance for any other MW 1.27+ version).


[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/a022f86b85b259c50f10629974f5e5fbb678974b

**Comment by kghbln** [comment] 2016-11-26 12:50
> [0] a022f86

Cool, that makes things easier. @Nikerabbit If you could give this a testing shot ... Thanks.

**Comment by Nikerabbit** [comment] 2016-11-26 17:06
I can confirm a022f86 does not produce the notices, while the parent of it does. Also master does not produce those notices.

**Comment by kghbln** [comment] 2016-11-26 20:08
> I can confirm a022f86 does not produce the notices, while the parent of it does. Also master does not produce those notices.

Thanks a lot for the feedback! Should roll out to the public soon.

**Closed by kghbln** 2016-11-26 20:08 UTC
Labels: bug
