### ISSUE TITLE
Queries are returning the displaytitle instead of the page name when using |link=none

### ISSUE THREAD

**Issue by Fannon** [SemanticMediaWiki/SemanticMediaWiki#1617] opened 2016-05-25 15:10 UTC
### Setup and configuration

- SMW version: 2.4
- MW version: 1.25
- DB: MySQL

### Issue
It looks like SMW 2.4 ASK queries are returning the displaytitle instead of the page name when using |link=none. It should return the page title.
This was probably introduced by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1410

**Comment by mwjames** [comment] 2016-05-25 15:24
> It looks like SMW 2.4 queries are returning the displaytitle in ASK queries instead of the page name when using |link=none. It should return the page title.

[0] could not manifest this observation, are you sure about this?

http://sandbox.semantic-mediawiki.org/wiki/Issue/1617

**Comment by Fannon** [comment] 2016-05-25 15:45
This only happens when the page has a {{DISPLAYTITLE:Something}}.

**Comment by Fannon** [comment] 2016-05-25 15:47
@cicalese You might be interested in this issue

**Comment by mwjames** [comment] 2016-05-25 15:57
> This only happens when the page has a {{DISPLAYTITLE:Something}}.

If possible, please provide an example (on the sandbox), so we don't spend time second guessing each other.

**Comment by gesinn-it** [comment] 2016-05-25 16:04
I'll follow-up providing examples in the sandbox... Need to create an account first.

**Comment by Fannon** [comment] 2016-05-25 16:08
I've got no sandbox account yet, and it's blocking me for the next 50 minutes

**Comment by gesinn-it** [comment] 2016-05-25 16:29
One thing I figured out is, that there is a caching issue:
* I created the page http://sandbox.semantic-mediawiki.org/wiki/Issue/1617/b without displaytitle
* Then, in a second edit, I added displaytitle to the page above

But http://sandbox.semantic-mediawiki.org/wiki/Issue/1617 still shows the page tile (Issue/1617/b) and not the displaytitle. A null edit fixes this.

**Comment by mwjames** [comment] 2016-05-25 17:12
> Then, in a second edit, I added displaytitle to the page above

This is because of the parser cache.

- Sandbox has `$GLOBALS['smwgEnabledQueryDependencyLinksStore']` enabled which means that queries are updated when conditions of an `#ask` query are matched
- When `Issue/1617/b` was added then the query in `Issue/1617` got updated (== means the parser cache got invalidated due to a met condition of `Has page`) and a new query result was requested
- When you later added the display title without changing any existing annotation (otherwise updates are not scalable, we only act on changes) then `QueryDependencyLinksStore` will not send a new update request to `Issue/1617` because `Has page` value remained and `Display title of` is not part of any query which means that the parser cache also remained intact for `Issue/1617`
- The manual null edit (or purge) forces the parser cache to be invalidated which leads to a new request where `Issue/1617/b` is being fetched with the new display title

**Comment by Fannon** [comment] 2016-05-26 09:39
I've tried to recreate the situation in the sandbox, but I couldn't because the LocalSettings of the test instance is missing a setting, that allows to use {{DISPLAYTITLE}} to set a displaytitle other than the page title:

```
$wgRestrictDisplayTitle = false;
```

It is also possible to set the displaytitle through a semantic property, but I don't know which property is configured to be used in the Issue namespace.

**Comment by mwjames** [comment] 2016-05-26 10:05
> $wgRestrictDisplayTitle = false;

Is set as per [0, 1] on the sandbox otherwise `{{DISPLAYTITLE}}` would not work as it does.

> It is also possible to set the displaytitle through a semantic property, but I don't know which property is configured to be used in the Issue namespace.

There is no specific property set for the "Issue namespace". I'm not sure what "to set the displaytitle through a semantic property" means.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1410#issuecomment-190319807
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1410#issue-134179848
[2] http://sandbox.semantic-mediawiki.org/wiki/Attribut:Display_title_of

**Comment by mwjames** [comment] 2016-05-26 10:26
> instance is missing a setting, that allows to use {{DISPLAYTITLE}} to set a displaytitle other than the page title:

To avoid possible misunderstandings about required settings, [0] now has a section that clarifies the expectation.

[0] https://www.semantic-mediawiki.org/wiki/Help:Special_property_Display_title_of

**Comment by Fannon** [comment] 2016-05-26 10:31
Thanks for the writeup, that makes it very clear.

I could not reproduce the problem on the sandbox, though. Maybe its an issue with our concrete setup. I'll be able to check that on Monday.

Thanks for your time!

**Comment by Fannon** [comment] 2016-05-30 12:38
@mwjames Is there a way to disable the display title cache, SMW is using?

**Comment by mwjames** [comment] 2016-05-30 13:03
> We've disabled caches in general, but the display titles are still cached (and outdated)

This seems like a very bad idea. SMW in general expects the CACHE [0] to be enabled (e.g. without cache a page purge will not function as it relies on an intermediary storage since it runs in a different transaction).

DTITLE uses the [0] setting and if it is not available it makes a live request [1, 2]. Using Display title without a cache is not a core setting that is recommended as it forces each page object to make a Store request. If you don't use a cache, I'd suggest you disable DTITLE as described in [3].

The cache object always gets evicted when on object changes its state (so having outdated cache seems unlikely). If you enable logging you can see messages for the when the cache gets evicted.

```
$wgDebugLogGroups  = array(
 'smw' => myLocaton/debug-smw-{$wgDBname}.log"
);

```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.settings.php#L574
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/datavalues/SMW_DV_WikiPage.php#L653-L656
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/CachedPropertyValuesPrefetcher.php#L72-L88
[3] https://www.semantic-mediawiki.org/wiki/Help:Special_property_Display_title_of

**Comment by Fannon** [comment] 2016-05-30 13:34
Hello!

Thanks for the explanation! We've enabled the cache now, but still have issues with outdated display titles.

It looks like that a null edit, an ?action=purge or a job item (recentChangesUpdate Special:RecentChanges type=cacheUpdate (id=2727) STARTING) does not invalidate the display title cache.

The cache is only invalidated if the page content actually _changes_. If that's the case, this appears in the debug log group you suggested:
```
Clear CachedPropertyValuesPrefetcher for Test_Product_5#5038#
```
After that, the display title is correctly updated.

Is it possible to count null edits and the like as cache invalidations, too?

**Comment by mwjames** [comment] 2016-05-30 13:47
> Is it possible to count null edits and the like as cache invalidations, too?

[0] contains some context as to why a purge is only done when `InTextAnnotationParser` was involved. Having a page with only an #ask would not carry a `ContextReference` and therefore bails-out early without running an update request.

Maybe have #ask set a context reference as in \[1] (I don't remember but maybe there is a reason I didn't do this to avoid double parses when invoked by other parser functions or templates).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/ParserAfterTidy.php#L127-L168
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/InTextAnnotationParser.php#L119-L120

**Comment by mwjames** [comment] 2016-05-30 13:54
>I don't remember but maybe there is a reason I didn't do this to avoid double parses when invoked by other parser functions or templates

https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1167

**Comment by mwjames** [comment] 2016-06-02 12:35
> Is it possible to count null edits and the like as cache invalidations, too?

During the first iteration it was done on null edits but I decided against it due to performance implications since the cache should only be evicted when an actual alteration occurs and since then it only happens on events outlined in [0].

When an entity (subject, property, object) is altered then the cache is purged but a null edit normally does not entail an instance change in terms of altered facts.

Cache invalidations (those relevant for SMW) are not directly related to invalidations of the parser cache and a stalled parser cache is the cause why certain query results are not updated directly.

The `QueryDependencyLinksStore` tries to be smart about those updates and informs each potential subject involved (by simply doing `PageUpdater::doPurgeParserCache`) to request a new "raw" view (without parser cache) which eventually triggers a query request to the backend store.

> You could try acting on a Display title of add/change and lookup related queries for the entity in question and sent an update request but I don't see this as a necessary feature for core out of performance considerations.

I was a bit contemplating about this use case and decided to open a possibility to define an "affiliate" property dependency that is resolved in `EntityIdListRelevanceDetectionFilter` (#1626) which is used by the `QueryDependencyLinksStore` to trigger an update job on registered ID's.

Normally when the `Display title of` is altered an embedded query object (or more precise the subject as object value) is not directly modified which means it would not trigger an update request, now considering the possibilities of an affiliate change, `$GLOBALS['smwgQueryDependencyAffiliatePropertyDetectionlist']` can be set to watch changes that occur on affiliate properties and can trigger an update as well. It goes without saying that this relates to an enabled `$GLOBALS['smwgEnabledQueryDependencyLinksStore']`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/EventListenerRegistry.php#L66-L83

**Comment by mwjames** [comment] 2016-06-02 14:42
Given that the initial issue "displaytitle instead of the page name when using |link=none" could not be replicated to the extend that it would require a change, I'm leaning towards closing this issue.

Proposed changes as outlined above are now available at [0].

[0] http://sandbox.semantic-mediawiki.org/wiki/Issue/1626.

**Closed** 2016-06-04 12:07 UTC

**Comment by Fannon** [comment] 2016-06-07 06:04
Yes, this issue should be closed. Thanks @mwjames!
