### ISSUE TITLE
SMW Sandbox is down

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#5264] opened 2022-06-16 14:53 UTC
Nothing new, just thought it might be a good idea to document this here, in case anybody else is wondering.

Any news on getting the sandbox up and running again, @kghbln ?

**Comment by kghbln** [comment] 2022-06-16 14:59
Not yet. The holdup is converting the current Chameleon 1.x skin into Chameleon 4.x including SARS and whatever. The Chameleon releases were unfortunately made without the option of a shim. Tough titties for early Chameleon adaptors.

Duplicate of https://github.com/SemanticMediaWiki/semantic-mediawiki.org/issues/92

**Closed by kghbln** 2022-06-16 14:59 UTC
Labels: bug

**Comment by kghbln** [comment] 2022-06-17 05:54
@krabina Will a blank new sandbox help you or are you seeking for something that was on the sandbox wiki?

**Comment by krabina** [comment] 2022-06-17 07:10
No, I was trying to look up something from an older issue in sandbox.

**Comment by krabina** [comment] 2022-06-17 07:10
why don't you bring it to life with vector skin for the time being?

**Comment by kghbln** [comment] 2022-06-17 07:32
> No, I was trying to look up something from an older issue in sandbox.

That's what I thought. The reason why I have not yet just created a blank sandbox.
