### ISSUE TITLE
Trying to access array offset on value of type bool in /var/www/sub/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

### ISSUE THREAD

**Issue by nekromoff** [SemanticMediaWiki/SemanticMediaWiki#4647] opened 2020-03-14 13:35 UTC
### Setup and configuration

- SMW version: 3.1.5
MediaWiki | 1.34.0
PHP | 7.4.2 (apache2handler)
MariaDB | 10.1.41-MariaDB-0+deb9u1

### Issue

Notices in server log:
Trying to access array offset on value of type bool in /var/www/sub/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

**Comment by jaideraf** [comment] 2020-03-14 15:46
SMW 3.1.5 requires PHP from 7.0.0 to 7.3.x. See the [compatibility matrix](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md).

**Comment by kghbln** [comment] 2020-03-14 16:45
Duplicate of #4541

**Closed by kghbln** 2020-03-14 16:45 UTC
Labels: bug, duplicate
