### ISSUE TITLE
Argument 1 passed to .../JobFactory::newUpdateDispatcherJob() must be an instance of Title, null given

### ISSUE THREAD

**Issue by KenanSulayman** [SemanticMediaWiki/SemanticMediaWiki#2125] opened 2016-12-20 04:02 UTC
### Setup and configuration

- SMW: 2.4.4
- MW: 1.26.4 (2e3e739)
- PHP: HHVM 3.15.2 (srv)
- MySQL: 5.7.16
- ICU: 52.1
- Lua: 5.1.5

### Issue

Cannot run `rebuildData.php` after successful data rebuild process.

<img width="793" alt="screen shot 2016-12-20 at 05 00 24" src="https://cloud.githubusercontent.com/assets/280212/21337860/3e32a574-c671-11e6-8158-840bfc377114.png">

I wanted to debug this error, but since it doesn't return a stack trace, it becomes prohibitively complicated.

How can I fix this? It happens quite random.

Thanks ✈️

**Comment by Nikerabbit** [comment] 2016-12-20 08:28
For HHVM, maybe https://github.com/facebook/hhvm/issues/4818#issuecomment-73813509 would help? Perhaps it also needs a custom error handler.

**Comment by kghbln** [comment] 2016-12-20 09:42
Thanks for reporting. There was a similar issue in the past #1143 so this is probably a variation happening at another spot.

**Comment by mwjames** [comment] 2016-12-20 10:26
Hi,

> I wanted to debug this error, but since it doesn't return a stack trace, it
> becomes prohibitively complicated.
>
> How can I fix this? It happens quite random.

> JobFactory::newUpdateDispatcherJob()

As far as I can tell, there are only two places that make this call,
with one invocation directly using a Title object hence can be
ignored. The other call happens [0] where we try to create a Title
object with the help of `Title::makeTitleSafe`.

The creation of a title should always work by relying on
`Title::makeTitleSafe` (instead of returning a null) but I remember
that we had a situation which involved `wgCapitalLinks` where a Title
would suddenly fail with null [1].

Since creating the situation is difficult (== cannot be tested without
considerable effort) as described in [1], I'll make an educated guess
as to how to avoid the situation by adding a check to
`SMW\PropertySpecificationChangeNotifier`:

```
@@ -67,10 +67,14 @@ class PropertySpecificationChangeNotifier {

 		if ( $this->semanticData->getSubject()->getNamespace() !==
SMW_NS_PROPERTY ) {
 			return;
 		}

+		if ( $this->semanticData->getSubject()->getTitle() === null ) {
+			return;
+		}
+
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/EventListenerRegistry.php#L144-L146

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1318#issuecomment-185480147

Cheers

**Comment by KenanSulayman** [comment] 2016-12-20 14:05
I managed to obtain a reasonable stack trace using the HHVM debugger:

```
root@07f3c062750f:/var/www/public/w/extensions/SemanticMediaWiki/maintenance# hhvm -a rebuildData.php
Welcome to HipHop Debugger!
Type "help" or "?" for a complete list of commands.

Program rebuildData.php loaded. Type '[r]un' or '[c]ontinue' to go.
hphpd> exception error
exception error
Breakpoint 1 set right after an error
hphpd> c

Running for storage: SMWSQLStore3

Removing table entries (marked for deletion).

.Breakpoint 1 reached: An error occurred at SMW\MediaWiki\Jobs\JobFactory::newUpdateDispatcherJob() on line 89 of /var/www/public/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/JobFactory.php
  88     */
  89*   public function newUpdateDispatcherJob( Title $title, array $parameters = array() ) {
  90*       return new UpdateDispatcherJob( $title, $parameters );
  91*   }
  92 

Error Message: Argument 1 passed to SMW\MediaWiki\Jobs\JobFactory::newUpdateDispatcherJob() must be an instance of Title, null given
hphpd> w
w
#0   ()
    at /var/www/public/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/JobFactory.php:91
#1  SMW\MediaWiki\Jobs\JobFactory::newUpdateDispatcherJob (null)
    at /var/www/public/w/extensions/SemanticMediaWiki/src/EventListenerRegistry.php:146
#2  Closure$SMW\EventListenerRegistry::registerStateChangeEvents (Onoi\EventDispatcher\DispatchContext Object
(
    [container":"Onoi\EventDispatc ...(omitted))
#3  call_user_func_array ("Closure\$SMW\\EventListenerRegistry::registerStateChangeEvents;1084011124", Array
(
    [0] => Onoi\EventDispatcher\DispatchContext Object
        (
        ...(omitted))
    at /var/www/public/w/vendor/onoi/event-dispatcher/src/Listener/GenericCallbackEventListener.php:62
#4  Onoi\EventDispatcher\Listener\GenericCallbackEventListener::execute (Onoi\EventDispatcher\DispatchContext Object
(
    [container":"Onoi\EventDispatc ...(omitted))
    at /var/www/public/w/vendor/onoi/event-dispatcher/src/Dispatcher/GenericEventDispatcher.php:122
#5  Onoi\EventDispatcher\Dispatcher\GenericEventDispatcher::dispatch ("property.specification.change", Onoi\EventDispatcher\DispatchContext Object
(
    [container":"Onoi\EventDispatc ...(omitted))
    at /var/www/public/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php:213
#6  SMW\SQLStore\PropertyTableIdReferenceDisposer::triggerResetCacheEventBy ("788")
    at /var/www/public/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php:109
#7  SMW\SQLStore\PropertyTableIdReferenceDisposer::cleanUpTableEntriesById ("788")
    at /var/www/public/w/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableIdReferenceDisposer.php:94
#8  SMW\SQLStore\PropertyTableIdReferenceDisposer::cleanUpTableEntriesByRow (stdClass Object
(
    [smw_id] => "788"
)
)
    at /var/www/public/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/EntityIdDisposerJob.php:57
#9  SMW\MediaWiki\Jobs\EntityIdDisposerJob::executeWith (stdClass Object
(
    [smw_id] => "788"
)
)
    at /var/www/public/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php:402
#10  SMW\Maintenance\DataRebuilder::doDisposeMarkedOutdatedEntities ()
     at /var/www/public/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php:226
#11  SMW\Maintenance\DataRebuilder::doRebuildAll ()
     at /var/www/public/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php:168
#12  SMW\Maintenance\DataRebuilder::rebuild ()
     at /var/www/public/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php:151
#13  SMW\Maintenance\RebuildData::execute ()
     at /var/www/public/w/maintenance/doMaintenance.php:103
#14  include ("/var/www/public/w/maintenance/doMaintenance.php")
     at /var/www/public/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php:198
```

After trawling through the code, I figured the process failed at cleaning up an entry it obtained from the `smw_object_ids` table. As visible in the above stack frame list, the failure occurs at the table entry `smw_id=788`.

I executed a query in order to obtain that entry:

`SELECT * FROM smw_object_ids WHERE smw_id=778;`

```
smw_id,smw_namespace,smw_title,smw_iw,smw_subobject,smw_sortkey,smw_proptable_hash
778, 106, "Event_calendar_item", <empty>, <empty>, "Event calendar item", <null>
```

Based on heuristical observation I noticed the namespace is unique in a 100 item query sample, so I queried for items with `smw_namespace=106`. The result yields only the above item in the table.

Given my previous bug report, I assume the 106 namespace was part of the Flow extension prior to its deletion from the MediaWiki installation. That is, the namespace definition probably vanished alongside the extension, causing SMW to fail when trying to resolve the namespace.

I'll be in a meeting for an hour now, but will try to remove that entry, rerun `rebuildData.php` and finally report to you.

✌️

**Comment by KenanSulayman** [comment] 2016-12-20 15:49
The process continued until it hit another row, this time the data it encompasses it quite interesting:

`788,102,0x4469666672616374696F6E2727275F2D5F546865726527735F6E6F5F706167655F666F725F746869732C5F6275745F77686572657665725F74686572655F7761735F6C696768745F74686572655F776572655F77617665735F6F665F7261696E626F775F636F6C6F757265645F6172636865735F746861745F6D6F7665645F696E5F616E5F7570776172645F6D6F74696F6E2E5F49745F7761735F6F6E6C795F6F6E5F7468655F686F72697A6F6E5F757375616C6C792C5F6F725F7768656E657665725F495F776F756C645F73746172655F61745F6C69676874732E0A0A272727436F676E69746976655F446973746F7274696F6E733A2727270A2A272727,0x3A736D772D64656C657465,0x,0x4469666672616374696F6E272727202D2054686572652773206E6F207061676520666F7220746869732C2062757420776865726576657220746865726520776173206C696768742074686572652077657265207761766573206F66207261696E626F7720636F6C6F75726564206172636865732074686174206D6F76656420696E20616E20757077617264206D6F74696F6E2E20497420776173206F6E6C79206F6E2074686520686F72697A6F6E20757375616C6C792C206F72207768656E65766572204920776F756C64207374617265206174206C69676874732E0A0A272727436F676E697469766520446973746F7274696F6E733A2727270A2A272727,<null>`

The long, encoded string is essentially this:

```
Diffraction'''_-_There's_no_page_for_this,_but_wherever_there_was_light_there_were_waves_of_rainbow_coloured_arches_that_moved_in_an_upward_motion._It_was_only_on_the_horizon_usually,_or_whenever_I_would_stare_at_lights.

'''Cognitive_Distortions:'''
*'''
```

And creating a title from it yields *null*. The row has `:smw-delete` set as value for `smw_iw`, so I'm quite confident that the row is used by SMW. That is, I'm not entirely sure if the above workaround by skipping null / corrupt titles is appropriate (`$this->semanticData->getSubject()->getTitle() === null`).

Nevertheless, the workaround doesn't work unfortunately. I am trying to identify the root cause.

**Comment by mwjames** [comment] 2016-12-20 16:00
Hi,

>
> And creating a title from it yields *null*. The row has `:smw-delete` set as

I'm pretty sure you are using an outdated 2.5@dev because
`PropertyTableIdReferenceDisposer` contains a check on the
`:smw-delete` iw field [0].

>
> Nevertheless, the workaround doesn't work unfortunately. I am trying to
> identify the root cause.

> is, I'm not entirely sure if the above workaround by skipping null / corrupt
> titles is appropriate (`$this->semanticData->getSubject()->getTitle() ===
> null`).

We'll need to add an additional check since we trigger a
`property.specification.change` to ensure that we clean-up everything
before the ID is removed. It goes without saying that this should only
happen in case of the NS being SMW_NS_PROPERTY (it is an oversight but
I'm glad we found that before the 2.5 release).

```
@@ -205,14 +205,16 @@ class PropertyTableIdReferenceDisposer {
 		$eventHandler->getEventDispatcher()->dispatch(
 			'cached.prefetcher.reset',
 			$dispatchContext
 		);

-		$eventHandler->getEventDispatcher()->dispatch(
-			'property.specification.change',
-			$dispatchContext
-		);
+		if ( $subject->getNamespace() === SMW_NS_PROPERTY ) {
+			$eventHandler->getEventDispatcher()->dispatch(
+				'property.specification.change',
+				$dispatchContext
+			);
+		}
```

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SQLStore/PropertyTableIdReferenceDisposer.php#L191-L197

Cheers

**Comment by KenanSulayman** [comment] 2016-12-20 20:59
`rebuildData.php` still fails with the identical error, on the above-named row. The process itself is a little opaque, so I still didn't find any obvious cause.

**Comment by KenanSulayman** [comment] 2016-12-26 00:28
Now that it's Christmas, I had the chance to put the server into read-only mode and proxy it to a mirror instance, so that I can work on the primary server. Deleting all data using `setupData.php --delete`, then initialising data using `setupData.php` and finally `rebuildData.php` fixed it.

You can replicate my previous situation like this:

1. Setup a test instance and copy over data from an existing MediaWiki database, including SMW data.
2. Execute these queries with the correct prefix, the '122' is a random number.
```
UPDATE `<prefix>_revision` SET `rev_content_model`="flow-board" WHERE rev_id=122;
UPDATE `<prefix>_revision` SET `rev_content_format`="application/json" WHERE rev_id=122;
```
3. Run the `rebuildData.php` script, it should fail with an error.
4. Re-run the script, it should be corrupt now in a way that it fails with my error.

Happy Christmas! 🎄🎉

**Comment by mwjames** [comment] 2017-01-01 14:55
> SMW: 2.4.4
> SMW\SQLStore\PropertyTableIdReferenceDisposer::triggerResetCacheEventBy ("788")

For the reported issue, two facts contradict each other because `triggerResetCacheEventBy` doesn't exist [0] in 2.4.4 therefore I assume you are using 2.5.0-alpha on the server that observes the null title issue.

> UPDATE `<prefix>_revision` SET `rev_content_model`="flow-board" WHERE rev_id=122;
UPDATE `<prefix>_revision` SET `rev_content_format`="application/json" WHERE rev_id=122;

Having thought a bit about this scenario, I came to the conclusion that a `NullJob` (#2143) should be sufficient in case some titles are null (due to no longer available content model etc.) instead of trying to match a job specification. This approach should be generic enough to handle a null title for all our jobs that are created via `JobFactory::newByType`.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/src/SQLStore/PropertyTableIdReferenceDisposer.php

**Comment by kghbln** [comment] 2017-01-07 11:33
@KenanSulayman The fix is not in master. Perhaps you may try it on your test instance and see if the issue is still around.

**Comment by KenanSulayman** [comment] 2017-01-12 00:32
I just updated to latest master, failed and I guess the corrupted the database again.

```
Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function getTouched() on a non-object (null)' in /var/www/public/w/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/QueryDependencyLinksStore.php:370
Stack trace:
#0 /var/www/public/w/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/QueryDependencyLinksStore.php(297): SMW\SQLStore\QueryDependency\QueryDependencyLinksStore->canSuppressUpdateOnSkewFactorFor()
#1 /var/www/public/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(571): SMW\SQLStore\QueryDependency\QueryDependencyLinksStore->doUpdateDependenciesFrom()
#2 /var/www/public/w/includes/Hooks.php(201): Closure$SMW\MediaWiki\Hooks\HookRegistry::registerHooksForInternalUse#3()
#3 /var/www/public/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(321): Hooks::run()
#4 /var/www/public/w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(405): SMWSQLStore3->getQueryResult()
#5 /var/www/public/w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(194): SMWQueryProcessor::getResultFromQuery()
#6 /var/www/public/w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(122): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters()
#7 /var/www/public/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(289): SMW\ParserFunctions\AskParserFunction->parse()
#8 /var/www/public/w/includes/parser/Parser.php(3805): Closure$SMW\ParserFunctionFactory::newAskParserFunctionDefinition()
#9 /var/www/public/w/includes/parser/Parser.php(3539): Parser->callParserFunction()
#10 /var/www/public/w/includes/parser/Preprocessor_Hash.php(1104): Parser->braceSubstitution()
#11 /var/www/public/w/includes/parser/Parser.php(3681): PPFrame_Hash->expand()
#12 /var/www/public/w/includes/parser/Preprocessor_Hash.php(1104): Parser->braceSubstitution()
#13 /var/www/public/w/includes/parser/Preprocessor_Hash.php(1543): PPFrame_Hash->expand()
#14 /var/www/public/w/includes/parser/Parser.php(3678): PPTemplateFrame_Hash->cachedExpand()
#15 /var/www/public/w/includes/parser/Preprocessor_Hash.php(1104): Parser->braceSubstitution()
#16 /var/www/public/w/includes/parser/Parser.php(3358): PPFrame_Hash->expand()
#17 /var/www/public/w/includes/parser/Parser.php(1244): Parser->replaceVariables()
#18 /var/www/public/w/includes/parser/Parser.php(444): Parser->internalParse()
#19 /var/www/public/w/includes/content/WikitextContent.php(331): Parser->parse()
#20 /var/www/public/w/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput()
#21 /var/www/public/w/extensions/SemanticMediaWiki/includes/ContentParser.php(184): AbstractContent->getParserOutput()
#22 /var/www/public/w/extensions/SemanticMediaWiki/includes/ContentParser.php(144): SMW\ContentParser->fetchFromContent()
#23 /var/www/public/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(122): SMW\ContentParser->parse()
#24 /var/www/public/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(106): SMW\MediaWiki\Jobs\UpdateJob->needToParsePageContentBeforeUpdate()
#25 /var/www/public/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(75): SMW\MediaWiki\Jobs\UpdateJob->doPrepareForUpdate()
#26 /var/www/public/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(61): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#27 /var/www/public/w/extensions/SemanticMediaWiki/src/SQLStore/EntityRebuildDispatcher.php(198): SMW\MediaWiki\Jobs\UpdateJob->run()
#28 /var/www/public/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(307): SMW\SQLStore\EntityRebuildDispatcher->startRebuildWith()
#29 /var/www/public/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(266): SMW\Maintenance\DataRebuilder->doExecuteFor()
#30 /var/www/public/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(168): SMW\Maintenance\DataRebuilder->doRebuildAll()
#31 /var/www/public/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(151): SMW\Maintenance\DataRebuilder->rebuild()
#32 /var/www/public/w/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#33 /var/www/public/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): include()
#34 {main}
```

I wonder what that might be..

**Comment by mwjames** [comment] 2017-01-12 00:45
Hi,

> Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call
> to a member function getTouched() on a non-object (null)' in

Okay, I never thought that those invalid titles (== null, non existing
NS, wrong content model etc.) are causing so much trouble.

As for an explanation, we try to access a title with
`$subject->getTitle()->getTouched()` which if it hits a null title,
fails and we do not explicitly check for null hence it returns with a
`BadMethodCallException`.

I'll make a PR during the weekend but for now I only can provide a quick fix:

```
@@ -364,12 +364,14 @@ class QueryDependencyLinksStore {
 			),
 			array( 's_id' => $sid ),
 			__METHOD__
 		);

-		if ( !isset( $suppressUpdateCache[$hash] ) ) {
-			$suppressUpdateCache[$hash] = $subject->getTitle()->getTouched() +
$this->skewFactorForDepedencyUpdateInSeconds;
+		$title = $subject->getTitle();
+
+		if ( !isset( $suppressUpdateCache[$hash] ) && $title !== null ) {
+			$suppressUpdateCache[$hash] = $title->getTouched() +
$this->skewFactorForDepedencyUpdateInSeconds;
 		}
```

... and I do hope that this is the last of them that could fail on a NULL title.

Cheers

**Comment by mwjames** [comment] 2017-01-14 15:43
> Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function getTouched() on a non-object (null)' in /var/www/public/w/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/QueryDependencyLinksStore.php:370
> I'll make a PR during the weekend but for now I only can provide a quick fix:

Fixed with #2166.

**Comment by KenanSulayman** [comment] 2017-01-18 22:16
I can verify that the process now finished 4 times correctly, thank you for that. Also, I will try to produce an error condition later this week that I was dealing with previously, verifying and closing this issue.

🍻

**Comment by kghbln** [comment] 2017-01-18 23:09
@KenanSulayman Thanks a lot for reporting back. Keeping fingers crossed. ;)

**Comment by mwjames** [comment] 2017-02-11 11:50
> I can verify that the process now finished 4 times correctly, thank you for that.

... and hereby closing the issue.

**Closed by mwjames** 2017-02-11 11:50 UTC
Labels: bug
