### ISSUE TITLE
2.4.2 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#1751] opened 2016-08-02 06:26 UTC
Tracking issue for a possible (not yet defined) release.
- [x] #1823
- [x] #1883 
- [x] #1885 
- [x] #1887 
- [x] #1901

**Comment by mwjames** [comment] 2016-10-05 17:30
Personally, I will have no time for this so maybe asking on the mailing-list on who wants to help out (and I'm mean NOT Karsten) otherwise I will close this task on my next week's support slot.

**Comment by JeroenDeDauw** [comment] 2016-10-05 21:59
No need to close it next week. I'll try to get to it, but it might be afterwards.

**Comment by kghbln** [comment] 2016-10-25 12:46
This is confusing. Apparently the code for #1901 is already within the 2.4.x branch tough it was not backported. Probably I should back off here.

**Comment by kghbln** [comment] 2016-11-05 13:56
@JeroenDeDauw Something we could do about release rot. As far as I see there is already enough for a 2.4.3

**Comment by JeroenDeDauw** [comment] 2016-11-05 21:58
Things get a lot easier if the minor releases get done more frequently, ie 2.5.0 happening soon.

I don't understand your comment about 2.4.3, as there is no 2.4.2 yet

**Comment by JeroenDeDauw** [comment] 2016-11-05 22:00
I've merged the stuff, so these commits are now on 2.4.x. Someone double checking things did not get messed up in the rebase would be good, as @mwjames mentioned already.

**Comment by JeroenDeDauw** [comment] 2016-11-05 22:03
@SemanticMediaWiki/testers to try out the development version of 2.4.2, change the version of SMW in `composer.json` to `2.4.x@dev` and run `composer update`. We want to know if the functionality critical to you is in working order.

@mwjames could you provide some pointers on what exactly to test based on what might have gotten broken?

**Comment by kghbln** [comment] 2016-11-05 23:02
> I don't understand your comment about 2.4.3, as there is no 2.4.2 yet

I meant if we had release 2.4.2 a month ago we could already have done a 2.4.3 by now.

**Comment by mwjames** [comment] 2016-11-05 23:08
> could you provide some pointers on what exactly to test based on what might have gotten broken?

Some have been tested, others relate to postgres text/bytea storage, the most critical is #1887 that should fix once and for all the registration of Property namespaces independent of whether an extension with a `extension.json` is invoked or not.

**Comment by kghbln** [comment] 2016-11-05 23:16
"rebuildData.php" gives me this:
```
PHP Fatal error:  Class 'SMWDIHandlerWikiPage' not found in /.../extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php on line 212

Fatal error: Class 'SMWDIHandlerWikiPage' not found in /.../extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php on line 212
```
Note that I have killed and recreated the backend before with "setupStore.php".

**Comment by mwjames** [comment] 2016-11-05 23:25
> PHP Fatal error:  Class 'SMWDIHandlerWikiPage'

Relates to a static composer autoload file. Those files exists in the 2.4.* branch. Doing a `dump-autoload` should correct this.

**Comment by mwjames** [comment] 2016-11-05 23:26
This is problem when mixing an master branch with a backport branch but nothing you can do much about it (unless you are scrapping the whole vendor dir and start from scratch).

**Comment by kghbln** [comment] 2016-11-06 00:10
`dump-autoload`fixed the issue with the class but now I am getting

```
PHP Fatal error:  Call to protected method Database::makeSelectOptions() from context 'SMW\MediaWiki\Database' in /.../extensions/SemanticMediaWiki/src/MediaWiki/Database.php on line 297

Fatal error: Call to protected method Database::makeSelectOptions() from context 'SMW\MediaWiki\Database' in /.../extensions/SemanticMediaWiki/src/MediaWiki/Database.php on line 297
```

**Comment by mwjames** [comment] 2016-11-06 00:22
> HP Fatal error:  Call to protected method Database::makeSelectOptions() from context 'SMW\MediaWiki\Database' in /.../extensions/SemanticMediaWiki/src/MediaWiki/Database.php on line 297

This relates to [0] 1.28 and the fact the method vanished in 1.28. I fixed this in 2.5 with #1911 by adding `return DatabaseHelper::makeSelectOptions( $options );` and copied the core function to our `DatabaseHelper` compat class.


[0] https://phabricator.wikimedia.org/T147550

**Comment by kghbln** [comment] 2016-11-06 09:56
> This relates to [0] 1.28 and the fact that the method vanished in 1.28.

I am grumpy now.

**Comment by mwjames** [comment] 2016-11-06 14:07
> ... copied the core function to our DatabaseHelper compat class.
> I am grumpy now.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/8e0ed06aa29a511712def2c72c3d1bbf77f14531

**Comment by kghbln** [comment] 2016-11-08 15:13
@SemanticMediaWiki/testers I have just switched the [sandbox wiki](http://sandbox.semantic-mediawiki.org/wiki/Main_Page) to use the 2.4.x branch and have no longer encountered issues doing so. It will be very kind if you could test a couple of things on the wiki and report back in case you encounter issues. Much appreciated. Thanks for your help!

**Comment by kghbln** [comment] 2016-11-08 16:00
another worry:  `Fatal error: Call to undefined method DatabaseMysqli::getSearchEngine() in /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Search/Search.php on line 58` happens when trying to use "Special:Search"

**Comment by JeroenDeDauw** [comment] 2016-11-08 20:29
That'd be caused by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1897

**Comment by mwjames** [comment] 2016-11-12 06:59
>... #1897 fixes

Cherry-picked https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/76e24c6a2008cb6272dc8a3206dc8144b2188101 and added to 2.4.x.

**Comment by mwjames** [comment] 2016-11-12 07:00
2.4.2 should now work indiscriminately with MW 1.28!

**Comment by JeroenDeDauw** [comment] 2016-11-12 07:37
Any objections to creating the tag?

**Comment by kghbln** [comment] 2016-11-12 11:32
> Cherry-picked 76e24c6 and added to 2.4.x.

Great. Thanks a lot!

> 2.4.2 should now work indiscriminately with MW 1.28!

At least it does with rc.0

> Any objections to creating the tag? I realize no release notes is not ideal, but a release without release notes is still better than no release.

Well, it should not be too hard to pipe release notes in before tagging. I will try now. Apart form that. Except for me being grumpy all the time nobody provided feedback which can be translated into: No objection!. And this is what I think.

**Comment by mwjames** [comment] 2016-11-12 11:42
>  nobody provided feedback which can be translated into

...it translates into no one bothered to actual test it which means if something goes south users are to blame for it (we gave it enough leeway).

**Comment by kghbln** [comment] 2016-11-12 11:52
> ...it translates into no one bothered to actual test

I guess you misunderstood my subtle criticism. ;) Probably I am a bit more diplomatic.

**Comment by kghbln** [comment] 2016-11-12 11:55
@JeroenDeDauw Once #2008 is merged all that is needed is to change [load.php#L31](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.4.x/load.php#L31) and tag

**Comment by mwjames** [comment] 2016-11-12 11:57
> I guess you misunderstood my subtle criticism. ;) Probably I am a bit more diplomatic.

I understood the subliminal message but I really have enough of this, asking people to make some simple tests and get some feedback shouldn't be that hard. Only when users encounter an issue they scream fire and like to have it fixed yesterday.

**Comment by JeroenDeDauw** [comment] 2016-11-13 02:33
Don't worry @mwjames, @kghbln will surely protect you from the fire breathing users.

![kgh](https://cloud.githubusercontent.com/assets/146040/20243290/f22224a2-a951-11e6-8e67-72e77abdc774.png)

**Comment by JeroenDeDauw** [comment] 2016-11-13 02:36
2.4.2 tag created

**Closed by JeroenDeDauw** 2016-11-13 02:36 UTC
Labels: roadmap

**Comment by kghbln** [comment] 2016-11-14 09:45
@JeroenDeDauw Wiki fluff including wiki announcement is done. Could you do this "social" media stuff like e-mail and twitter?

**Comment by JeroenDeDauw** [comment] 2016-11-15 06:01
Sure. Though I'm a bit dubious about classifying email as social media :)

**Comment by kghbln** [comment] 2016-11-15 09:21
> Sure.

Cool.

> Though I'm a bit dubious about classifying email as social media :)

That's why I added the quotation marks to social. I totally agree that one in contrast should actually try to be serious with/in e-mails.

**Comment by mwjames** [comment] 2016-11-19 02:18
I had a quick look at the [0] on the last 2.4.2 merge and unfortunately as well as unpleasantly, the back-port for the `DatabaseHelper` (required due to MW 1.28) contains a `[]` (PHP 5.5+) usage [1] which is invalid in a PHP 5.3/5.4* environment and ultimately fails [0].

The specific function is only called on `format=debug` which should barely be used by users, yet it is somewhat unsettling given that 2.4* is advertised with PHP 5.3 support.

What are the options:

- Keep the issue until the first user complains and release a 2.4.3 by that time or
- Push an immediate 2.4.3

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/175415401

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/DatabaseHelper.php#L25

**Comment by kghbln** [comment] 2016-11-19 12:41
> The specific function is only called on format=debug which should barely be used by users, yet it is somewhat unsettling given that 2.4* is advertised with PHP 5.3 support.

Given the extent of the impact this has it is indeed a rather marginal issue. Thus I'd go for option 1) or propose option 3) Waiting until we have another fix on top which could potentially be https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1975 after feedback was provided.
