### ISSUE TITLE
SMW::off and SMW::on showing in VisualEditor

### ISSUE THREAD

**Issue by cariaso** [SemanticMediaWiki/SemanticMediaWiki#1055] opened 2015-06-09 23:01 UTC
![screen shot 2015-06-09 at 6 58 03 pm](https://cloud.githubusercontent.com/assets/125330/8071587/a0a7edfa-0ed9-11e5-873b-c75a047d3964.png)

I setup my first version of SNPedia.com with VisualEditor and noticed that my main template has 
SMW::off and SMW::on showing during editing. This isn't a huge problem, but it is new and undesired behavior and it seemed worth documenting it.

**Comment by mwjames** [comment] 2015-06-09 23:55
See [0].

In order for `SMW::off` / `SMW::on` to be hidden it is required that [1, 2] are executed. Since the normal "wikitext" editing does work as expected, I'm inclined to argue that the VisualEditor/Parsoid doesn't execute the required hooks or the parsing is intercepted at same point.

Anyone who can  install/maintain VisualEditor/Parsoid can help debugging this by reporting at which point SMW (together with the hooks provided by MW) isn't executed as compared to the normal wikitext.

[0] https://phabricator.wikimedia.org/T76278

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/InTextAnnotationParser.php#L257

[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/Hooks/InternalParseBeforeLinks.php#L102-L110

**Comment by mwjames** [comment] 2015-06-19 16:53
@cariaso I don't expect any help from the VF/Parsoid team (as T76278 has being inactive for over 6 month) and since I don't have time to install yet let alone debug VF, I added a work around with #1068 (SMW 2.3).

If `$GLOBALS['smwgAllowUnrestrictedTemplateParse']` is set `true` it should disable the output of `SMW::off` / `SMW::on` in your VF session.

I can't say whether `$GLOBALS['smwgAllowUnrestrictedTemplateParse']` will have an impact on performance if enabled (as templates are going to be parsed unrestricted) but it is the most non-inverse PR that let you use SMW and VF all together.

I'm expecting non of the SMW-core devs to delve into VF therefore I hope that #1068 is enough to make SMW and VF to work side by side.

@kghbln Maybe something for the docu, I guess!

**Comment by cariaso** [comment] 2015-06-19 17:03
I used VisualEditor/Parsoid for about 3 days, and then disabled it, as I've found that saving a page with VE didn't cause the semantic properties to be set. However I've automated the install and can say that these steps installation steps worked for me on a centos/amazon linux:

in LocalSettings.php

require_once("$IP/extensions/VisualEditor/VisualEditor.php");
$wgDefaultUserOptions['visualeditor-enable'] = 1;


system wide from the wiki extensions directory

git clone -b REL1_25 https://gerrit.wikimedia.org/r/p/mediawiki/extensions/VisualEditor.git
cd VisualEditor
  edit VisualEditor.php and change
                                                     http://localhost:8000
   to
                                                     http://localhost:8800
  git submodule update --init

sudo yum -y install nodejs npm --enablerepo=epel
git clone https://gerrit.wikimedia.org/r/p/mediawiki/services/parsoid
cd parsoid
sudo npm install

/var/www/html/extensions/parsoid/api/localsettings.js
'use strict';
exports.setup = function(parsoidConfig) {
        parsoidConfig.setMwApi('localhost', { uri: 'http://www.snpedia.com/api.php' });
        parsoidConfig.useSelser = true;
        parsoidConfig.serverPort = 8800;
};


I have a disposable machine with VE/parsoid installed and if you'll email a public key to cariaso@promethease.com
I'll be happy to offer a login where you can explore and feel free to modify or delete anything with no danger of doing any harm.

**Comment by mwjames** [comment] 2015-06-19 17:17
> I used VisualEditor/Parsoid for about 3 days, and then disabled it, as I've found that saving a page with VE didn't cause the semantic properties to be set.

I'm guessing that the inherent nature of the issue is that the hooks (as described above) required for processing aren't executed and as a result annotations can not be filtered.

If VF/Parsoid doesn't execute the standard hooks then there is no way for SMW to store or even query those annotations.

**Comment by mwjames** [comment] 2015-11-27 06:20
It has been a year since [0] and with the status of being uncommented from the WMF side, VE remains an utter mystery on how to make any integration work. Closing this issue as no actionable tasks can be inferred from [0].

[0] https://phabricator.wikimedia.org/T76278

**Closed by mwjames** 2015-11-27 06:20 UTC
Labels: mediawiki
