### ISSUE TITLE
Control display of namespace in printouts

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#5400] opened 2023-01-19 16:24 UTC
I am very surprised that this is not yet possible in SMW. The default link behaviour for pages is to hide the namespace in links. This is true for the mainlabel (the page names) as well as for datatype page.

I think there are two places where this has to be done:
1. For the main result column it would be good the either extend the [limit parameter](https://www.semantic-mediawiki.org/wiki/Help:Inline_queries) or introduce a new parameter. So in addition to `link=all, subject, or none`, we could have additionalle, allns, subjectns. So to extend the values to: `link=all, allns, subject, subjectns, none`
2. For individual printouts of datatype "page", there are already a lot of [formatting options](https://www.semantic-mediawiki.org/wiki/Help:Displaying_information), so we could add something comparable to `?Has URL#nowiki`, e. g. in the form of `?Has Page#namespace`

Any other suggestions?

**Comment by krabina** [comment] 2023-01-19 16:30
An example can be found here: https://sandbox.semantic-mediawiki.net/wiki/Issue/5400
The rationale behind it is that it might be very important to see that the page "**French accents**" is actually the page "**Discussion:French_accents**", which is especially important id such a query results both pages that then cannot be distinguished from each other (other than with hovering over the links).

While I can see that often you don't want to display the namespaces (which should stay the default behaviour), I would like to see more flexibility having the above mentioned options.

**Comment by bertrandgorge** [comment] 2023-01-19 17:42
I've never had the issue, but I use the template format extensively so I guess I'm not really concerned. In any case, I believe it would be better to have a formating option for that (option 2).

For option 1, you mean link, not limit ? I'm not sure it's the right place for doing that since you might want some columns with that behaviour but not some others ?

**Comment by thomas-topway-it** [comment] 2023-01-19 20:28
> https://github.com/Knowledge-Wiki/SemanticMediaWiki/commit/6f1cbce25c7537ddd18ea3538881de50e9c5f783

perhaps it could be used as default ? i.e. the prefix is always shown for namespaces other than main

**Comment by bertrandgorge** [comment] 2023-01-19 21:25
>  prefix is always shown for namespaces other than main

Hu, I would rather not ! For categories for a start, that would really not be that nice.

**Comment by krabina** [comment] 2023-01-19 21:28
Yes, I meant limit, not link, sorry. So it seems there is an easy fix for this. Would this be a problem for you @bertrandgorge in the template? I guess not, because you can always use magic words in template. And for large amounts of data, putting everything into templates for formatting slows things down more. So I think it is good to see the namespaces in links by default.

**Comment by krabina** [comment] 2023-01-19 21:29
> Hu, I would rather not ! For categories for a start, that would really not be that nice.

Indeed, you are right there. So @thomas-topway-it , maybe you can find a way to leave the default as is but implement the mentioned configuration options? It is always good to be flexible.

**Comment by thomas-topway-it** [comment] 2023-01-20 11:58
the problem is that the ResultPrinter calls directly the datavalue's methods getShortWikiText or getShortHTMLText and such methods are unaware of the parameters in the ask query.

In my opinion the ideal solution is to have
```
if ( $displayTitle === '' ) {
	$displayTitle = $this->getPrefixedText();
}
```

when the namespaces of subjects of the ask query are mixed

and

```
if ( $displayTitle === '' ) {
	$displayTitle = $this->getText();
}
```

when they aren't mixed (for instance when the output is a list of categories, as pointed out by @bertrandgorge, but also a list of users if you are just querying users, etc.)

This rather than from the output (which otherwise should be evaluated as a whole) could be inferred from the query itself.

A temporary solution is to use a global parameter, like 
`$smwgShowNamespacePrefixInAskQueries = true;`

So in order to avoid the global parameter, the only solution is to extend various SMW methods (specifically includes/datavalues/SMW_DataValue.php) for they know when they are called by the ResultPrinter, (using the parameters in the ask query suggested by Bernhard) and (as additional refinement) to let SMW understand from the ask query that it would produce mixed results (and then using the prefixed subjects) rather than using additional parameters in the ask query itself (at least ideally)

**Comment by krabina** [comment] 2023-01-20 12:22
Great, thank you for the investigation!
Any thoughts on this @marijnvanwezel @YOUR1 @jaideraf @gesinn-it-gea @kghbln @hexmode @alex-mashin @cicalese @Abijeet @octfx @amire80 @HamishSlater?

Is it sufficient to implement 
`$smwgShowNamespacePrefixInAskQueries = true;`
or should we go the long route?

**Comment by jaideraf** [comment] 2023-01-20 12:51
> Is it sufficient to implement $smwgShowNamespacePrefixInAskQueries = true;

Fine by me. If is not changing the default behavior of hundreds of wikis, it is fine. Extending the Ask query language even more is also dangerous. I would prefer a standardization of the options between result formats than adding more options that would work only in one or two formats.

**Comment by krabina** [comment] 2023-01-20 13:05
With "standardization" do you mean to solve what you have investigated in https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4749?

**Comment by jaideraf** [comment] 2023-01-20 13:19
> With "standardization" do you mean to solve what you have investigated in #4749?

Yes, but also https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/466 and https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/30 (the example is gone in this one)

**Comment by thomas-topway-it** [comment] 2023-01-20 13:42
so the global parameter rather than to output always the prefixed text, could enable the conditional output (with results prefixed only for mixed namespaces), without using additional parameters in the ask query. I'm not sure that this is possible but I will verify.
(this way the behavior of other wikis is not affected)

**Comment by krabina** [comment] 2023-01-20 18:55
For reference, the maps extension features a namespece option for the leaflet result format, see https://maps.extension.wiki/wiki/Leaflet_SMW_queries

**Comment by marijnvanwezel** [comment] 2023-01-20 23:32
I don't think using the proposed global is very useful. You want the display options to be controllable on the query level, not globally.

We can introduce a new argument to the `SMWDataValue::getShortText()` method, but that would kind of break the abstraction it provides. I cannot think of another way to do this that does not require a significant refactoring though. Any thoughts?

As to how the option should be passed; a new parameter is probably the best approach. We can introduce a parameter called `link namespace`, which takes the values `all` (include namespace in all links), `subject` (include namespace in subject links) and `none` (don't include namespace). That way, a user can e.g. print all pages as links, but only print the namespace for the subject.

**Comment by thomas-topway-it** [comment] 2023-01-21 07:49
@marijnvanwezel yes the global parameter would be justified only to keep the feature disabled by default in case it does not rely on new ask parameters.
Yesterday I've find out that the use of the method `newNamespaceDescription` internally used (among others) to build the query, might reveal query results without mixed namespaces. In this case one could conditionally enable/disable the prefix based on whether `newNamespaceDescription` has been used or not to build the query, without requiring additional parameters to be specified by the user.
Regarding (either where the prefix is manually required by the user through a parameter in the ask query, or determined this way) how to pass the data to the datavalue class, another way is to use a global variable (since the query is built before the results are printed) only for internal use, although this couldn't be a good practice.

**Comment by thomas-topway-it** [comment] 2023-01-21 07:54
-- or better than an internal global parameter, the query builder could be accessed by the datavalue class, I think other use-cases of this can be found in the SMW code

**Comment by thomas-topway-it** [comment] 2023-01-24 20:35
I think this 
[call datavalue getShortText/getLongText based on query description](https://github.com/Knowledge-Wiki/SemanticMediaWiki/commit/7e82de4b71bbd8e6c3c4d279c2ceaa59b9247881)

is a good solution that doesn't affect the abstraction of the datavalue classes. It also uses the idea to check for the query language NamespaceDescription to avoid additional parameters to be inserted manually in the query (which however would be the most reliable way, unless the automated way isn't extensively tested)

**Comment by thomas-topway-it** [comment] 2023-01-27 19:57
updated: from the Pull request abstract

> 
> Adds parameter `prefix` with values `'all', 'subject', 'none', 'auto' `
> 
> * The PR does not affect the default behavior of askquery results
> * The new parameter does not break the abstraction of the SMWDataValue class and sub-classes and as such does not change the interface of existing methods with additional parameters (only the class `ValueTextsBuilder` is created with a constructor taking the SMWQueryResult.) Instead, the existing SMWDataValue's `getShortText` and `getLongText` are concurrently used based on the new parameter
> * The new parameter also introduces an option "auto", checking whether the class  `SMW\Query\Language\Description`, used the create the query, is an instance of `NamespaceDescription`, which ensures that namespaces of the query results aren't mixed.
> * The PR does not make use of global parameters or global variables in order to work
>

**Comment by gesinn-it-gea** [comment] 2023-02-19 12:50
... sorry for my late reply on this. How about a printout format that allows to specify a "mapping template"? In this mapping template, you could remove the namepace or do some other magic. And folks would know "mapping template" from Page Forms already.

`?My URL#MT;Template-Name`

**Comment by alex-mashin** [comment] 2023-02-19 13:10
> ... sorry for my late reply on this. How about a printout format that allows to specify a "mapping template"? In this mapping template, you could remove the namepace or do some other magic. And folks would know "mapping template" from Page Forms already.
> `?My URL#MT;Template-Name`

Could be useful for some other purposes as well.

**Comment by krabina** [comment] 2023-02-20 08:29
As much as I like template regarding the flexiblity they bring, they also have a downside: the slow queries down considerably. So if you have a large amount of data to be retrieved in one query (e.g. to display on a map or via mermaid, etc.) you want to avoid putting them through templates. Namespace control is such a basic feature that I think it should be available in every query without templating.

**Comment by gesinn-it-gea** [comment] 2023-02-20 08:35
... map and mermaid are not the ideal example becaue both are JavaScript based where data needs to be transferred to the client. This is more likely the main bottleneck. I don't think that a template processing server-side causes some significant performance issue. It's worth some profiling, otherwise it's just wild guessing.

**Comment by krabina** [comment] 2023-02-20 08:56
I have experienced it in practice, confirming what is written here: https://www.semantic-mediawiki.org/wiki/Speeding_up_Semantic_MediaWiki#Slow_query_formatting

**Comment by thomas-topway-it** [comment] 2023-02-20 16:09
@gesinn-it-gea what about to open a separate issue for this ? If I understand correctly it is something I've already implemented for PageProperties (see [here](https://www.mediawiki.org/wiki/Extension:PageProperties##pageproperties)) and in the context of an ask query we could try to require a low recursion limit to avoid the slowdowns pointed out by Bernhard.

**Comment by thomas-topway-it** [comment] 2023-03-06 10:42
regarding the idea of a mapping-template for printouts I have now more data on this because I was about to use the recursiveTagParseFully for single cells content. So this in practical terms is possible and there are several use-cases where it is highly desirable. For instance when you want to manipulate the value of a printout/column and then to use it as a link for another page (is there a way to do it already?). Also, with the latest version of datatables you could set a low defer-each limit (the amount of rows to be retrieved at every call) and an initial reasonable limit (for instance a few hundred entries) and to retrieve the data-set incrementally (this is done automatically). Regarding nested templates this could be left to the responsibility of the administrators ... or to limit the recursion if technically possible.

**Comment by thomas-topway-it** [comment] 2023-03-10 10:57
@gesinn-it-gea and @alex-mashin added in the latest version ! https://www.semantic-mediawiki.org/wiki/Help:Datatables_format_(v2)

just use ` |?My property |+template=mytemplate ` or ` |? |+template=mytemplate ` for the mainlabel

git clone -b datatable-v2 https://github.com/Knowledge-Wiki/SemanticResultFormats

**Comment by jaideraf** [comment] 2023-03-13 21:09
@thomas-topway-it I just have tested the `|+template` feature in your `Datatables` implementation and I think there is a thing to fix. The syntax:

`|?Property name|+template=My template` works fine, but when there is [a label](https://www.semantic-mediawiki.org/wiki/Help:Displaying_information#Printing_property_values)

`|?Property name=My label|+template=My template` it doesn't work.

(I am sorry, I know here is not the appropriate place to report it, but considering the new `Datatables` is not yet merged, it would  be strange to create a new issue for something that is not in the codebase yet)

**Comment by thomas-topway-it** [comment] 2023-03-15 09:25
Done !
https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/770

Here are also some development notes:

https://www.semantic-mediawiki.org/wiki/Help:Datatables_format_(v2)/Development_notes

**Closed** 2023-09-22 23:19 UTC
Labels: new feature
