### ISSUE TITLE
Make Special:Ask sane

### ISSUE THREAD

**Issue by davidforgianni** [SemanticMediaWiki/SemanticMediaWiki#839] opened 2015-02-21 15:25 UTC
Contact : @JeroenDeDauw  (Tracking request: [37442](https://bugzilla.wikimedia.org/show_bug.cgi?id=37442))

Current ask code is not very decent and could benefit a lot from a full rewrite, making use of current MW and SMW features. Or it could just be ditched in favour of a new query UI if that gets created and brought to a usable and stable point.

**Comment by mwjames** [comment] 2017-08-20 10:41
> Current ask code is not very decent and could benefit a lot from a full rewrite,

Well, the code got a refresher with the expectation to bit more readable including compartmentalized functionality. I don't have time for a full rewrite and I can't see anyone raising the hand and screaming "me, me ..." therefore I'm closing this issue.

@kghbln `Special:Ask` requires some "handy" testing after all the re-factoring to verify that I did not introduced some involuntary regressions.

**Closed by mwjames** 2017-08-20 10:41 UTC
Labels: big, code quality, feature

**Comment by kghbln** [comment] 2017-08-21 09:07
@mwjames Wow, great work! After superficial testing it even works with [MobileFrontend](https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Requ%C3%AAter&mobileaction=toggle_view_mobile) though this could need some additional CSS tweaks.

**Comment by kghbln** [comment] 2017-08-21 09:10
@SemanticMediaWiki/testers Many improvements have been made to special page "Ask" for the upcoming 3.0 release. It will be great if you could test for involuntary regressions. Note that the changes were already merged so you could use current master for testing.

**Comment by jaideraf** [comment] 2017-08-22 02:59
:+1: Everything seems fine to me.

**Comment by mwjames** [comment] 2017-08-26 11:53
> it even works with MobileFrontend though this could need some additional CSS tweaks.

I added some minor tweaks (#2650) on obvious blunders caused by MobileFrontend which is not to say that all have been fixed.
