### ISSUE TITLE
Multilingual SemanticMediaWiki

### ISSUE THREAD

**Issue by roland2025** [SemanticMediaWiki/SemanticMediaWiki#1002] opened 2015-05-05 16:35 UTC
Hi.

Has anyone tried setting up a SemanticMediaWiki with Translations on a single server install?

Since I could find an answer online, maybe one of you has some experience.

Translation bundle
===============
* Set up Translation Bundle on SMW single server/single database install

don't really know if it is possible.

Semantic property
==============
Another approach, using 2 semantic properties per page (names can be improved):
* "Has language" 
* "Has neutral article" or "Has original article"

Define a neutral language, which most know, example: english
Pages in the neutral language: no need to have these properties.

Pages in non-neutral languages: should define the 2 properties, has language and has neutral/original article

What do you guys/gals think is the best approach?

Since SMWCon is tomorrow, maybe this is a topic, someone has had experience with :)

Best regards
--
Roland Uuesoo

**Comment by mwjames** [comment] 2015-05-05 16:39
Duplicate of #594

**Closed by mwjames** 2015-05-05 16:39 UTC
