### ISSUE TITLE
SMW off/on when embedded in MediaWiki system message

### ISSUE THREAD

**Issue by Clubfan22** [SemanticMediaWiki/SemanticMediaWiki#2370] opened 2017-03-31 15:00 UTC
### Setup and configuration

* [Setup A](http://wiki.liquipedia.space/commons/index.php?title=Special:Version):
- SMW version: 2.5.0
- MW version: 1.27.1
- PHP version: 5.6.30-0+deb8u1 (apache2handler)
- DB (MySQL etc.):  	5.5.54-0+deb8u1

* [Setup B](http://wiki.teamliquid.net/dota2/Special:Version?detail=1):
- SMW version: 2.2.2
- MW version: 1.25.2
- PHP version: 5.6.30-0+deb8u1 (fpm-fcgi)
- DB (MySQL etc.):  	10.1.22-MariaDB-1~jessie

### Issue

When using SMW in system messages in the MediaWiki: namespace, [[SMW:off]] and [[SMW:on]] annotations are visible.

Our use case is that we want to display semantic query results on uncreated pages to better assess if it's worth creating them. For that, we want to embed a query in MediaWiki:Noarticletext, MediaWiki:Noarticletest-nopermission and MediaWiki:Newarticletext. Everything works as intended except that [[SMW:off]] and [[SMW:on]] annotations are still in the output.

We first noticed it on our main setup (Setup B) and thought it might be related to the rather old MW and SMW versions, but it happens as well on the test wiki (Setup A).

- Definition of subobject: http://wiki.liquipedia.space/commons/index.php?title=Main_Page&action=edit&section=12
- MediaWiki system message with SMW query: http://wiki.liquipedia.space/commons/index.php?title=MediaWiki:Noarticletext&action=edit
- Uncreated page displaying the query (and the unwanted annotations): http://wiki.liquipedia.space/commons/index.php?title=TaeJa

Feel free to ask if you need more information about our setup and/or use case.
Thank you already!

Clubfan

**Comment by kghbln** [comment] 2017-03-31 15:57
Thanks for reporting. Most likely related to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2347

**Comment by Clubfan22** [comment] 2017-03-31 16:33
I already applied #2351 to Setup A, yet the issue remains.

**Comment by mwjames** [comment] 2017-03-31 16:57
Hi,

> Thanks for reporting. Most likely related to
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2347

It is indeed related and we made an exception for special pages but
this is not a bug and intended (== by design) to avoid parsing of code
executed during a `Message::parse` (we don't execute any SMW code for
any message that runs on a message parse). See comments in [0], you
can (yet that wasn't the use case mind when I added the parameter) use
`import-annotation=true` as parameter to invoke a recursive parse
while a template is resolved.

I don't intend to change [0] since that would open all sorts of
recursive parsing with possible unintended consequences.

[0] InternalParseBeforeLinks line 79.

Cheers

**Comment by mwjames** [comment] 2017-03-31 17:11
Hi,

>> Thanks for reporting. Most likely related to
>> https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2347
>
> It is indeed related and we made an exception for special pages but

Correction, 2347 is not related it was another issue during the
2.5.0-alpha testing (I don't have the number at hand).

Cheers

**Comment by mwjames** [comment] 2017-04-01 11:13
>  I don't intend to change [0] since that would open all sorts of recursive parsing with possible unintended consequences.

Messages are still disallowed from general parsing but to avoid introducing yet another parameter,  #2373 contains a small tweak that should allow for an exception in case `[[SMW::off]]` is detected.

**Comment by Clubfan22** [comment] 2017-04-01 11:28
Deployed #2373 to Setup A (test wiki) and can comfirm that it fixes the issue. Neither [[SMW:off]] nor [[SMW:on]] are included in the output anymore.

**Comment by mwjames** [comment] 2017-04-01 11:33
> Deployed #2373 to Setup A (test wiki) and can comfirm that it fixes the issue. 

That was quick, haven't even merged it to master.

**Comment by kghbln** [comment] 2017-04-02 07:17
Cool, great collaboration! Thanks for the insights and the tweaks @mwjames and thanks @Clubfan22 for the testing.

**Closed by kghbln** 2017-04-02 07:17 UTC
Labels: bug
