### ISSUE TITLE
State of undocumented hook `SMW::DataUpdater::ContentProcessor`

### ISSUE THREAD

**Issue by osnard** [SemanticMediaWiki/SemanticMediaWiki#5078] opened 2021-09-22 13:17 UTC
The hook `SMW::DataUpdater::ContentProcessor` has been added four years ago (#3122). Back then it was also documented in the `docs/technical/hooks.md`. This documentation apparently has been removed in the meantime, but the hook is still in the code.

Is is safe to bind code to this hook, or must it be seen as deprecated?

**Comment by kghbln** [comment] 2021-09-22 15:12
Duplicate of #4846

**Closed by kghbln** 2021-09-22 15:12 UTC
Labels: question
