### ISSUE TITLE
Problem with subobjects multiplying many times over

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#791] opened 2015-02-06 21:30 UTC
Dear community,

I'm using SMW for a cataloguing project on the website http://www.vanhamel.nl and stumbled on a remarkable and somewhat disturbing issue: 

* Last year or so, a page was moved from "Orcuin Néill Noígiallaig" to "Orcuin Néill Noígíallaig" (its new title), with the former being kept as a redirect page. There were some puzzling issues with that move, but I can't quite recall what happened at the time (I'm sorry to say). 
* Today I noticed that the counter for the special property "Has improper value for" is alarmingly high: 28790 pages and/or subobjects! 
* On closer inspection, it seems that about 99% (the vast majority) are mysterious 'ghost' subobjects belonging to the redirect page "Orcuin Néill Noígiallaig", even if there's no syntax associated with them. An improper value is recorded for "Property:Preserved commentary" (has type "text"). For some reason I'm not aware of, the number of subobjects must have been growing and growing until there were many thousands of them. And I'm worried that this is not the end of the loop, or whatever it is, either. 
* It is not impossible per se that this is a recent change rather than a trend that has building up over previous months. Why? As of today, I'm in the process of switching some 'subobjects' from Semantic Internal Objects (SIO) to SMW. I haven't abandoned SIO just yet, but I've added equivalent subobjects using the same properties and plan to remove their SIO counterparts once I'm certain they're no longer needed. On the other hand, this should not affect an old redirect page, let alone wandering subobjects that should not exist in the first place. 

Here are some links to my website that should hopefully help you form some idea of what's going on:
* Query showing subobjects: http://www.vanhamel.nl/w/index.php?title=Special:Ask&offset=1600&limit=500&q=%5B%5BHas+improper+value+for%3A%3AProperty%3APreserved+commentary%5D%5D&p=default%3D%28no-20improper-20value-20recorded%29%2Fformat%3Dbroadtable
* Property:Has improper value for: http://www.vanhamel.nl/wiki/Property:Has_improper_value_for
* Property:Preserved commentary: http://www.vanhamel.nl/wiki/Property:Preserved commentary
* The page: http://www.vanhamel.nl/wiki/Orcuin_N%C3%A9ill_No%C3%ADg%C3%ADallaig
* The redirect page: http://www.vanhamel.nl/w/index.php?title=Orcuin_N%C3%A9ill_No%C3%ADgiallaig&redirect=no

Finally, the specs:
* Semantic Bundle 1.9.2
* including Semantic MediaWiki 1.9.2
* including Semantic Internal Objects 0.7.6
* MediaWiki 1.22.7

Does anyone know how I should go about to solve this? 

Best,

Dennis Groenewegen

**Comment by mwjames** [comment] 2015-02-06 22:24
### Analysis
Property `Preserved commentary` is set by `Template:MS` containing:

```
--->{{#set_internal:Preserved
|Preserved in={{{1|}}}{{{MS|}}}
|Preserved in section={{{section|}}}
|Preserved at folio={{{folio|}}}{{{folios|}}}
|Preserved at page={{{page|}}}{{{pages|}}}
|Preserved at column={{{column|}}}{{{columns|}}}
|Preserved commentary={{{commentary|}}}
|Preserved tag={{{tag|}}}
|Preserved incipit={{{incipit|}}}
|Preserved heading={{{MS title|}}}
}}<!---

time to make the transition to subobjects! Will replace SIO some time later
--->{{#subobject:-
|Subobject describes=Manuscript witness of a text
|Preserved in={{{1|}}}{{{MS|}}}
|Preserved in section={{{section|}}}
|Preserved at folio={{{folio|}}}{{{folios|}}}
|Preserved at page={{{page|}}}{{{pages|}}}
|Preserved at column={{{column|}}}{{{columns|}}}
|Preserved commentary={{{commentary|}}}
|Preserved tag={{{tag|}}}
|Preserved incipit={{{incipit|}}}
|Preserved heading={{{MS title|}}}
}}</includeonly><noinclude>
```

A subobject name (is equivalent to its hash) of a property (Name#_7777) is based on the content it represents which means that if something changes on a subobject a new hash is generated and it is being handled as new subobject.

`Preserved commentary` is specified as text and currently I can't imagine what would cause some content to mark this as a `Has improper value for` value. Well, the assignment says `|Preserved commentary={{{commentary|}}}` but I'd expect `{{{commentary|}}}` to have a valid content.

#### Questions
- Why would a declared text property `Preserved commentary` been marked with `Has improper value for` taken in account that a text type property does not have any restrictions or limitations?
- What content changes are happening on `{{{commentary|}}` to require a subobject to calculate a new hash (and for that matter a new subobject)?
- Can you find out what normally is stored in `{{{commentary|}}}` and becomes a `Has improper value for` by the time it is assigned to the `Preserved commentary` property?

I can't make really sense of the above therefore my first and foremost single advice here is to update to the most recent SMW version. While I can't pinpoint to a related cause I know I fixed a minor issue related to redirects in 2.1 [0] and their is another #682 issue pending which have to be dealt with sooner rather than later.

Also try migrating to `#subobject` before the update to avoid chasing shadows.

As your using Semantic Bundle 1.9.2 please be cautious during the update to ensure that all classes are correctly updated (since SB is not using Composer). If you made the update you also be advised to run `rebuildData` to watch and monitor your subobject and especially your "Orcuin Néill Noígiallaig" page.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SQLStore/SMW_SQLStore3_Readers.php#L118

**Comment by jongfeli** [comment] 2015-02-06 22:30
Hello Dennis,

The skin on your site looks great but has moved far from the standard MW
skin. This means finding the "source code" of a page is difficult or was
made "impossible" ( it is on my tablet).

Question, is there any need for the redirecting page(s)? If not just delete
them and rebuild your SMW data to see if the problem is gone.

See: https://semantic-mediawiki.org/wiki/Help:Repairing_SMW%27s_data

Regards,

Felipe.
Op 6 feb. 2015 22:30 schreef "D-Groenewegen" <notifications@github.com>:

**Comment by D-Groenewegen** [comment] 2015-02-07 21:24
Thanks, mwjames and jongfeli, for your helpful comments! 

Two updates: 

Update 1: I vaguely recall now that I could not remove the page at the time. I just had another go at deleting it but after about a minute, the site gives up and chokes up an "Internal Server Error" message. When I try to blank the page, things get more specific: 

----------
A database query error has occurred. This may indicate a bug in the software.

    Query:
    UPDATE `o2a5_smw_object_ids` SET smw_sortkey = 'Orcuin Néill Noígiallaig' WHERE smw_id = '11636'
    Function: SMWSql3SmwIds::makeDatabaseId
    Error: 1205 Lock wait timeout exceeded; try restarting transaction (localhost
	
[and below:]

Notice: Uncommitted DB writes (transaction from DatabaseBase::query (WikiPage::pageData)). in /var/www/vhosts/vanhamel.nl/httpdocs/w/includes/db/Database.php on line 3944
----------

Update 2: To go by
http://www.vanhamel.nl/wiki/Special:Browse/Orcuin_N%C3%A9ill_No%C3%ADgiallaig
http://www.vanhamel.nl/w/index.php?title=Orcuin_N%C3%A9ill_No%C3%ADgiallaig&action=info 
older content long removed is still being recognised one way or another. 

> Why would a declared text property ...  

Using the tags <ref>...</ref> inside a value belonging to a property of type "Text" may still result in an error message together with an annotation for "Has improper value for". Those tags may have been used at some point in the history of this page. 

Also, the SIO 'alias' for subobjects has now been substituted for its SMW equivalent. Upgrading SMW would be a good idea regardless and I do hope to move ahead soon enough, although it's not exactly a trivial operation. 

Cheers,

Dennis

**Comment by mwjames** [comment] 2015-02-07 21:57
> Using the tags `<ref>...</ref>`

That's an issue, the parser tag `<ref>` cannot be unstrip by SMW (MW assigns an internal `UNIQ...` number, see als #232) because the content has been marked by the cite extension and by the time the SMW parser would be able to unstrip the content in only contains a [1] link.

**Comment by D-Groenewegen** [comment] 2015-06-26 10:37
An update. The site has been updated (new URL: http://www,vanhamel.nl/codecs)

The issue raised by this topic seems to have disappeared gradually, probably as a result of the upgrade. On the other hand, the "Data repair and upgrade" has been running for weeks but the process appears to be stuck at 7.2149%. I wonder if there's still an error in the database.

**Comment by mwjames** [comment] 2016-03-12 15:56
Closing this unless someone can replicate the issue on [0].

[0] http://sandbox.semantic-mediawiki.org

**Closed by mwjames** 2016-03-12 15:56 UTC
Labels: analysis, discussion
