### ISSUE TITLE
Special:SemanticMediaWiki small display error in German

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticMediaWiki#4258] opened 2019-08-22 10:12 UTC
### Setup and configuration

- SMW version:  3.0.2
- MW version: 	1.31.3
- PHP version: 7.1.8
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 	5.5.62-log

### Issue
There seems to be a small parsing error on Special:SemanticMediaWiki&action=duplookup
![grafik](https://user-images.githubusercontent.com/4318745/63506302-8af68280-c4d5-11e9-8977-bc3d6786b8ed.png)
The syntax "{{PLURAL:41|einen Eintrag|41 Einträge}}" is correct on a regular wiki page, but somehow it does not seem to get parsed on the special page.

The language is set on "de-formal" in the wiki.

### Steps to reproduce
for those who have access to 
https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:SemanticMediaWiki

**Comment by mwjames** [comment] 2019-08-22 10:30
> There seems to be a small parsing error on
> Special:SemanticMediaWiki&action=duplookup
> ![grafik](https://user-images.githubusercontent.com/4318745/63506302-8af68280-c4d5-11e9-8977-bc3d6786b8ed.png)
> The syntax "{{PLURAL:41|einen Eintrag|41 Einträge}}" is correct on a regular
> wiki page, but somehow it does not seem to get parsed on the special page.

The `duplookup` uses the API and JS to query duplicates in the
background and updates the page as it receives feedback from the
backend. Now as far as I remember, the JS component cannot resolve
messages with {{PLURAL... which is why the output looks distorted and
because of this I think I changed the approach of what is displayed in
3.1.

If you find the issue/PR please link to it.

**Comment by mwjames** [comment] 2019-08-22 10:40
> If you find the issue/PR please link to it.

I think it is #3718, if I remember correctly.

**Comment by mwjames** [comment] 2019-08-22 10:42
Actually, this issue is a duplicate of #3736.

**Comment by krabina** [comment] 2019-08-22 10:57
oops

**Closed** 2019-08-22 13:37 UTC
Labels: bug, duplicate
