### ISSUE TITLE
Incompatibility with Extension:Flow ?

### ISSUE THREAD

**Issue by simontaurus** [SemanticMediaWiki/SemanticMediaWiki#4954] opened 2021-03-20 03:11 UTC
I have encountered a strange problem within two independent Mediawiki installations. When the flow extension is enabled in LocalSettings.php before SMW, the parser functions of SMW are not registered when rebuildDate.php is called. This has the consequence that for example inline queries are misinterpreted as annotation. 
For example, for the page text 
`{{#ask: [[Has part.Has part::Some part]] }}`
an annotation error message 
`a property chain is not permitted during the annotation process`
occurs. If the page content is recreated by a "purge" via webinterface instead, everything works correctly. If the loading order of Flow and SWM is reversed (first SMW then Flow), everything also works correctly (also via rebuildData.php). 

Are there any known incompatibilities between the extensions or is this just a specific local problem?

Product | Version Wiki 1 | Version Wiki 2
-- | -- | --
MediaWiki | 1.31.6 | 1.31.12 (e3f6093) 16:13, 24 February 2021
PHP | 7.2.24-0ubuntu0.18.04.2 (fpm-fcgi)  | 7.1.33-34+ubuntu16.04.1+deb.sury.org+1 (apache2handler)
MySQL | 5.7.29-0ubuntu0.18.04.1 | 8.0.17
Semantic MediaWiki | 3.0.2 | 3.2.2
Flow | 1.1 (a6eab4d) 17:23, 25 July 2020 | 1.1 (e60a9b1) 12:35, 1 January 2021

**Comment by kghbln** [comment] 2021-03-22 17:25
@simontaurus Thanks for reporting this issue. You are the first one to report this incompatibility.

Unfortunately I have no workaround for you at hand. Also I do not expect that this will be fixed on the end of SMW even if it turns out that SMW is the cause. The simple reason is limited man power here and at the same time Flow being a legacy software for years already which wlll probably be abandoned in the near to middle future in favour of the [new discussion](https://www.mediawiki.org/wiki/Talk_pages_project/New_discussion) and [replying tool](https://www.mediawiki.org/wiki/Talk_pages_project/Replying) if I am not mistaken.

**Comment by simontaurus** [comment] 2021-03-23 19:40
Thank you for your reply. In fact, swapping the loading order is already a working workaround for me. However, the problem has cost me two days, which I wanted to prevent for others =)

**Comment by kghbln** [comment] 2021-03-24 09:00
> Thank you for your reply. In fact, swapping the loading order is already a working workaround for me. However, the problem has cost me two days, which I wanted to prevent for others =)

Ah right. There is a way out. Good that you pointed this out! I documented also on the [troubleshooting page](https://www.semantic-mediawiki.org/w/index.php?title=Help:Troubleshooting&diff=80523&oldid=70106)

**Closed by kghbln** 2021-03-24 09:00 UTC
Labels: question
