### ISSUE TITLE
Travis and `composer create-project ...` is broken

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMediaWiki#2629] opened 2017-08-19 07:50 UTC
`composer create-project` is broken [0]!

Updating to version 1.5.1 (stable channel) produces [1]:

```
cd /home/travis/build/SemanticMediaWiki/SemanticMediaWiki/../mw/extensions
composer create-project mediawiki/semantic-media-wiki SemanticMediaWiki dev-master -s dev --prefer-dist --no-dev

No composer.json in current directory, do you want to use the one at /home/travis/build/SemanticMediaWiki/mw? [Y,n]? 
```

refs https://github.com/composer/composer/issues/6617

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/265581327

**Comment by kghbln** [comment] 2017-08-26 14:36
Apart from that, Composer 1.5.2 is needed for better experience. Closing since there is nothing SMW can do to help the cause.

**Closed by kghbln** 2017-08-26 14:36 UTC
Labels: infrastructure
