### ISSUE TITLE
Show inline queries in the page history with data from the past

### ISSUE THREAD

**Issue by z0n** [SemanticMediaWiki/SemanticMediaWiki#2850] opened 2017-12-04 17:08 UTC
### Setup and configuration

- SMW version: 2.5.4
- MW version: 1.27.4
- PHP version:5.5.9-1ubuntu4.22 (apache2handler)
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 5.5.58-0ubuntu0.14.04.1

### Issue
This was reported as a bug from one of our wiki users but I think it might be more of a feature request.
When viewing the history of a wiki page which includes an inline query, the query returns the current data.
The expected result was that the query showed the data from the time the page was edited.

This can be seen as a bug or a feature request. I think it makes sense to add the possibility to view the inline query results as they were in the past as the data is basically there. I'm not sure how much computing power this would require though.

**Comment by kghbln** [comment] 2017-12-04 17:18
This is definitively a feature request and not a bug. I do not think that it will be possible to implement. A wiki is in general about current data so I believe that the data model has to be changed in a way allowing to query only for specific data of a given timestamp.

**Comment by kghbln** [comment] 2017-12-04 19:33
Thanks for you elaborate assessment and explanation building up on my first comment. Thus closing since this is not possible to implement.

**Closed by kghbln** 2017-12-04 19:33 UTC
Labels: enhancement
