### ISSUE TITLE
Is an empty property query possible in semantic media wiki? If not please make it possible.

### ISSUE THREAD

**Issue by WolfgangFahl** [SemanticMediaWiki/SemanticMediaWiki#1073] opened 2015-06-24 13:30 UTC
see http://stackoverflow.com/questions/31027987/is-an-empty-property-query-possible-in-semantic-media-wiki

**Comment by kghbln** [comment] 2015-06-25 18:33
I think this is a duplicate of https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/874

**Closed by kghbln** 2015-06-25 18:33 UTC
Labels: duplicate
