### ISSUE TITLE
Deprecated: Use of Linker::link with parameter $query as string in SMWInfolink::getText

### ISSUE THREAD

**Issue by nemobis** [SemanticMediaWiki/SemanticMediaWiki#2014] opened 2016-11-17 12:39 UTC
```
-rakkaus:#mediawiki-i18n- \nDeprecated: Use of Linker::link with parameter $query as string (should be array) was deprecated in MediaWiki 1.20. [Called from SMWInfolink::getText in /.../extensions/SemanticMediaWiki/includes/SMW_Infolink.php at line 251] in /.../includes/debug/MWDebug.php on line 311
```

SMW 2.4.2 https://translatewiki.net/wiki/Special:Version

**Comment by kghbln** [comment] 2016-11-17 14:11
I guess "Special:Version" is dynamic thus:

- MediaWiki 	1.29.0-alpha
- HHVM 	3.15.2 (srv)
- MariaDB 	5.5.52-MariaDB-1ubuntu0.14.04.1
- Semantic MediaWiki	2.4.2

**Comment by mwjames** [comment] 2016-11-19 02:10
> \nDeprecated: Use of Linker::link with parameter $query as string

Duplicate of #511.

I'd be happy to review a PR but since the deprecation is caused by MW and not by SMW and I only have marginal support window (which I'd like to spent on SMW and not on MW related issues) I cannot see myself working on this very soon.

**Comment by kghbln** [comment] 2016-11-19 12:48
Closing as duplicate

**Closed** 2016-11-22 16:50 UTC
Labels: bug, duplicate, mediawiki
