### ISSUE TITLE
Add "X" to close "This page supports semantic..." box

### ISSUE THREAD

**Issue by jidanni** [SemanticMediaWiki/SemanticMediaWiki#2543] opened 2017-07-11 01:58 UTC
https://wiki.osgeo.org/index.php?title=Taiwan_datums&action=edit there is your box
![m](https://user-images.githubusercontent.com/1230959/28047789-376539ac-661f-11e7-9e0d-9d66a81637ab.jpg)
that says "This page supports semantic in-text annotations..."
Alas it takes up valuable real estate on smaller monitors.
After the user reads it, he wishes to close it. But there is no "X" to do so.

**Comment by jidanni** [comment] 2017-07-11 02:01
https://wiki.osgeo.org/wiki/Special:Version says Semantic MediaWiki | 2.3.

**Comment by jaideraf** [comment] 2017-07-11 02:37
@jidanni you may want to set 

`$smwgEnabledEditPageHelp = false;`

to your `LocalSettings.php` configuration file. [1]

[1] https://www.semantic-mediawiki.org/wiki/Help:$smwgEnabledEditPageHelp

**Comment by jidanni** [comment] 2017-07-11 03:08
You misunderstand me.

I am saying on thousands of sites, thousands of users will be benefited
by having an X to close that box after they have read it.

I am not saying remove the box, not even for one site.

I am saying that box should have an X.

You could even have a dropdown menu, which could have
*"Close this message"
*"Don't show me this me this message ever again on this site" (via cookie?)

**Comment by kghbln** [comment] 2017-07-11 07:39
Thanks for your suggestion. This one is a bit tricky since not all namespaces are supporting annotations by default and they must not necessarily do so by individual configuration. Thus I see the option to dismiss this box on a per page basis as a valid enhancement while doing a "Do not show me ever again on this site" is basically better met with disabling this feature via the configuration setting provided.

**Comment by mwjames** [comment] 2017-07-11 14:57
> You could even have a dropdown menu,

Maybe, but that's too labour intensive from a development
point-of-view to justify such development and maintenance activity.

> *"Don't show me this me this message ever again on this site" (via cookie?)

Cookies are a no-go.

If you wanted to give it a user enable/disable spin, use the
`GetPreference` hook and add a checkbox to modify the display
characteristics in the `EditPageForm` hook.

As goody and for a daily 5 min. coding sprint practice:


```
@@ -335,10 +335,12 @@
 	"smw-paramdesc-category-template": "A template to format the items with",
 	"smw-paramdesc-category-userparam": "A parameter to pass to the template",
 	"smw-info-par-message": "Message to display.",
 	"smw-info-par-icon": "Icon to show, either \"info\" or \"warning\".",
 	"prefs-smw": "Semantic MediaWiki",
+	"prefs-general-options": "General options",
+	"smw-prefs-general-options-disable-editpage-info": "Disable edit
page information.",
 	"prefs-ask-options": "Semantic search options",
```
```
@@ -26,10 +26,15 @@ class GetPreferences {
 	 * @var array
 	 */
 	private $preferences;

 	/**
+	 * @var boolean
+	 */
+	private $enabledEditPageHelp = false;
+
+	/**
 	 * @since  2.0
 	 *
 	 * @param User $user
 	 * @param array $preferences
 	 */
@@ -37,10 +42,19 @@ class GetPreferences {
 		$this->user = $user;
 		$this->preferences =& $preferences;
 	}

 	/**
+	 * @since 3.0
+	 *
+	 * @param boolean $enabledEditPageHelp
+	 */
+	public function isEnabledEditPageHelp( $enabledEditPageHelp ) {
+		$this->enabledEditPageHelp = $enabledEditPageHelp;
+	}
+
+	/**
 	 * @since 2.0
 	 *
 	 * @return true
 	 */
 	public function process() {
@@ -56,10 +70,17 @@ class GetPreferences {
 				'section' => 'smw',
 				'raw' => 1,
 				'rawrow' => 1,
 			);

+		$this->preferences['smw-prefs-general-options-disable-editpage-info']
= array(
+			'type' => 'toggle',
+			'label-message' => 'smw-prefs-general-options-disable-editpage-info',
+			'section' => 'smw/general-options',
+			'disabled' => !$this->enabledEditPageHelp
+		);
+
```
```
@@ -403,17 +403,21 @@ class HookRegistry {
 		};

 		/**
 		 * @see https://www.mediawiki.org/wiki/Manual:Hooks/GetPreferences
 		 */
-		$this->handlers['GetPreferences'] = function ( $user, &$preferences ) {
+		$this->handlers['GetPreferences'] = function ( $user, &$preferences
) use( $applicationFactory ) {

 			$getPreferences = new GetPreferences(
 				$user,
 				$preferences
 			);

+			$getPreferences->isEnabledEditPageHelp(
+				$applicationFactory->getSettings()->get( 'smwgEnabledEditPageHelp' )
+			);
+
 			return $getPreferences->process();
 		};

 		/**
 		 * @see https://www.mediawiki.org/wiki/Manual:Hooks/SkinTemplateNavigation
@@ -528,10 +532,14 @@ class HookRegistry {

 			$editPageForm->isEnabledEditPageHelp(
 				$applicationFactory->getSettings()->get( 'smwgEnabledEditPageHelp' )
 			);

+			$editPageForm->isDisabledOnPreference(
+				$GLOBALS['wgUser']->getOption(
'smw-prefs-general-options-disable-editpage-info' )
+			);
+
 			return $editPageForm->process( $editPage );
```

PS: This is missing tests, so it won't get merged!

**Comment by jidanni** [comment] 2017-07-11 22:39
All this is fine, as long as users see some way to close the box. (An
"X" and/or the word "Close" which when clicked will give them
instructions and a link to their preferences.)

Also all this should be the default, so administrators don't have to
edit their Local_Settings.php to enable it or even know about it.

**Closed** 2017-07-23 05:44 UTC
Labels: enhancement

**Comment by kghbln** [comment] 2017-07-24 10:28
@mwjames Wow, thanks a lot! I believe we have now best flexibility in controlling the behaviour here. One thing: The general options section delivered with this is located at the bottom of the respective section on special page "Preference". Now it looks like it refers to SRF and not to SMW. Will it be possible to move this up to show before the SRF user preferences. Same for the search preferences choosable for SMW.

**Comment by mwjames** [comment] 2017-07-29 00:45
> Now it looks like it refers to SRF and not to SMW. Will it be possible to move this up to show before the SRF user preferences. Same for the search preferences choosable for SMW.

I've seen this but since this is caused by the internal sorting in [0]. I'm not going to spend time on that. One can maybe switch the order by manipulating `'section' => 'smw/general-options',`/`'section' => 'smw'` naming.

[0] https://www.mediawiki.org/wiki/Manual:Hooks/GetPreferences, `Preferences` class
