### ISSUE TITLE
DBLanguageError: Table name component contains unexpected quote or dot character

### ISSUE THREAD

**Issue by squirrelslair** [SemanticMediaWiki/SemanticMediaWiki#5663] opened 2024-07-11 13:59 UTC
Error When updating a wiki from MW 1.41.1  to 1.42.1 using "mediawiki/semantic-media-wiki": "dev-master" in composer.local.json. No error in old version.
## Issue
```
[Zo7A79ngLqZ-ud6oXyROAQAAAA8] /index.php?title=Main_Page Wikimedia\Rdbms\DBLanguageError: Table name component contains unexpected quote or dot character
```
## Backtrace:
```
from <hidden>/includes/libs/rdbms/platform/SQLPlatform.php(1051)
#0 <hidden>/includes/libs/rdbms/platform/SQLPlatform.php(991): Wikimedia\Rdbms\Platform\SQLPlatform->extractTableNameComponents(string)
#1 <hidden>/includes/libs/rdbms/platform/SQLPlatform.php(957): Wikimedia\Rdbms\Platform\SQLPlatform->qualifiedTableComponents(string)
#2 <hidden>/includes/libs/rdbms/platform/SQLPlatform.php(936): Wikimedia\Rdbms\Platform\SQLPlatform->tableName(string)
#3 <hidden>/includes/libs/rdbms/platform/SQLPlatform.php(837): Wikimedia\Rdbms\Platform\SQLPlatform->tableNameWithAlias(string, string)
#4 <hidden>/includes/libs/rdbms/platform/SQLPlatform.php(665): Wikimedia\Rdbms\Platform\SQLPlatform->tableNamesWithIndexClauseOrJOIN(array, array, array, array)
#5 <hidden>/includes/libs/rdbms/database/Database.php(3334): Wikimedia\Rdbms\Platform\SQLPlatform->selectSQLText(array, array, array, string, array, array)
#6 <hidden>/includes/libs/rdbms/database/DatabaseMySQL.php(730): Wikimedia\Rdbms\Database->selectSQLText(array, array, array, string, array, array)
#7 <hidden>/includes/libs/rdbms/database/Database.php(1342): Wikimedia\Rdbms\DatabaseMySQL->selectSQLText(array, array, array, string, array, array)
#8 <hidden>/includes/libs/rdbms/database/DBConnRef.php(119): Wikimedia\Rdbms\Database->select(array, array, array, string, array, array)
#9 <hidden>/includes/libs/rdbms/database/DBConnRef.php(351): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#10 <hidden>/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(246): Wikimedia\Rdbms\DBConnRef->select(array, array, array, string, array, array)
#11 <hidden>/extensions/SemanticMediaWiki/src/SQLStore/QueryDependency/DependencyLinksValidator.php(122): SMW\MediaWiki\Connection\Database->select(array, array, array, string, array, array)
#12 <hidden>/extensions/SemanticMediaWiki/src/DependencyValidator.php(128): SMW\SQLStore\QueryDependency\DependencyLinksValidator->hasArchaicDependencies(SMW\DIWikiPage)
#13 <hidden>/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/ArticleViewHeader.php(94): SMW\DependencyValidator->hasArchaicDependencies(SMW\DIWikiPage)
#14 <hidden>/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(706): SMW\MediaWiki\Hooks\ArticleViewHeader->process(Article, NULL, boolean)
#15 <hidden>/includes/HookContainer/HookContainer.php(159): SMW\MediaWiki\Hooks->onArticleViewHeader(Article, NULL, boolean)
#16 <hidden>/includes/HookContainer/HookRunner.php(859): MediaWiki\HookContainer\HookContainer->run(string, array)
#17 <hidden>/includes/page/Article.php(634): MediaWiki\HookContainer\HookRunner->onArticleViewHeader(Article, NULL, boolean)
#18 <hidden>/includes/page/Article.php(563): Article->generateContentOutput(MediaWiki\User\User, ParserOptions, integer, MediaWiki\Output\OutputPage, array)
#19 <hidden>/includes/actions/ViewAction.php(78): Article->view()
#20 <hidden>/includes/actions/ActionEntryPoint.php(733): ViewAction->show()
#21 <hidden>/includes/actions/ActionEntryPoint.php(510): MediaWiki\Actions\ActionEntryPoint->performAction(Article, MediaWiki\Title\Title)
#22 <hidden>/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#23 <hidden>/includes/MediaWikiEntryPoint.php(199): MediaWiki\Actions\ActionEntryPoint->execute()
#24 <hidden>/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#25 {main}
```

**Comment by jongfeli** [comment] 2024-07-12 08:16
Yesterday I also wanted to see how far I would be able to come with SMW on MW-1.42 (future LTS) but found the same problem. This, or similar issue was actually reported by @osnard back in May 2024. See: #5634

**Comment by kghbln** [comment] 2024-07-12 09:00
This is indeed the same or a variant of the mentioned issue. Thus closing this one as duplicate of #5634

**Closed by kghbln** 2024-07-12 09:00 UTC
Labels: bug
