### ISSUE TITLE
Not refreshing after attribute update

### ISSUE THREAD

**Issue by StefanKaifer74** [SemanticMediaWiki/SemanticMediaWiki#5286] opened 2022-07-29 13:26 UTC
### Setup

- SMW version: 4.0.2
- MW version: 1.35.7
- PHP version: 7.4.30 (fpm-fcgi)
- DB system: 10.6.8-MariaDB-1:10.6.8+maria~focal

### Issue

I've added a new poperty to an attribute. After that i've got this message on the attribute page:
_"This page is protected to prevent accidental data modification and can only be edited by users with the appropriate edit right"_
Of course, the user has smw-edit right!

On a site with the attribute is this message (ex. mark): "attribut is not in the list of allowed values for the "propertyname" property."

_php7.4 runJobs.php_, etc. not helps. Maybee a caching problem (I'm using APC).

Only a restart of PHP-FPM (_systemctl restart php7.4-fpm.service_) helps (after that has the message gone).

Further: https://www.mediawiki.org/wiki/Topic:Wnm5bsydehe70myo

**Comment by kghbln** [comment] 2022-07-29 14:39
This is a dupe of #4344 and a bit annoying. Over there some tricks are mentioned on how to get the page unlocked. Moreover, if your wiki is not a public one you could indeed set [configuration parameter `$smwgChangePropagationProtection`](https://www.semantic-mediawiki.org/wiki/Help:$smwgChangePropagationProtection) to `false`.

**Closed by kghbln** 2022-07-29 14:39 UTC
Labels: bug
