### ISSUE TITLE
Embeding Special:RunQuery on a page is generating an error

### ISSUE THREAD

**Issue by plegault3397** [SemanticMediaWiki/SemanticMediaWiki#3117] opened 2018-04-12 13:50 UTC
### Setup and configuration

- MediaWiki	1.30.0
- PHP	7.1.8 (apache2handler)
- Semantic MediaWiki	2.5.6
- Page Forms	4.3 (624f2a9) 18:20, 16 January 2018
- MySQL | 5.6.34-log

### Issue
When using `{{Special:RunQuery/query form name}}` in a page the embedded query form shows. When I select run query I get -
```
Internal error [Ws9lhIU9d0Fn9w7DXp@QtgAAAAc] 2018-04-12 13:56:23: Fatal exception of type "TypeError"
```
Debug information
```
[Ws5Q-Z3aU0dVxecP9WjFDAAAAAU] /index.php/LADR_Downloads_and_Statistics TypeError from line 46 of /app/mediawiki/extensions/SemanticMediaWiki/includes/formatters/MessageFormatter.php: Argument 1 passed to SMW\MessageFormatter::__construct() must be an instance of Language, instance of StubUserLang given, called in /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php on line 89
```

### Backtrace:
```
#0 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(89): SMW\MessageFormatter->__construct(StubUserLang)
#1 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(291): SMW\ParserFunctionFactory->newAskParserFunction(Parser)
#2 /app/mediawiki/includes/parser/Parser.php(3383): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string)
#3 /app/mediawiki/includes/parser/Parser.php(3106): Parser->callParserFunction(PPFrame_DOM, string, array)
#4 /app/mediawiki/includes/parser/Preprocessor_DOM.php(1229): Parser->braceSubstitution(array, PPFrame_DOM)
#5 /app/mediawiki/includes/parser/Parser.php(2921): PPFrame_DOM->expand(DOMElement, integer)
#6 /app/mediawiki/includes/parser/Parser.php(1277): Parser->replaceVariables(string)
#7 /app/mediawiki/includes/parser/Parser.php(451): Parser->internalParse(string)
#8 /app/mediawiki/includes/content/WikitextContent.php(329): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#9 /app/mediawiki/includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#10 /app/mediawiki/includes/poolcounter/PoolWorkArticleView.php(144): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#11 /app/mediawiki/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#12 /app/mediawiki/includes/page/Article.php(585): PoolCounterWork->execute()
#13 /app/mediawiki/includes/actions/ViewAction.php(68): Article->view()
#14 /app/mediawiki/includes/MediaWiki.php(499): ViewAction->show()
#15 /app/mediawiki/includes/MediaWiki.php(293): MediaWiki->performAction(Article, Title)
#16 /app/mediawiki/includes/MediaWiki.php(851): MediaWiki->performRequest()
#17 /app/mediawiki/includes/MediaWiki.php(523): MediaWiki->main()
#18 /app/mediawiki/index.php(43): MediaWiki->run()
#19 {main}
```

**Comment by plegault3397** [comment] 2018-04-12 14:00
- MediaWiki	1.30.0
- PHP	7.1.8 (apache2handler)
- Semantic MediaWiki	2.5.6
- Page Forms	4.3 (624f2a9) 18:20, 16 January 2018
- MySQL | 5.6.34-log
**Issue**
When using {{Special:RunQuery/query form name}} in a page the embedded query form shows. When I select run query I get -
`
Internal error
[Ws9lhIU9d0Fn9w7DXp@QtgAAAAc] 2018-04-12 13:56:23: Fatal exception of type "TypeError"
`
**Debug information**

```
[Ws5Q-Z3aU0dVxecP9WjFDAAAAAU] /index.php/LADR_Downloads_and_Statistics TypeError from line 46 of /app/mediawiki/extensions/SemanticMediaWiki/includes/formatters/MessageFormatter.php: Argument 1 passed to SMW\MessageFormatter::__construct() must be an instance of Language, instance of StubUserLang given, called in /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php on line 89

Backtrace:

#0 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(89): SMW\MessageFormatter->__construct(StubUserLang)
#1 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(291): SMW\ParserFunctionFactory->newAskParserFunction(Parser)
#2 /app/mediawiki/includes/parser/Parser.php(3383): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string)
#3 /app/mediawiki/includes/parser/Parser.php(3106): Parser->callParserFunction(PPFrame_DOM, string, array)
#4 /app/mediawiki/includes/parser/Preprocessor_DOM.php(1229): Parser->braceSubstitution(array, PPFrame_DOM)
#5 /app/mediawiki/includes/parser/Parser.php(2921): PPFrame_DOM->expand(DOMElement, integer)
#6 /app/mediawiki/includes/parser/Parser.php(1277): Parser->replaceVariables(string)
#7 /app/mediawiki/includes/parser/Parser.php(451): Parser->internalParse(string)
#8 /app/mediawiki/includes/content/WikitextContent.php(329): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#9 /app/mediawiki/includes/content/AbstractContent.php(516): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#10 /app/mediawiki/includes/poolcounter/PoolWorkArticleView.php(144): AbstractContent->getParserOutput(Title, integer, ParserOptions)
#11 /app/mediawiki/includes/poolcounter/PoolCounterWork.php(123): PoolWorkArticleView->doWork()
#12 /app/mediawiki/includes/page/Article.php(585): PoolCounterWork->execute()
#13 /app/mediawiki/includes/actions/ViewAction.php(68): Article->view()
#14 /app/mediawiki/includes/MediaWiki.php(499): ViewAction->show()
#15 /app/mediawiki/includes/MediaWiki.php(293): MediaWiki->performAction(Article, Title)
#16 /app/mediawiki/includes/MediaWiki.php(851): MediaWiki->performRequest()
#17 /app/mediawiki/includes/MediaWiki.php(523): MediaWiki->main()
#18 /app/mediawiki/index.php(43): MediaWiki->run()
#19 {main}
```

**Comment by kghbln** [comment] 2018-04-12 20:12
Did this start all of a sudden or did you change your setup, e.g. upgrade an extension like Page Forms or Semantic MediaWiki prior to starting to get this issue?

I tried to recreate the issue by adding `{{Special:RunQuery/BooksQuery}}` to a [page](https://sandbox.semantic-mediawiki.org/wiki/Issues/3117). So it seems that master of SWM does not longer cause the issue observed. However Page Forms is unable to translate the embedded syntax into a working URL since it claims that no query form was specified. I am not sure what may cause this though.

**Comment by mwjames** [comment] 2018-04-14 09:49
> #0 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(89): SMW\MessageFormatter->__construct(StubUserLang)
#1 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(291): SMW\ParserFunctionFactory->newAskParserFunction(Parser)


Well, of course this will not work when a process uses `StubUserLang` and we have a type hint that says `Language` which means we expect a `Language` object.

The type hint is the same for 2.5 [0] as for 3.0 [1] and works fine for any other process, the question is why is the parser invoked by PF doing that? Anyway, we may be able to work around this if we have a reproducible case. Locally, I cannot install PF on my instances therefore the issue needs to be happen on the sandbox so that when a hack (not a fix because there is nothing wrong with the `Language` type hint!) is available it can be tested on a pre/post examination.

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/formatters/MessageFormatter.php#L46
[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.5.x/includes/formatters/MessageFormatter.php#L46

**Comment by plegault3397** [comment] 2018-04-14 11:25
I upgraded MediaWiki from 1.28, to 1.30. is when I noticed it however it may have happened when I upgraded Semantic MediaWiki 2.5.6. I was getting a parser error on 1 page when running rebuildData before the upgrade. I only used the embed code on one page. I found it when one of the users reported it.

**Comment by kghbln** [comment] 2018-04-26 12:58
I just updated sandbox to revision 8d9c794 of Page Forms but the behaviour is unchanged to what I have noted in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3117#issuecomment-380929977

**Comment by jaideraf** [comment] 2018-05-06 18:09
@kghbln could you update Page Forms to `4.3.1 (a3c23fe)` on sandbox? Just to be sure your issue is still present.

**Comment by kghbln** [comment] 2018-05-07 06:59
@jaideraf The version I stated was just one commit behind 4.3.1 which only updated the version. So after doing the update the issue still appears. However it is no longer the issue described here originally but an new one which appears to be a new one for Page Forms itself.

**Comment by jaideraf** [comment] 2018-05-07 12:44
Thanks @kghbln. Your described issue is strange, because I also have `{{Special:RunQuery/Form}}` in a [page](http://wikincat.org/wiki/Wikincat) and it is working (with a different behaviour from previous PF versions - but it's another thing). I am using MW 1.30.0 and PF 4.3.1.

**Comment by mwjames** [comment] 2018-05-12 01:50
> Coming back to the original issue. Is it save to say that this one is fixed in SMW master? I guess so.
> #0 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(89): SMW\MessageFormatter->__construct(StubUserLang)
#1 /app/mediawiki/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(291): SMW\ParserFunctionFactory->newAskParserFunction(Parser)

As mentioned earlier in this thread, the interface for the function is the same for 2.5 [0] as it is for 3.0 [1] which also means that we haven't fixed anything between releases because there was nothing to fix.

Given that the reported stack trace cannot be reliably reproduced on the sandbox, I'm closing this issue as not reproducible. In case it can be reproduced (on the sandbox), feel free to reopen the issue. 

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.5.x/includes/formatters/MessageFormatter.php#L46-L47
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/formatters/MessageFormatter.php#L46-L47

**Closed by mwjames** 2018-05-12 01:50 UTC
Labels: bug
