### ISSUE TITLE
Fuzzy Matching Search for Semantic Data

### ISSUE THREAD

**Issue by d3mon187** [SemanticMediaWiki/SemanticMediaWiki#264] opened 2014-04-04 16:34 UTC
I have a site I'm working on with millions of pages of data (business listings).  Each listing has the business name, categories, location data, and keywords, all as semantic data.  I have a semantic search where a person can enter a "what" string (name, category, or keyword), and a "where" string (city, state, or zip).  The search of course needs to be forgiving (i.e. matching "restaurant" to "restaurants", and san antonio, tx to San Antonio, Texas). 

So far I've achieved this by creating semantic properties with strings like "italian; restaurants; olive garden" and "san antonio, tx 78211; san antonio, texas 78211", and then using an ask search like `{{#ask:[[SearchArea::~*{{lc:{{{Where|}}}}}*]][[SearchLocation::~*{{lc:{{{What|}}}}}*]]}}`.  It's fairly forgiving and works well, but after a few thousand records it becomes slow for obvious reasons when using the wildcard matching.  So I've come to the conclusion that I either need to split all words up, get rid of wilcards, and add things like "s" and "es" to the end of the user's search words, or get help with a better solution involving indexing or some other thing I  haven't thought of.

I'm sure I'm not the only one searching for a better semantic search solution, so hopefully someone can help me out.  I will also happily fund a solution if I can get some help quickly with this.  Thanks!

**Comment by mwjames** [comment] 2017-08-12 10:32
> Fuzzy Matching Search

Instead of fuzziness or "Fuzzy Matching Search", the issue is more about the support of case-insensitive matching which got addressed in:

> query to generate MATCH(t0.o_hash) AGAINST ('keyword' IN BOOLEAN MODE),

#1481

> I changed my smw_di_blob table to MyISAM, utf8_general_ci, and changed o_hash to

#2499

**Closed by mwjames** 2017-08-12 10:32 UTC
Labels: query, question
