### ISSUE TITLE
Warnings about DB_SLAVE not being defined

### ISSUE THREAD

**Issue by hexmode** [SemanticMediaWiki/SemanticMediaWiki#4100] opened 2019-06-22 16:39 UTC
### Setup and configuration

(Dupe of #4093?)

- SMW version: master
- MW version: master
- PHP version: 7.3.6-1+0\~20190531112735.39+stretch~1.gbp6131b7 
- DB system and version: Percona XtraDB Cluster: mysql  Ver 14.14 Distrib 5.7.25-28, for debian-linux-gnu (x86_64) using  7.0

### Issue
When running MediaWiki's `maintenance/install.php`, the following warning is printed:
```
PHP Warning:  Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP)
```

### Steps to reproduce
```
$ php maintenance/install.php  wiki adminp
PHP Warning:  Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /home/mah/work/code/mediawiki/core/extensions/SemanticMediaWiki/DefaultSettings.php on line 163
PHP Warning:  Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /home/mah/work/code/mediawiki/core/extensions/SemanticMediaWiki/DefaultSettings.php on line 167
You need to provide the option "pass" or "passfile"
```

**Comment by kghbln** [comment] 2019-06-24 18:35
Thanks for reporting and providing a patch. Yes, I also think this is a dupe of #4093. Thus closing this one in favour of the earlier one.

**Closed by kghbln** 2019-06-24 18:35 UTC
Labels: duplicate
