### ISSUE TITLE
PHP 7.4 compatibillity

### ISSUE THREAD

**Issue by akuckartz** [SemanticMediaWiki/SemanticMediaWiki#4547] opened 2020-02-15 08:33 UTC
Refs: #4549

This is a feature request.

**Comment by kghbln** [comment] 2020-02-15 11:15
This will come with SMW 3.2 in May. I guess no need to create a tracking issue for this. @mwjames

**Comment by mwjames** [comment] 2020-02-15 11:19
Let's keep it as extra ticket since this requires some effort and diligence.

**Comment by kghbln** [comment] 2020-02-15 11:23
> Let's keep it as extra ticket since this requires some effort and diligence.

Ok, fine with me.

**Comment by JeroenDeDauw** [comment] 2020-02-15 15:38
@akuckartz "Refs: #4547" is a self reference ;)

**Comment by kghbln** [comment] 2020-02-15 15:40
> Refs: #4547" is a self reference ;)

Actually this was me. Amended now.

**Comment by JeroenDeDauw** [comment] 2020-02-15 15:46
Nitpick mode: @kghbln this is either a feature/enhancement or a bug, not a code quality change

**Comment by JeroenDeDauw** [comment] 2020-02-15 15:47
Is https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4308 the only remaining known issue on PHP 7.4?

**Comment by kghbln** [comment] 2020-02-15 15:55
> Is #4308 the only remaining known issue on PHP 7.4?

Nobody knows since we currently do not test against PHP 7.4. Current tests already fail with PHP 7.3

**Comment by mwjames** [comment] 2020-02-15 16:02
> PHP 7.4. Current tests already fail with PHP 7.3

Incorrect, PHP 7.3 + MW master fails while other combinations in regards to PHP 7.3 do pass.

**Comment by kghbln** [comment] 2020-02-15 16:11
> Incorrect, PHP 7.3 + MW master fails while other combinations in regards to PHP 7.3 do pass.

Ah, indeed. I overlooked the test running against MW 1.33

**Comment by mwjames** [comment] 2020-02-16 13:33
Anyone could have just added PHP 7.4 as a non voting CI run to see what's missing! Aside from this technical aspect, users who want to see support for PHP 7.4 should have a look at [0] and start contributing to fix the failing tests otherwise support for PHP 7.4 is not guaranteed.

```
Using PHP 7.4.0

Semantic MediaWiki: 3.2.0-alpha, git: 835b2c7
                    SMWSQLStore (mysql:5.6.33-0ubuntu0.14.04.1)

MediaWiki:          1.35.0-alpha, git: 2e3bdb3 (refs/heads/master)
                    Extension vendor autoloader
Site language:      en

Execution time:     2020-02-16 01:21
Debug logs:         Disabled

Xdebug:             Disabled (or not installed)
Intl/ICU:           7.4.0 / 52.1

PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.0

...
Time: 4.88 minutes, Memory: 870.00 MB

There were 19 errors:
```

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/651097841

**Comment by mwjames** [comment] 2020-02-22 12:28
@kghbln #4584 tried fix those odd "Trying to access array offset on value of type ..." based on the tests where there were encountered but that doesn't guarantee that aren't any left.

As noted in #4584, MW 1.35 is still a mess and I don't have time to look into this.

**Comment by JeroenDeDauw** [comment] 2020-02-22 19:29
> 3) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "s-0027.json" ('/home/travis/build/SemanticMe...7.json')
> 
> implode(): Passing glue string after array is deprecated. Swap the parameters
> 
> /home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:306

@mwjames do you know where that library comes from?

**Comment by mwjames** [comment] 2020-02-23 02:19
>  /home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:306
> @mwjames do you know where that library comes from?

https://github.com/wikimedia/mediawiki/blob/master/composer.json#L63

**Comment by JeroenDeDauw** [comment] 2020-02-23 03:27
Oh no >_>

**Comment by mwjames** [comment] 2020-02-23 06:18
> Upstream patch: zordius/lightncandy#328

The problem seems to be https://github.com/zordius/lightncandy/issues/325.

**Comment by mwjames** [comment] 2020-03-07 10:08
@kghbln Again, another user (on the mailing list) complaining about "Trying to access array offset ..." which is likely to be caused by using a non supported PHP 7.4 environment but given the lack of information in the report itself, I'm stretching my arm here and make an assumption due to the specific error message.

**Comment by kghbln** [comment] 2020-03-08 19:13
It appears that PHP 7.4 still does not pass, however I seem to have triggered something with my comment yesterday. The now have a new hardcandy release supporting PHP 7.4, which is good.

**Comment by mwjames** [comment] 2020-03-08 19:45
> It appears that PHP 7.4 still does not pass,

It passes, the error(s) you seemed to refer to are caused by MW 1.35 / master as noted by the tickets I created.

**Comment by kghbln** [comment] 2020-03-08 21:29
> It passes, the error(s) you seemed to refer to are caused by MW 1.35 / master as noted by the tickets I created.

Ah, ok. I was thinking of adding a test environment for 1.34 together with PHP 7.4 however MW 1.34 does not claim to support PHP 7.4. Thus not doing it.

However, since SMW covers PHP 7.4 we can close this one I guess.

**Closed by kghbln** 2020-03-08 21:29 UTC
Labels: code quality
