### ISSUE TITLE
Maintenance script updateQueryDependencies.php error 1146

### ISSUE THREAD

**Issue by carlo66** [SemanticMediaWiki/SemanticMediaWiki#4423] opened 2020-01-15 15:01 UTC
### Setup and configuration

- SMW version: 3.1.2 (e00b175)
- MW version: 1.32.0
- PHP version: 7.2.18 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.2.22-MariaDB

### Issue
Trying to enable embedded query updates, maintenance script "updateQueryDependencies.php" fails with the error

Error: 1146 Table 'Wiki.smw_fpt_ask' doesn't exist (localhost)

(full output is reported below). The table is not found because the table prefix is not prepended to the table name. The problem is the check at line 2346 in file MW_INSTALL_PATH/includes/libs/rdbms/database/Database.php:
```
		if ( preg_match( '/(^|\s)(DISTINCT|JOIN|ON|AS)(\s|$)/i', $name ) !== 0 ) {
			$this->queryLogger->warning(
				__METHOD__ . ": use of subqueries is not supported this way.",
				[ 'trace' => ( new RuntimeException() )->getTraceAsString() ]
			);

			return $name;
		}
```
which matches for "smw_fpt_ask AS p".

A possible solution is modifying the updateQueryDependencies.php script at line 131 as:
```
		$res = $connection->select(
			[ SQLStore::ID_TABLE, $tableName ],
			[
				'smw_id',
				'smw_title',
				'smw_namespace'
			],
			[
				'smw_iw!=' . $connection->addQuotes( SMW_SQL3_SMWIW_OUTDATED ),
				'smw_iw!=' . $connection->addQuotes( SMW_SQL3_SMWDELETEIW ),
			],
			__METHOD__,
			[
				'GROUP BY' => 'smw_id'
			],
			[
				$tableName  => [ 'INNER JOIN', [ 's_id=smw_id' ] ],
			]
		);
```

### Stack trace
updateQueryDependencies.php output:

```
[bfa4f1db69e65b9e4b5fadbc] [no req]   RuntimeException from line 291 of /var/www/html/wiki_1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: SELECT  smw_id,smw_title,smw_namespace  FROM `wiki_smw_object_ids` INNER JOIN smw_fpt_ask AS p ON ((s_id=smw_id))   WHERE (smw_iw!=':smw') AND (smw_iw!=':smw-delete')  GROUP BY smw_id 
Function: SMW\Maintenance\UpdateQueryDependencies::runUpdate
Error: 1146 Table 'Wiki.smw_fpt_ask' doesn't exist (localhost)

#0 /var/www/html/wiki_1.32.0/includes/libs/rdbms/database/Database.php(1466): Wikimedia\Rdbms\Database->makeQueryException('Table 'Wiki.smw...', 1146, 'SELECT  smw_id,...', 'SMW\\Maintenance...')
#1 /var/www/html/wiki_1.32.0/includes/libs/rdbms/database/Database.php(1226): Wikimedia\Rdbms\Database->reportQueryError('Table 'Wiki.smw...', 1146, 'SELECT  smw_id,...', 'SMW\\Maintenance...', false)
#2 /var/www/html/wiki_1.32.0/includes/libs/rdbms/database/Database.php(1697): Wikimedia\Rdbms\Database->query('SELECT  smw_id,...', 'SMW\\Maintenance...')
#3 /var/www/html/wiki_1.32.0/includes/libs/rdbms/database/DBConnRef.php(53): Wikimedia\Rdbms\Database->select(Array, Array, Array, 'SMW\\Maintenance...', Array, Array)
#4 /var/www/html/wiki_1.32.0/includes/libs/rdbms/database/DBConnRef.php(269): Wikimedia\Rdbms\DBConnRef->__call('select', Array)
#5 /var/www/html/wiki_1.32.0/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(306): Wikimedia\Rdbms\DBConnRef->select(Array, Array, Array, 'SMW\\Maintenance...', Array, Array)
#6 /var/www/html/wiki_1.32.0/extensions/SemanticMediaWiki/maintenance/updateQueryDependencies.php(147): SMW\MediaWiki\Connection\Database->select(Array, Array, Array, 'SMW\\Maintenance...', Array, Array)
#7 /var/www/html/wiki_1.32.0/extensions/SemanticMediaWiki/maintenance/updateQueryDependencies.php(102): SMW\Maintenance\UpdateQueryDependencies->runUpdate()
#8 /var/www/html/wiki_1.32.0/maintenance/doMaintenance.php(94): SMW\Maintenance\UpdateQueryDependencies->execute()
#9 /var/www/html/wiki_1.32.0/extensions/SemanticMediaWiki/maintenance/updateQueryDependencies.php(186): require_once('/var/www/html/w...')
#10 {main}
Backtrace:
#0 /var/www/html/wiki_1.32.0/extensions/SemanticMediaWiki/maintenance/updateQueryDependencies.php(147): SMW\MediaWiki\Connection\Database->select(array, array, array, string, array, array)
#1 /var/www/html/wiki_1.32.0/extensions/SemanticMediaWiki/maintenance/updateQueryDependencies.php(102): SMW\Maintenance\UpdateQueryDependencies->runUpdate()
#2 /var/www/html/wiki_1.32.0/maintenance/doMaintenance.php(94): SMW\Maintenance\UpdateQueryDependencies->execute()
#3 /var/www/html/wiki_1.32.0/extensions/SemanticMediaWiki/maintenance/updateQueryDependencies.php(186): require_once(string)
#4 {main}
```

**Comment by kghbln** [comment] 2020-01-15 15:50
@carlo66 Thanks a lot for the elaborate report.

**Comment by mwjames** [comment] 2020-01-18 17:46
The SELECT array is configured as expected by the `Wikimedia\Rdbms\Database::select` as:

```
		$res = $connection->select(
			[ SQLStore::ID_TABLE, $tableName ],
			[
```

> The problem is the check at line 2346 in file MW_INSTALL_PATH/includes/libs/rdbms/database/Database.php:

As you said, `Database.php` doesn't add the prefix and I have no idea whether the issue is due to "MW version: 1.32.0" or not and fixed in a different release.

I don't have the time to dig around the MediaWiki code base to see whether this has been fixed already as it would require me to setup a wiki with a separate DB prefix.

My suggestion is to search in the WMF phab for any related issues, or to use a different MW release and try to replicate the issue.

**Comment by carlo66** [comment] 2020-02-05 16:39
> I have no idea whether the issue is due to "MW version: 1.32.0" or not and fixed in a different release.

I tried with MW 1.33.2 with the same result.

However, it seems to me the issue is related to an incorrect value for the $table parameter of `Database::select`. The second element should contain only the table name and not the alias specification (based on the comments in `Database::tableName`, which adds the table prefix and returns the quoted value). After searching the MediaWiki manuals for the correct way to use table alias, I think the select call in the script should be patched this way:

```
--- updateQueryDependencies.php-	2020-02-03 17:06:35.620215412 +0100
+++ updateQueryDependencies.php	2020-02-04 18:04:38.492428155 +0100
@@ -129,7 +129,7 @@
 		);
 
 		$res = $connection->select(
-			[ SQLStore::ID_TABLE, $tableName . ' AS p' ],
+			[ SQLStore::ID_TABLE, 'p' => $tableName ],
 			[
 				'smw_id',
 				'smw_title',
@@ -144,7 +144,7 @@
 				'GROUP BY' => 'smw_id'
 			],
 			[
-				$tableName . ' AS p' => [ 'INNER JOIN', [ 'p.s_id=smw_id' ] ],
+				'p' => [ 'INNER JOIN', [ 'p.s_id=smw_id' ] ],
 			]
 		);
```
which produces the query

```
SELECT  smw_id,smw_title,smw_namespace  FROM `wiki_smw_object_ids` INNER JOIN `wiki_smw_fpt_ask` `p` ON ((p.s_id=smw_id))   WHERE (smw_iw!=':smw') AND (smw_iw!=':smw-delete')  GROUP BY smw_id
```
which I think it's the expected result.

**Comment by mwjames** [comment] 2020-02-08 06:42
> which produces the query
> SELECT  smw_id,smw_title,smw_namespace  FROM `wiki_smw_object_ids` INNER JOIN `wiki_smw_fpt_ask` `p` ON ((p.s_id=smw_id))   WHERE (smw_iw!=':smw') AND (smw_iw!=':smw-delete')  GROUP BY smw_id
> which I think it's the expected result.

If you think this fixes the issue, please provide a PR so it can run through the test suite which also means I can focus on something else instead of everybody waiting on me to be an enabler.

**Comment by carlo66** [comment] 2020-02-10 09:08
OK, I'll do it, but since I'm new to git and github, please consider this might take some time.

**Comment by kghbln** [comment] 2020-02-10 09:49
> OK, I'll do it, but since I'm new to git and github, please consider this might take some time.

You can edit the code file via the browser without issues too. Probably easier as a short term solution than digging into git.

**Comment by carlo66** [comment] 2020-02-11 12:59
I hope the pull request has been created correctly.

**Closed** 2020-02-15 06:30 UTC
Labels: bug
