### ISSUE TITLE
Bug: Table name component contains unexpected quote or dot character

### ISSUE THREAD

**Issue by physikerwelt** [SemanticMediaWiki/SemanticMediaWiki#5672] opened 2024-07-19 05:51 UTC
### Setup

- SMW version: 4.2.0 (b651a74) 15:43, 18. Jul. 2024
- MW version:1.43.wmf9
- PHP version: PHP 8.1.29 (cli) (built: Jul  2 2024 04:12:19) (NTS)
- DB system (MySQL, Blazegraph, etc.) and version:Mysql 1:11.0.2+maria~ubu2204 (update.php was executed today)

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
[957f9fd478bb8e047d463fca] /index.php?title=Vorlage:Scriptnav Wikimedia\Rdbms\DBLanguageError: Table name component contains unexpected quote or dot character

Backtrace:

from /var/www/html/includes/libs/rdbms/platform/SQLPlatform.php(1150)
#0 /var/www/html/includes/libs/rdbms/platform/SQLPlatform.php(1090): Wikimedia\Rdbms\Platform\SQLPlatform->extractTableNameComponents(string)
#1 /var/www/html/includes/libs/rdbms/platform/SQLPlatform.php(1056): Wikimedia\Rdbms\Platform\SQLPlatform->qualifiedTableComponents(string)
#2 /var/www/html/includes/libs/rdbms/platform/SQLPlatform.php(1023): Wikimedia\Rdbms\Platform\SQLPlatform->tableName(string)
#3 /var/www/html/includes/libs/rdbms/platform/SQLPlatform.php(924): Wikimedia\Rdbms\Platform\SQLPlatform->tableNameWithAlias(string, string)
#4 /var/www/html/includes/libs/rdbms/platform/SQLPlatform.php(712): Wikimedia\Rdbms\Platform\SQLPlatform->tableNamesWithIndexClauseOrJOIN(array, array, array, array)
#5 /var/www/html/includes/libs/rdbms/database/Database.php(3285): Wikimedia\Rdbms\Platform\SQLPlatform->selectSQLText(array, string, string, string, array, array)
#6 /var/www/html/includes/libs/rdbms/database/DatabaseMySQL.php(652): Wikimedia\Rdbms\Database->selectSQLText(string, string, string, string, array, array)
#7 /var/www/html/includes/libs/rdbms/database/Database.php(1334): Wikimedia\Rdbms\DatabaseMySQL->selectSQLText(string, string, string, string, array, array)
#8 /var/www/html/includes/libs/rdbms/database/DBConnRef.php(126): Wikimedia\Rdbms\Database->select(string, string, string, string, array, array)
#9 /var/www/html/includes/libs/rdbms/database/DBConnRef.php(350): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#10 /var/www/html/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(247): Wikimedia\Rdbms\DBConnRef->select(string, string, string, string, array, array)
#11 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(414): SMW\MediaWiki\Connection\Database->select(string, string, string, string, array)
#12 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/QueryEngine/QueryEngine.php(225): SMW\SQLStore\QueryEngine\QueryEngine->getInstanceQueryResult(SMWQuery, integer)
#13 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(393): SMW\SQLStore\QueryEngine\QueryEngine->getQueryResult(SMWQuery)
#14 /var/www/html/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(381): SMW\SQLStore\SQLStore->fetchQueryResult(SMWQuery)
#15 /var/www/html/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(338): SMW\SQLStore\SQLStore->getQueryResult(SMWQuery)
#16 /var/www/html/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(367): SMWQueryProcessor::getResultFromQuery(SMWQuery, array, integer, integer)
#17 /var/www/html/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(202): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#18 /var/www/html/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(402): SMW\ParserFunctions\AskParserFunction->parse(array)
#19 /var/www/html/includes/parser/Parser.php(3464): SMW\ParserFunctionFactory->SMW\{closure}(MediaWiki\Parser\Parser, string)
#20 /var/www/html/includes/parser/Parser.php(3147): MediaWiki\Parser\Parser->callParserFunction(PPFrame_Hash, string, array)
#21 /var/www/html/includes/parser/PPFrame_Hash.php(275): MediaWiki\Parser\Parser->braceSubstitution(array, PPFrame_Hash)
#22 /var/www/html/includes/parser/Parser.php(2981): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#23 /var/www/html/includes/parser/Parser.php(1627): MediaWiki\Parser\Parser->replaceVariables(string)
#24 /var/www/html/includes/parser/Parser.php(729): MediaWiki\Parser\Parser->internalParse(string)
#25 /var/www/html/includes/content/WikitextContentHandler.php(377): MediaWiki\Parser\Parser->parse(string, MediaWiki\Title\Title, ParserOptions, boolean, boolean, integer)
#26 /var/www/html/includes/content/ContentHandler.php(1675): WikitextContentHandler->fillParserOutput(WikitextContent, MediaWiki\Content\Renderer\ContentParseParams, MediaWiki\Parser\ParserOutput)
#27 /var/www/html/includes/content/Renderer/ContentRenderer.php(67): ContentHandler->getParserOutput(WikitextContent, MediaWiki\Content\Renderer\ContentParseParams)
#28 /var/www/html/includes/Revision/RenderedRevision.php(260): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput(WikitextContent, MediaWiki\Title\Title, MediaWiki\Revision\RevisionStoreRecord, ParserOptions, boolean)
#29 /var/www/html/includes/Revision/RenderedRevision.php(232): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#30 /var/www/html/includes/Revision/RevisionRenderer.php(226): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string, array)
#31 /var/www/html/includes/Revision/RevisionRenderer.php(164): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, ParserOptions, array)
#32 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#33 /var/www/html/includes/Revision/RenderedRevision.php(199): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#34 /var/www/html/includes/poolcounter/PoolWorkArticleView.php(91): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#35 /var/www/html/includes/poolcounter/PoolWorkArticleViewCurrent.php(107): MediaWiki\PoolCounter\PoolWorkArticleView->renderRevision()
#36 /var/www/html/includes/poolcounter/PoolCounterWork.php(171): MediaWiki\PoolCounter\PoolWorkArticleViewCurrent->doWork()
#37 /var/www/html/includes/page/ParserOutputAccess.php(355): MediaWiki\PoolCounter\PoolCounterWork->execute()
#38 /var/www/html/includes/page/Article.php(762): MediaWiki\Page\ParserOutputAccess->getParserOutput(WikiPage, ParserOptions, MediaWiki\Revision\RevisionStoreRecord, integer)
#39 /var/www/html/includes/page/Article.php(564): Article->generateContentOutput(MediaWiki\User\User, ParserOptions, integer, MediaWiki\Output\OutputPage, array)
#40 /var/www/html/includes/actions/ViewAction.php(78): Article->view()
#41 /var/www/html/includes/actions/ActionEntryPoint.php(731): ViewAction->show()
#42 /var/www/html/includes/actions/ActionEntryPoint.php(508): MediaWiki\Actions\ActionEntryPoint->performAction(Article, MediaWiki\Title\Title)
#43 /var/www/html/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#44 /var/www/html/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#45 /var/www/html/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#46 {main}


```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
Go to https://wiki.physikerwelt.de/index.php?title=Vorlage:Scriptnav

**Comment by kghbln** [comment] 2024-07-19 08:07
Thank you for reporting. Duplicate of https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5634

**Closed by kghbln** 2024-07-19 08:07 UTC
Labels: bug
