### ISSUE TITLE
Use of templates in  #info: doesn't display properly inside tables

### ISSUE THREAD

**Issue by PeterBodifee** [SemanticMediaWiki/SemanticMediaWiki#2392] opened 2017-04-03 22:01 UTC
### Setup and configuration

- SMW version: 2.5.0
- MW version: 1.27.1
- PHP version: 5.5.38
- DB (MySQL etc.): 5.5.50-MariaDB

### Issue

When using parser function #info referring to a template inside a table the displayed output is incorrect. See attached screen shot. This worked fine in SMW 2.4.2
![screen shot 2017-04-03 at 23 18 22](https://cloud.githubusercontent.com/assets/26725260/24633528/4c6f261c-18c9-11e7-89a9-96df6e6e3890.jpg)

(unfortunately I am not receiving the email conformation for my requested account on https://sandbox.semantic-mediawiki.org so I can't reproduce the error there.

**Comment by kghbln** [comment] 2017-04-03 22:24
Thanks for reporting an issue. However it [works for me](https://sandbox.semantic-mediawiki.org/wiki/Issue/2392) as the example shows. The wiki is on MW 1.28 and MW 1.27 does not behave differently here. Perhaps some other extension is interfering here or "Help:InfoContext" contains something special which I cannot see from the screen shot. You could probably check your browsers error console for more info.

> (unfortunately I am not receiving the email conformation for my requested account on https://sandbox.semantic-mediawiki.org so I can't reproduce the error there.

This wiki uses ReCAPTCHA so there is no human approval process. You should be able to create an account without hindrance.

**Comment by kghbln** [comment] 2017-04-03 22:39
Well if there is a query on the page you are transcluding when you will get a "A fatal error occurred in the #info parser function" but this appears to be different from the worries you are experiencing. Also I am not sure if such a setup is actually supported. But again you issue is different.

**Comment by PeterBodifee** [comment] 2017-04-04 07:48
The issue with receiving the email confirmation from Sandbox is solved, it ended up in my spam folder at gmail. So I have now access to the Sandbox :-)

See https://sandbox.semantic-mediawiki.org/wiki/Parser_function_info_using_template_in_table

I also created the page in the help namespace (https://sandbox.semantic-mediawiki.org/wiki/Aide:InfoContext)

In my wiki when the template is empty, The label isn't overwritten. Please note the sandbox is running SMW 3.0.0-alpha, where as my wiki uses the released SMW 2.5.0.

See attached screenshots of referring to an existing and non-existing template.
![screen shot 2017-04-04 at 9 36 34](https://cloud.githubusercontent.com/assets/26725260/24645970/75d1628a-191a-11e7-94dc-79b3d0f3098e.jpg)
![screen shot 2017-04-04 at 9 36 55](https://cloud.githubusercontent.com/assets/26725260/24645973/7627d93a-191a-11e7-975e-b9fa74328d47.jpg)

I will try to find out if I have other extensions that may conflict here. 
Obviously it worked in my wiki using 2.4.2 and in the sandbox using 3.0.0-alpha and I believe it shouldn't be dependent on other extensions?

**Comment by PeterBodifee** [comment] 2017-04-04 07:55
I just did another test, as we have also the extension SimpleTooltip on our wiki, where parser function #tip-info provides a similar functionality and works as expected. To me this indicates that #info is broken.
![screen shot 2017-04-04 at 9 51 46](https://cloud.githubusercontent.com/assets/26725260/24646543/b24b0c46-191c-11e7-822a-c88c655b7aea.jpg)

**Comment by kghbln** [comment] 2017-04-04 08:10
I just tested successfully on smw.o which is running SMW 2.5.0 on a 1.27.1 It may however be that SimpleTooltip is the extension we were looking for that is interfering here. What happens if you pull SimpleTooltip from the wiki? What happens if yoiu place `#tip-info` below `#info`

In general I suggest to use either one or the other.

![bildschirmfoto vom 2017-04-04 10-04-45](https://cloud.githubusercontent.com/assets/1104078/24647032/729e298c-191e-11e7-935d-9589117a1753.png)

**Comment by mwjames** [comment] 2017-04-04 08:27
This may have been addressed with #2363 (we require to pre-process
content available in the title attribute).

PS: When creating content examples, please try to use content as close
as possible to the original observation (in most cases the detail of
that content reveals the true issue).

Cheers

**Comment by kghbln** [comment] 2017-04-04 08:33
> This may have been addressed with #2363 (we require to pre-process content available in the title attribute). 

@mwjames Thanks for the info.

@PeterBodifee Since this was already backported but not yet released with 2.5.1 you can already test with `"mediawiki/semantic-media-wiki": "2.5.x@dev"` in your "comploser.local.json" in case you are using Composer.

**Comment by PeterBodifee** [comment] 2017-04-04 08:59
@mwjames We use #info on all fields onall our Page Forms form pages, so for me this is a big thing. Initially reported the problem with PF (https://phabricator.wikimedia.org/T162071) , but @yaronkoren asked me to check if this behaviour of #info occurs outside a wiki table. Outside it doesn't, inside a wiki table it does (irrespective of table class).
I also removed the extension SimpleTooltip to see if it is interfering, but that doesn't make a difference.
Will try to get 2.5.1. installed and report back.

**Comment by PeterBodifee** [comment] 2017-04-04 14:16
Reading #2347 I tried the suggestion to put the #info call on the next line. That does solve my problem!
![screen shot 2017-04-04 at 16 14 10](https://cloud.githubusercontent.com/assets/26725260/24661201/0e65a916-1952-11e7-8c46-e981297bed88.jpg)

**Comment by PeterBodifee** [comment] 2017-04-04 21:14
@kghbln wrote

> This may indicate that there is something in you template causing this as I suggested before.

The template has pure plain text, not a single wiki construct. The content you see in the above screenshot is EXACTLY how it is in the template.

**Comment by kghbln** [comment] 2017-04-05 07:22
> The template has pure plain text, not a single wiki construct. The content you see in the above screenshot is EXACTLY how it is in the template.

Thanks for clarifying this. So I assume that the pull #2363 indeed addressed this issue successfully regardless of other tricks which may help the cause.

**Comment by PeterBodifee** [comment] 2017-04-07 10:26
Had version 2.5.0 (6ddb4c6) 1 apr 2017 15:02 installed and the problem is indeed gone. Thanks guys!

**Comment by kghbln** [comment] 2017-04-07 15:11
> Had version 2.5.0 (6ddb4c6) 1 apr 2017 15:02 installed and the problem is indeed gone. Thanks guys!

Thanks for reporting back on this. So SMW 2.5.1 will indeed bring the fix to this issue. Great.

**Closed by kghbln** 2017-04-07 15:11 UTC
Labels: question
