### ISSUE TITLE
Disabling entity issue panel

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMediaWiki#4674] opened 2020-03-28 15:17 UTC
Is there a way to disable the entity issue panel via wiki config?

![image](https://user-images.githubusercontent.com/146040/77826343-16d92880-710f-11ea-92d5-81e53054ef72.png)

Having it show, by default, on pages that do not have semantic annotations on them, does not seem like a good idea to me. For the same reasons listed here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4673#issue-589594461. Maybe having it on by default makes sense. Not sure. But on pages without semantic annotations? Uhhh.

User experience: install SMW. New things shows up on page. Complicated technical explanation. Why do I need to deal with this? What does it even mean. I'm not even using SMW yet. Maybe I should give this Cargo thing a try instead?

**Comment by kghbln** [comment] 2020-03-28 15:49
I agree that we should probably have an configuration parameter which allows to disable this for advanced users. 

However I do not think that it should be disabled by default. Admittedly I myself already had a couple of situation where this helped me identify structural issues fast and not by chance at a later stage or after a couple of people sent me e-mails about an issue. For me as an expert user this is actually an improvement.

> Having it show, by default, on pages that do not have semantic annotations on them, does not seem like a good idea to me.

Do not forget special property annotations so an extra logic would have to be added here which probably complicates things unnecessarily. For all the people who are sitting on SMW and do not want to use it the configuration parameter to enable/disable is good enough I guess.

**Comment by JeroenDeDauw** [comment] 2020-03-28 16:24
> disable this for advanced users

While I find the new UI element mildly annoying, my concern is about its effect on non-advanced users. Especially in parts of a wiki where SMW is not used, or where it is otherwise not relevant to the user.

That you like having it on by default suggests something about advanced users :) 

> special property annotations

Yeah. But that is technical stuff. This does not help new users that get confused. And it does not matter to admins that get put off from installing SMW because of usability issues.

**Comment by kghbln** [comment] 2020-03-28 16:31
> While I find the new UI element mildly annoying, my concern is about its effect on non-advanced users. Especially in parts of a wiki where SMW is not used, or where it is otherwise not relevant to the user.

I think that we agree on having a configuration parameter. If everything works the panel does not show up at all. If if does it is about constraint violations and stuff like that. This in turn is useful for novice users.

> Yeah. But that is technical stuff. This does not help new users that get confused. And it does not matter to admins that get put off from installing SMW because of usability issues.

In these cases you would want to use the configuration parameter.

**Comment by akuckartz** [comment] 2020-03-28 16:35
Maybe letting the user decide if he/she wants to see the panel is an alternative?

**Comment by kghbln** [comment] 2020-03-28 16:39
> Maybe letting the user decide if he/she wants to see the panel is an alternative?

Well, we could additionally have a UPO for this, indeed.

**Comment by JeroenDeDauw** [comment] 2020-03-28 21:42
> If everything works the panel does not show up at all.

Maybe true on some technical level... but not really. I have it show on pages where I do not use SMW. There simply is no issue on those. It does not matter that SMW is a revision behind, because whatever SMW is strong is not used anyway.

> useful for novice users.

For novice site admins doing SMW stuff, yes. But for "standard users", those that do not have deep knowledge of SMW and just add things via forms, I highly question the usefulness. They cannot fix the problem even if they understood it, which they don't. Some might argue those users should just learn SMW but I strongly disagree. I think that is not realistic nor economical for organizations.

**Comment by jaideraf** [comment] 2020-03-28 21:50
> However I do not think that it should be disabled by default. Admittedly I myself already had a couple of situation where this helped me identify structural issues fast...

I am with @kghbln here, I think if there is an SMW annotation (provided by users or not) on a page, the entity issue panel should be there. Almost the same reasons stated here https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4673#issuecomment-605522248.

**Comment by Ostrzyciel** [comment] 2020-04-02 13:36
As a sysadmin I can confirm that this feature can cause additional confusion among readers and editors. Not everyone needs to see this, it's a panel that uses very technical language and it's useful only to very few people. Also, it is an additional resource that needs to be loaded with every page.

I would suggest making it an UPO, then a sysadmin could disable it by default and only interested users would enable it.

**Comment by mwjames** [comment] 2020-04-02 13:49
> As a sysadmin I can confirm that this feature can cause additional confusion
> among readers and editors. Not everyone needs to see this, it's a panel that
> uses very technical language and it's useful only to very few people. Also,
> it is an additional resource that needs to be loaded with every page.
>
> I would suggest making it an UPO, then a sysadmin could disable it by
> default and only interested users would enable it.

I understand the view from those who made a sound argument (the
initial report failed to do that and was rather rude towards those
people who make a continues effort of improving the software) and is
the reason I internally conferred with Karsten on how to improve the
situation. He will surely make a proposal on what I see as a solution.

**Comment by akuckartz** [comment] 2020-04-02 17:03
> the initial report ... was rather rude towards those
people who make a continues effort of improving the software

I very much appreciate your efforts to improve SMW. But I do not think that the initial description of this issue was directed against these efforts.

**Comment by stefahn** [comment] 2021-11-18 15:08
+1 for making this an option that can be turned off. In my eyes it makes no sense to show this to anons.

Besides on our wiki I found that the icon https://www.semantic-mediawiki.org/w/images/5/50/Entity-issue-panel-running-deferred.png sometimes won't disappear - and since it's animated it somehow changes the height of the div and all page content is moving up and down all the time :-/
Could someone add a fixed height to the icon/div?

**Comment by malberts** [comment] 2022-12-07 09:20
My specific use case is having a somewhat aggressive caching policy where anonymous users shouldn't hit the server backend if Varnish/CDN serves everything else. Right now the (uncacheable) API call is making every cached page still hit the backend.

At the moment I am less concerned about UX for logged-in users, so my current basic requirement aligns with "just add UPO" (which I'll disable in my config). I'm also inclined to leave the current behavior (show by default) to avoid introducing "breaking" behavior.

I can have a look at this if adding just a UPO is fine. If we need more advanced magic (like checking if the page uses any properties), then let's add that later on top of the UPO.

**Comment by JeroenDeDauw** [comment] 2022-12-07 13:19
@malberts if you don't actually need to panel, you can get rid of it without introducing a breaking change, by adding a new config option that can be changed for your wiki, but retains the current behavior by default.

**Comment by krabina** [comment] 2023-03-24 17:54
I guess we can close this because it was implemented?

**Closed** 2023-03-25 07:51 UTC
Labels: UX
