### ISSUE TITLE
Support for user's timezone preference?

### ISSUE THREAD

**Issue by jamesmontalvo3** [SemanticMediaWiki/SemanticMediaWiki#2509] opened 2017-06-14 16:04 UTC
### Setup and configuration

- SMW version: 2.5.2
- MW version: 1.27.2
- PHP version: 5.6.30
- DB (MySQL etc.): 5.5.52-MariaDB

### Issue

Uploading an image (using Upload Wizard, but I don't think that's relevant) results in this history:

![image](https://user-images.githubusercontent.com/716482/27142420-93a3cfc4-50f0-11e7-903a-b5fee20b4edf.png)

But going to Special:Browse shows this:

![image](https://user-images.githubusercontent.com/716482/27142452-b07e6172-50f0-11e7-8cc6-cea9ce79c6c7.png)

The file page "history" section shows the time in my preferences-defined timezone (US Central). SMW property shows it in UTC. This is confusing for people using the "Modification date" property.

**Comment by kghbln** [comment] 2017-06-14 16:41
Thanks for reporting. Just to clarify the situation concerning the setup: Is the server set to UTC or the wiki or both?

**Comment by mwjames** [comment] 2017-06-16 10:21
>  my preferences-defined timezone (US Central). SMW property shows it in UTC. This is confusing for people using the "Modification date" property.

On the matter of storage and retrieval, the information is retrieved
from [0,1] and has been so since the very beginning therefore it is
not a bug with Page::getTimestamp returning the "MW timestamp of last
article revision".

On the matter of display and output characteristics, local (user)
preferences are currently not supported (I think I noted that on
another ticket recently) and it would require some rework of how dates
are to be displayed if a user chooses a preference.

I have a PR (is a bit dated though) that addresses the display issue
to a larger extend but it is missing unit and integration tests, and
I'm not currently not invested to improve the PR but if someone wants
to write the missing part as required, I will gladly share it. (PS:
...and yes, tests are required otherwise it won't get merged!)

- Unit test on methods that have been altered
- Unit test on new classes
- Integration test to verify that LOCL#TO works

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/PropertyAnnotators/PredefinedPropertyAnnotator.php#L88-L89

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/MediaWiki/PageInfoProvider.php#L56-L58

**Comment by kghbln** [comment] 2017-06-16 10:50
> I think I noted that on another ticket recently

I guess it is this issue: https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/205

**Comment by jamesmontalvo3** [comment] 2017-06-16 13:36
@kghbln server and wiki are `America/Chicago`:

Server:
```
$ timedatectl
      Local time: Fri 2017-06-16 08:24:27 CDT
  Universal time: Fri 2017-06-16 13:24:27 UTC
        RTC time: Fri 2017-06-16 13:24:25
       Time zone: America/Chicago (CDT, -0500)
     NTP enabled: yes
NTP synchronized: no
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  Sun 2017-03-12 01:59:59 CST
                  Sun 2017-03-12 03:00:00 CDT
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  Sun 2017-11-05 01:59:59 CDT
                  Sun 2017-11-05 01:00:00 CST
```

LocalSettings.php:
```php
$wgLocaltimezone = "America/Chicago";
```

@mwjames or @kghbln: Is there any way within an ask query to apply an offset? I don't think there is, just wondering if this has been considered. Perhaps this is related to the PR you mentioned, @mwjames? Which PR is that?

**Comment by kghbln** [comment] 2017-06-16 17:23
@jamesmontalvo3 Thanks for the additional info.

> Is there any way within an ask query to apply an offset?

No. You could probably somehow add the offset to the values stored via the template used by utilizing the `#timel` parser function. This however gets ugly twice a year because of daylight savings.

**Comment by mwjames** [comment] 2017-06-17 09:49
>  @mwjames? Which PR is that?

#2515 and as noted the PR is without tests, so it won't get merged,

> $wgLocaltimezone = "America/Chicago";

`LocalTime.php` contains most of the magic which is mostly user based, not sure how this plays with `$wgLocaltimezone`.

**Comment by gesinn-it** [comment] 2017-06-29 10:00
just for the record:

`$wgLocaltimezone = "Europe/Berlin";`

`[[Start Date Time::2017-08-01 10:00 +0400]]` formatted with `#-F[Y-m-d H:i:s O]` returns `2017-08-01 10:00:00 +0200` instead of either `2017-08-01 10:00:00 +0400` or `2017-08-01 8:00:00 +0200`

`$wgLocaltimezone = "UTC";`

`[[Start Date Time::2017-08-01 10:00 +0400]]` formatted with `#-F[Y-m-d H:i:s O]` returns `2017-08-01 10:00:00 +0000` instead of either `2017-08-01 10:00:00 +0400` or `2017-08-01 6:00:00 +0000`

We'll have a look @mwjames PR...

**Comment by gesinn-it** [comment] 2017-06-29 13:37
... uuh what a mistake, my above annotation is an incorrect date time string: the offset is treated as milliseconds ...

Should be `[[Start Date Time::2017-08-01T10:00:00+04:00]]`

**Comment by mwjames** [comment] 2017-07-29 06:46
The sandbox contains the implementation that was part of #2515 and allows to display local times according to a user setting and is indicated by `ᴸ` to distinguish it from the ISO or any other system related date display. 

![image](https://user-images.githubusercontent.com/1245473/28742816-f591e340-7474-11e7-9bda-7bdb9314e98a.png)

**Closed** 2017-07-29 06:46 UTC
Labels: feature
