### ISSUE TITLE
Debug log spam: "this connection was not opened as a foreign "

### ISSUE THREAD

**Issue by Nikerabbit** [SemanticMediaWiki/SemanticMediaWiki#947] opened 2015-03-30 12:56 UTC
While I was investigating another issue, I noticed I get a lot (read: thousands) of repeated messages like this in the debug log:

```
107.8440 1145.0M  LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
107.8441 1145.0M  LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
107.8443 1145.0M  LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
107.8444 1145.2M  LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
107.8446 1145.2M  LoadBalancer::reuseConnection: this connection was not opened as a foreign connection
```

It might be caused by the following code:
```php
includes/src/MediaWiki/LazyDBConnectionProvider.php
79:                     wfGetLB( $this->wiki )->reuseConnection( $this->connection );
```

This looks like incorrect use of reuseConnection and apart from printing the warning it does nothing.

Observed on 2.0.

**Comment by mwjames** [comment] 2015-03-30 18:10
It is using the same implementation as in [0] and I'd say it would cause the same issue for users of `WikibaseDatabase`. If someone wants to investigate, please feel free or point to a more correct use of `reuseConnection` (I don't have time for this).

> This looks like incorrect use of reuseConnection and apart from printing the warning it does nothing.

Yes, it is only used to satisfy the interface `DBConnectionProvider::releaseConnection` (I don't think that the production code ever executes `releaseConnection` or for that matter `reuseConnection`).

Unless someone has a suggestion on how to improve the `reuseConnection` usage, I'm inclined to close this issue.

[0] https://github.com/wmde/WikibaseDatabase/blob/a93e6da285ac77b87b5b4498a40b9e63211e76a8/src/MediaWiki/LazyDBConnectionProvider.php#L79

**Comment by mwjames** [comment] 2015-03-30 18:32
> I don't think that the production code ever executes releaseConnection or for that matter reuseConnection

It would help if you could find out who (or better which class) and where `reuseConnection` is being executed.

**Comment by JeroenDeDauw** [comment] 2015-03-31 03:40
@mwjames This part of WikibaseDatabase was never extensively tested. It has some integration tests for this code, though these presumably do not catch the reported issue.

@Nikerabbit if you can tell this usage is incorrect, can you also tell what it should probably be?

**Comment by Nikerabbit** [comment] 2015-03-31 05:53
As I said, it currently does nothing but print a warning and still works I believe, so I think it can be dropped. I have not verified whether it re-uses existing connections or not (which I believe it was trying to do), so it might need a second fix to achieve that.

**Comment by mwjames** [comment] 2015-04-13 07:12
> As I said, it currently does nothing but print a warning and still works I believe, so I think it can be dropped.

The log comes from MW's DatabaseBase/Loadbalancer class. SMW does not sent any logs therefore we can't drop them.

**Comment by Nikerabbit** [comment] 2015-04-13 07:15
To clarify, I meant the call to resuseConnection in
```
includes/src/MediaWiki/LazyDBConnectionProvider.php
79:                     wfGetLB( $this->wiki )->reuseConnection( $this->connection );
```

**Comment by mwjames** [comment] 2015-04-13 07:21
Unless someone can explain why `wfGetLB( $this->wiki )->reuseConnection( $this->connection );` can't be used or why the usage of above throws a `LoadBalancer::reuseConnection: this connection was not opened as a foreign connection`, I'm not easily convinced that this is the best course of action to solve an underlying issue (because this hasn't be answered yet).

**Comment by JeroenDeDauw** [comment] 2015-04-19 22:26
@Nikerabbit perhaps a pull request is the easiest way to convey what you want to change?

**Comment by Nikerabbit** [comment] 2015-04-20 06:18
That will be unlikely. I have more pressings things to work on than one line pull requests which are unlikely to get merged. I will provide backtrace when I get one.

**Comment by mwjames** [comment] 2015-04-20 08:09
> That will be unlikely. I have more pressings things to work on than one line pull requests 

I think we can all agree on that anyone has more pressing things to do and fixing a symptom not knowing whether it fixes the cause isn't going to fix anything.

I took my 5 min. morning break to have a look at `LoadBalancer::reuseConnection` to see who is emitting those (I could't find any caller that emits it directly from SMW) instead what I saw is that when an update [0] is initiated, `HTMLCacheUpdate`  (`HTMLCacheUpdateJob::run` -> `LBFactorySimple::forEachLB` ... ) [1] is called and in the event of `DatabaseBase::onTransactionIdle` [1] throws a:

```
		if ( $serverIndex === null || $refCount === null ) {
			var_dump( wfGetCaller( 8 ) );
			wfDebug( __METHOD__ . ": this connection was not opened as a foreign connection\n" );

			/**
			 * This can happen in code like:
			 *   foreach ( $dbs as $db ) {
			 *     $conn = $lb->getConnection( DB_SLAVE, array(), $db );
			 *     ...
			 *     $lb->reuseConnection( $conn );
			 *   }
			 * When a connection to the local DB is opened in this way, reuseConnection()
			 * should be ignored
			 */

			return;
		}
```
So removing the suggested line above will unlikely stop the log messages (as I said earlier we don't actively use `reuseConnection` in production, we only use it in tests) because the execution happens outside of the vicinity of SMW (based on my quick hack).

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SMW_Store.php#L221

[1] https://github.com/wikimedia/mediawiki/blob/4834574f631fba4d468183701a198d995b71ce86/includes/deferred/HTMLCacheUpdate.php#L62

**Comment by mwjames** [comment] 2015-04-23 13:57
I just got a chance to fetch a stack for the `HTMLCacheUpdateJob` execution, you can see that `JobQueueDB.php:205` calls `onTransactionIdle` [0] which actually throws the message.

```
4	119.7481	22561064	LBFactory->commitMasterChanges( )	..\MediaWiki.php:591
5	119.7481	22561144	LBFactory->forEachLBCallMethod( )	..\LBFactory.php:192
6	119.7481	22561728	LBFactorySimple->forEachLB( )	..\LBFactory.php:175
7	119.7482	22562072	call_user_func_array ( )	..\LBFactory.php:329
8	119.7484	22562096	LBFactory->callMethod( )	..\LBFactory.php:329
9	119.7484	22562360	call_user_func_array ( )	..\LBFactory.php:185
10	119.7485	22562456	LoadBalancer->commitMasterChanges( )	..\LBFactory.php:185
11	119.7489	22562704	DatabaseBase->commit( )	..\LoadBalancer.php:952
12	119.7789	22562976	DatabaseBase->runOnTransactionIdleCallbacks( )	..\Database.php:3585
13	119.8026	22563448	call_user_func ( )	..\Database.php:3354
14	119.8026	22563448	HTMLCacheUpdate->{closure:...\includes\deferred\HTMLCacheUpdate.php:63-65}( )	..\Database.php:3354
15	119.8026	22563464	HTMLCacheUpdateJob->run( )	..\HTMLCacheUpdate.php:64
16	119.8664	22640560	JobQueueGroup->push( )	..\HTMLCacheUpdateJob.php:69
17	119.9322	22875656	JobQueue->push( )	..\JobQueueGroup.php:127
18	119.9323	22875712	JobQueue->batchPush( )	..\JobQueue.php:311
19	119.9328	22875840	JobQueueDB->doBatchPush( )	..\JobQueue.php:340
20	119.9351	22877248	onTransactionIdle ( )	..\JobQueueDB.php:205
21	119.9351	22877448	DBConnRef->__call( )	..\JobQueueDB.php:205
22	119.9351	22877760	call_user_func_array ( )	..\LoadBalancer.php:1216
23	119.9352	22877944	DatabaseBase->onTransactionIdle( )	..\LoadBalancer.php:1216
24	119.9359	22878312	DatabaseBase->runOnTransactionIdleCallbacks( )	..\Database.php:3315
25	119.9362	22878488	call_user_func ( )	..\Database.php:3354
26	119.9362	22878488	JobQueueDB->{closure:...\includes\jobqueue\JobQueueDB.php:202-204}( )	..\Database.php:3354
27	119.9362	22878504	JobQueueDB->doBatchPushInternal( )	..\JobQueueDB.php:203
28	119.9697	22881320	insert ( )	..\JobQueueDB.php:257
29	119.9697	22881616	DBConnRef->__call( )	..\JobQueueDB.php:257
```

[0] https://github.com/wikimedia/mediawiki/blob/787f2dfc36724eaafeb984a490f7d9e7f5aacb0d/includes/jobqueue/JobQueueDB.php#L201

**Comment by mwjames** [comment] 2015-04-23 14:01
Given the information above with evidence that SMW isn't directly causing the log (well we call `HTMLCacheUpdate` but eventually `JobQueueDB::doBatchPush` is causing the log when executing `onTransactionIdle`), I'm closing this issue.

**Closed by mwjames** 2015-04-23 14:01 UTC

**Comment by Nikerabbit** [comment] 2015-04-23 14:21
Thanks for debugging. I will report this against MediaWiki.
