### ISSUE TITLE
Adjust for Wikimedia\Services move

### ISSUE THREAD

**Issue by lucaswerkmeister** [SemanticMediaWiki/SemanticMediaWiki#3554] opened 2018-12-14 19:54 UTC
### Setup and configuration

None, this is a notification about an upcoming MediaWiki change.

### Issue

In [T211608](https://phabricator.wikimedia.org/T211608 "Move includes/services/ into includes/libs/"), we’re extracting MediaWiki’s services framework into a separate library, which involves renaming the namespace from `MediaWiki\Services` to `Wikimedia\Services`. Semantic MediaWiki currently refers to the old name in a handful of comments (which could be changed to just the basename, I think), and in one code location, `src/Site.php`:

```php
	// MediaWiki\Services\ServiceDisabledException from line 340 of
	// ...\ServiceContainer.php: Service disabled: DBLoadBalancer
	try {
		$isReadOnly = wfReadOnly();
	} catch( \MediaWiki\Services\ServiceDisabledException $e ) {
		$isReadOnly = true;
	}
```

This code was originally introduced in #2434 to address #2432, hence CCing @mwjames and @kghbln.

I’m not sure what should be done to address this, but I don’t think simply updating the import is the best solution. If I understand #2432 correctly, this code was originally added because a `ServiceDisabledException` was encountered when attempting to run part of SMW on a MediaWiki where the installation was not yet completed. I don’t think catching a `ServiceDisabledException` is the right thing to do here: in such a situation (very unusual IMHO), that is not the only exception that could be encountered. I think it would be about equally reasonable, for example, for MediaWiki to throw some kind of `DBError`, or even a generic `MWException`. So perhaps that line of code should be changed to catch almost any kind of exception (and assume the wiki is read-only, or at least not ready to be written to)?

**Comment by kghbln** [comment] 2018-12-15 20:16
@lucaswerkmeister Thanks a lot for notifying.

> None, this is a notification about an upcoming MediaWiki change.

Since this is upcoming we are most probably talking about MW 1.33 and later.

**Comment by mwjames** [comment] 2019-01-06 02:12
>SMW is compatible with, sorry. 

I think we keep a fairly prominent file [0] containing all the information on past and planned releases.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

> In T211608, we’re extracting MediaWiki’s services framework into a separate library, which involves renaming the namespace from MediaWiki\Services to Wikimedia\Services

As long as you keep the aliases for at least two LTS releases I don't see an issue for switching SMW to those namespaces on the next occasion we change to a LTS that includes these changes as minimum.

> Also, at this point it’s not yet clear how long we’ll keep class_aliases for the old namespace around.

Since aliases are cheap, please make sure to recognize that people have different release plans other than to just rely on MW master. On the contrast, volunteer time is not cheap therefore changing should be done in a concerted effort to minimize the impact for the extension and its developers.

Adding @mwstake as like to see that such efforts are coordinated and not just push towards the end of extension developers.

**Comment by mwjames** [comment] 2019-01-06 02:35
As for:

> If I understand #2432 correctly, this code was originally added because a ServiceDisabledException was encountered when attempting to run part of SMW on a MediaWiki where the installation was not yet completed. I don’t think catching a ServiceDisabledException is the right thing to do here: 

In the past I made different attempts on phab in regards to the root cause but I got no sufficient answer and ultimately selected a solution that has proven to be stable. Reason to use `$isReadOnly = wfReadOnly();` is because accessing `Title->getRestrictionTypes()` -> `Title->getArticleID` will trigger a DB request without checking that it can actually make such request. 

```
#1 /var/www/w/includes/GlobalFunctions.php(3089): MediaWiki\MediaWikiServices->getDBLoadBalancer()
#2 /var/www/w/includes/GlobalFunctions.php(3075): wfGetLB(boolean)
#3 /var/www/w/includes/cache/LinkCache.php(267): wfGetDB(integer)
#4 /var/www/w/includes/Title.php(3222): LinkCache->addLinkObj(Title)
#5 /var/www/w/includes/Title.php(4295): Title->getArticleID(integer)
#6 /var/www/w/includes/Title.php(2572): Title->exists()
#7 /var/www/w/includes/Title.php(2687): Title->getRestrictionTypes()
```

**Comment by JeroenDeDauw** [comment] 2019-08-11 00:55
As I understand this there is some compatibility alias that we can continue using for some time. And using the new version would break our own compatibility requirements. So... there is nothing to do on the SMW side till we drop compat with MW 1.33? If so, this should not be under the 3.1 milestone.

**Comment by mwjames** [comment] 2019-08-11 01:07
> the SMW side till we drop compat with MW 1.33? If so, this should not be under the 3.1 milestone.

Only after the next MW LTS release which I think is 1.35 are we able to break compat until then we require 1.31 as minimum MW release.

**Comment by JeroenDeDauw** [comment] 2019-08-11 01:11
Alright, lets close this issue then.

**Closed by JeroenDeDauw** 2019-08-11 01:11 UTC
Labels: bug, mediawiki

**Comment by kghbln** [comment] 2019-08-11 11:28
> Alright, lets close this issue then.

From reading this I get the impression that this is still relevant for the future. On the other hand this may be more of a tracking issue which will be accompanied by individual issues still to be created addressing the respective service items.
