### ISSUE TITLE
Mediawiki 1.3.6 and Semantic Mediawiki 3.2.3

### ISSUE THREAD

**Issue by fw25** [SemanticMediaWiki/SemanticMediaWiki#5005] opened 2021-06-11 08:42 UTC
During the install the following errors occur (see below) when starting the website.
The errors occur only when i install Semantic Mediawiki 3.2.3

Deprecated: Premature access to service container [Called from Hooks::run in /Volumes/Dm1 Data/MAMP/hglsw/includes/Hooks.php at line 135] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated: Premature access to service 'HookContainer' [Called from MediaWiki\MediaWikiServices::getInstance in /Volumes/Dm1 Data/MAMP/hglsw/includes/MediaWikiServices.php at line 252] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated: Premature access to service 'ObjectFactory' [Called from Wikimedia\Services\ServiceContainer::{closure} in /Volumes/Dm1 Data/MAMP/hglsw/includes/ServiceWiring.php at line 535] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated: Premature access to service 'StatsdDataFactory' [Called from ObjectCache::newFromParams in /Volumes/Dm1 Data/MAMP/hglsw/includes/objectcache/ObjectCache.php at line 149] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated: Premature access to service 'MainConfig' [Called from Wikimedia\Services\ServiceContainer::{closure} in /Volumes/Dm1 Data/MAMP/hglsw/includes/ServiceWiring.php at line 1424] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated: Premature access to service 'ConfigFactory' [Called from Wikimedia\Services\ServiceContainer::{closure} in /Volumes/Dm1 Data/MAMP/hglsw/includes/ServiceWiring.php at line 734] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated: Premature access to service 'BootstrapConfig' [Called from Wikimedia\Services\ServiceContainer::{closure} in /Volumes/Dm1 Data/MAMP/hglsw/includes/ServiceWiring.php at line 277] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated: Premature access to service 'DBLoadBalancer' [Called from ObjectCache::{closure} in /Volumes/Dm1 Data/MAMP/hglsw/includes/objectcache/ObjectCache.php at line 181] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated: Premature access to service 'DBLoadBalancerFactory' [Called from Wikimedia\Services\ServiceContainer::{closure} in /Volumes/Dm1 Data/MAMP/hglsw/includes/ServiceWiring.php at line 383] in /Volumes/Dm1 Data/MAMP/hglsw/includes/debug/MWDebug.php on line 376

Deprecated

**Comment by Nikerabbit** [comment] 2021-06-11 11:26
This is duplicate of https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5001.

**Closed** 2021-06-13 09:40 UTC
Labels: bug, duplicate
