### ISSUE TITLE
"mb_strtolower(): Unknown encoding" after enabling Full-text search

### ISSUE THREAD

**Issue by D-Groenewegen** [SemanticMediaWiki/SemanticMediaWiki#3060] opened 2018-03-16 07:06 UTC
Posting this here now but I'll be looking for more details as soon as I can get them. 

### Setup and configuration
- Semantic MediaWiki 2.5.5
- MediaWiki 1.28.2
- PHP 7.0.28 (cgi-fcgi)
- MariaDB 10.0.32-MariaDB-0+deb8u1
- ICU 52.1

### Issue
To enable full-text search (which I know is experimentally supported), I followed the instructions over at https://www.semantic-mediawiki.org/wiki/Help:Full-text_search/Indexing. 
- Enabled $smwgEnabledFulltextSearch  
- Ran [...]/extensions/SemanticMediaWiki/maintenance/rebuildFulltextSearchTable.php without additional parameters, just the once (not yet on a daily basis)
- (SMW_FIELDT_CHAR_NOCASE is not enabled)

The TextSanitizer seems to run into some trouble, however. The following error message occurred a number of times:
```
PHP Warning:  mb_strtolower(): Unknown encoding "" in [...]/vendor/onoi/tesa/src/Normalizer.php on line 72
```
Full-text search does seem to work most of the time, but imperfectly: it does not always return what you'd expect to find, as if the index has not been fully built.

**Comment by mwjames** [comment] 2018-03-17 00:56
> The following error message occurred a number of times: PHP Warning:  mb_strtolower(): Unknown encoding ""

Well, this is related to PHP itself [0, 1] (see google with "PHP Warning:  mb_strtolower(): Unknown encoding ") which could be caused by various issue and without a specific example isn't actually solvable from the application (means SMW) side.

> Full-text search does seem to work most of the time,

This is a bit vague without explicit examples.

> but imperfectly: it does not always return what you'd expect to find, as if the index has not been fully built.

The MySQL/MariaDB fulltext support is known to have restrictions [3] that can hardly be overcome by SMW due its extrinsic limitations (see also #2731) and is also the reason why you want to look for a "real" fulltext search engine such as Elasticsearch (#3054).

[0] https://github.com/php/php-src/blob/master/ext/mbstring/tests/mb_strtolower_variation2.phpt
[1] https://stackoverflow.com/questions/18631777/warning-mb-convert-encoding-unknown-encoding-windows-1256
[3] https://dev.mysql.com/doc/refman/5.7/en/fulltext-restrictions.html

**Comment by kghbln** [comment] 2018-03-20 16:57
I have added the bug label preliminarily for now. I believe in the course of information it will become more clear what this one is about.

**Comment by D-Groenewegen** [comment] 2018-03-22 07:33
Thanks, James. Knowing that the issue happens somewhere server-side is already quite useful. You're right about a proper search engine like Elasticsearch being a better (faster and more efficient) alternative - I'll keep an eye out on #2274 and #3054. I just hoped that for searches like this where the scope is relatively small and circumscribed, this would be a way out and maybe it will.

**Comment by mwjames** [comment] 2018-03-25 13:34
> I just hoped that for searches like this where the scope is relatively small and circumscribed, this would be a way out and maybe it will.

My comment was directed towards the limitation set by MySQL/MariaDB itself where without specific examples it is difficult to elaborate on your "scope" reference. For example, prefix searches (e.g `fo*bar` to match `foobar`) are not possible with MySQL/MariaDB when relying on the fulltext (`MATCH ...`) [0, 1] because MySQL/MariaDB doesn't build an index for it. On the other hand, using the `LIKE` expression [2] will support those searches because it uses a different field type and a different index but is limited in length available for a search request. [3] contains some examples and comments on the matter of LIKE vs. MATCH.

[0] https://stackoverflow.com/questions/20679696/wildcard-search-in-mysql-full-text-search
[1] https://stackoverflow.com/questions/14776350/mysql-like-operator-vs-match-against
[2] https://makandracards.com/makandra/12813-performance-analysis-of-mysql-s-fulltext-indexes-and-like-queries-for-full-text-search
[3] https://sandbox.semantic-mediawiki.org/wiki/Issue/2499

**Comment by mwjames** [comment] 2018-07-14 08:01
> Well, this is related to PHP itself [0, 1] (see google with "PHP Warning: mb_strtolower(): Unknown encoding ") which could be caused by various issue and without a specific example isn't actually solvable from the application (means SMW) side.

As noted before without an example we are unable to replicate the specific issue raised about "HP Warning: mb_strtolower(): Unknown encoding".

As for "... Full-text search does seem to work most of the time, but imperfectly: it does not always return what you'd expect to find ..." I tried to elaborate as to why MySQL/MariaDB may not return all expected results.

SMW 3.0 supports Elasticsearch as drop-in replacement especially with the objective to support better full-text searches which are comparatively superior to what MySQL/MariaDB could deliver now or in future. Furthermore, SMW can only replicate the data to the backend and rely on the vendor implementation to produce acceptable results. Now, MySQL/MariaDB do not provide a lot of configurations to improve the situation.

In light of these findings, I will close this issue until more specific information are available.

**Closed by mwjames** 2018-07-14 08:01 UTC
Labels: bug
